package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.FmClientCopy;
import com.dcits.deposit.entity.FmClientCopyExample;
import com.dcits.deposit.facade.eo.FmClientCopyEO;
import com.dcits.deposit.enums.ClientIndicator;
import com.dcits.deposit.enums.ClientType;
import com.dcits.deposit.enums.ClientStatus;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.OccupationCode;
import com.dcits.deposit.enums.VerificationResult;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.CategoryType;
import com.dcits.deposit.enums.Sex;
import com.dcits.deposit.enums.OthBranchRegionalismCode;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.Education;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndustryLevel;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.TaxFlag;
import com.dcits.deposit.enums.City;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.ContactType;
import com.dcits.deposit.enums.CrRating;
import com.dcits.deposit.enums.ClientClass;
import com.dcits.deposit.enums.ClassLevel;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.TaxResidentFlag;
import com.dcits.deposit.enums.Nation;
import com.dcits.deposit.enums.SpokenLanguage;
import com.dcits.deposit.enums.Industry;
import com.dcits.deposit.enums.Company;

public final class FmClientCopyValueUtil {
    private FmClientCopyValueUtil() {
    }

    public static FmClientCopyEO entityToEo(FmClientCopy entity) {
        if (entity == null) {
            return null;
        }
        FmClientCopyEO eo = new FmClientCopyEO();
        eo.setClientNo(entity.getClientNo());
        eo.setClientName(entity.getClientName());
        eo.setEnClientName(entity.getEnClientName());
        eo.setChClientName(entity.getChClientName());
        eo.setClientShort(entity.getClientShort());
        eo.setClientIndicator(ClientIndicator.byValue(entity.getClientIndicator()));
        eo.setClientType(ClientType.byValue(entity.getClientType()));
        eo.setClientStatus(ClientStatus.byValue(entity.getClientStatus()));
        eo.setIsIndividual(IndividualFlag.byValue(entity.getIsIndividual()));
        eo.setAddress(entity.getAddress());
        eo.setInternalIndFlag(IndividualFlag.byValue(entity.getInternalIndFlag()));
        eo.setOccupationCode(OccupationCode.byValue(entity.getOccupationCode()));
        eo.setVerificationResult(VerificationResult.byValue(entity.getVerificationResult()));
        eo.setResidentFlag(IndividualFlag.byValue(entity.getResidentFlag()));
        eo.setMaturityDate(entity.getMaturityDate());
        eo.setInlandOffshore(IndividualFlag.byValue(entity.getInlandOffshore()));
        eo.setDocumentId(entity.getDocumentId());
        eo.setDocumentType(DocumentType.byValue(entity.getDocumentType()));
        eo.setIssCountry(IssCountry.byValue(entity.getIssCountry()));
        eo.setIssPlace(entity.getIssPlace());
        eo.setIssDate(entity.getIssDate());
        eo.setRepDocumentId(entity.getRepDocumentId());
        eo.setRepDocumentType(DocumentType.byValue(entity.getRepDocumentType()));
        eo.setLegalRep(entity.getLegalRep());
        eo.setRepExpiryDate(entity.getRepExpiryDate());
        eo.setCategoryType(CategoryType.byValue(entity.getCategoryType()));
        eo.setSex(Sex.byValue(entity.getSex()));
        eo.setState(OthBranchRegionalismCode.byValue(entity.getState()));
        eo.setCtrlBranch(AcctBranch.byValue(entity.getCtrlBranch()));
        eo.setBusinessScope(entity.getBusinessScope());
        eo.setEducation(Education.byValue(entity.getEducation()));
        eo.setWrnFlag(IndividualFlag.byValue(entity.getWrnFlag()));
        eo.setCorpFlag(IndividualFlag.byValue(entity.getCorpFlag()));
        eo.setIndustryLevel(IndustryLevel.byValue(entity.getIndustryLevel()));
        eo.setBranchInnerFlag(IndividualFlag.byValue(entity.getBranchInnerFlag()));
        eo.setPostalCode(entity.getPostalCode());
        eo.setTaxFlag(TaxFlag.byValue(entity.getTaxFlag()));
        eo.setCity(City.byValue(entity.getCity()));
        eo.setCountryLoc(IssCountry.byValue(entity.getCountryLoc()));
        eo.setContactType(ContactType.byValue(entity.getContactType()));
        eo.setContactTel(entity.getContactTel());
        eo.setMobilePhone(entity.getMobilePhone());
        eo.setBirthDate(entity.getBirthDate());
        eo.setCrRating(CrRating.byValue(entity.getCrRating()));
        eo.setGhoCustomerClass(entity.getGhoCustomerClass());
        eo.setClientClass(ClientClass.byValue(entity.getClientClass()));
        eo.setClassLevel(ClassLevel.byValue(entity.getClassLevel()));
        eo.setPrefFlag(IndividualFlag.byValue(entity.getPrefFlag()));
        eo.setCorporationFlag(IndividualFlag.byValue(entity.getCorporationFlag()));
        eo.setTaxResidentFlag(TaxResidentFlag.byValue(entity.getTaxResidentFlag()));
        eo.setNation(Nation.byValue(entity.getNation()));
        eo.setSpokenLanguage(SpokenLanguage.byValue(entity.getSpokenLanguage()));
        eo.setIndustry(Industry.byValue(entity.getIndustry()));
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setLastChangeUserId(entity.getLastChangeUserId());
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setSyncTranTimestamp(entity.getSyncTranTimestamp());
        eo.setCompany(Company.byValue(entity.getCompany()));
        return eo;
    }

    public static FmClientCopy eoToEntity(FmClientCopyEO eo) {
        if (eo == null) {
            return null;
        }
        FmClientCopy entity = new FmClientCopy();
        entity.setClientNo(eo.getClientNo());
        entity.setClientName(eo.getClientName());
        entity.setEnClientName(eo.getEnClientName());
        entity.setChClientName(eo.getChClientName());
        entity.setClientShort(eo.getClientShort());
        entity.setClientIndicator(eo.getClientIndicator() == null ? null : eo.getClientIndicator().getValue());
        entity.setClientType(eo.getClientType() == null ? null : eo.getClientType().getValue());
        entity.setClientStatus(eo.getClientStatus() == null ? null : eo.getClientStatus().getValue());
        entity.setIsIndividual(eo.getIsIndividual() == null ? null : eo.getIsIndividual().getValue());
        entity.setAddress(eo.getAddress());
        entity.setInternalIndFlag(eo.getInternalIndFlag() == null ? null : eo.getInternalIndFlag().getValue());
        entity.setOccupationCode(eo.getOccupationCode() == null ? null : eo.getOccupationCode().getValue());
        entity.setVerificationResult(eo.getVerificationResult() == null ? null : eo.getVerificationResult().getValue());
        entity.setResidentFlag(eo.getResidentFlag() == null ? null : eo.getResidentFlag().getValue());
        entity.setMaturityDate(eo.getMaturityDate());
        entity.setInlandOffshore(eo.getInlandOffshore() == null ? null : eo.getInlandOffshore().getValue());
        entity.setDocumentId(eo.getDocumentId());
        entity.setDocumentType(eo.getDocumentType() == null ? null : eo.getDocumentType().getValue());
        entity.setIssCountry(eo.getIssCountry() == null ? null : eo.getIssCountry().getValue());
        entity.setIssPlace(eo.getIssPlace());
        entity.setIssDate(eo.getIssDate());
        entity.setRepDocumentId(eo.getRepDocumentId());
        entity.setRepDocumentType(eo.getRepDocumentType() == null ? null : eo.getRepDocumentType().getValue());
        entity.setLegalRep(eo.getLegalRep());
        entity.setRepExpiryDate(eo.getRepExpiryDate());
        entity.setCategoryType(eo.getCategoryType() == null ? null : eo.getCategoryType().getValue());
        entity.setSex(eo.getSex() == null ? null : eo.getSex().getValue());
        entity.setState(eo.getState() == null ? null : eo.getState().getValue());
        entity.setCtrlBranch(eo.getCtrlBranch() == null ? null : eo.getCtrlBranch().getValue());
        entity.setBusinessScope(eo.getBusinessScope());
        entity.setEducation(eo.getEducation() == null ? null : eo.getEducation().getValue());
        entity.setWrnFlag(eo.getWrnFlag() == null ? null : eo.getWrnFlag().getValue());
        entity.setCorpFlag(eo.getCorpFlag() == null ? null : eo.getCorpFlag().getValue());
        entity.setIndustryLevel(eo.getIndustryLevel() == null ? null : eo.getIndustryLevel().getValue());
        entity.setBranchInnerFlag(eo.getBranchInnerFlag() == null ? null : eo.getBranchInnerFlag().getValue());
        entity.setPostalCode(eo.getPostalCode());
        entity.setTaxFlag(eo.getTaxFlag() == null ? null : eo.getTaxFlag().getValue());
        entity.setCity(eo.getCity() == null ? null : eo.getCity().getValue());
        entity.setCountryLoc(eo.getCountryLoc() == null ? null : eo.getCountryLoc().getValue());
        entity.setContactType(eo.getContactType() == null ? null : eo.getContactType().getValue());
        entity.setContactTel(eo.getContactTel());
        entity.setMobilePhone(eo.getMobilePhone());
        entity.setBirthDate(eo.getBirthDate());
        entity.setCrRating(eo.getCrRating() == null ? null : eo.getCrRating().getValue());
        entity.setGhoCustomerClass(eo.getGhoCustomerClass());
        entity.setClientClass(eo.getClientClass() == null ? null : eo.getClientClass().getValue());
        entity.setClassLevel(eo.getClassLevel() == null ? null : eo.getClassLevel().getValue());
        entity.setPrefFlag(eo.getPrefFlag() == null ? null : eo.getPrefFlag().getValue());
        entity.setCorporationFlag(eo.getCorporationFlag() == null ? null : eo.getCorporationFlag().getValue());
        entity.setTaxResidentFlag(eo.getTaxResidentFlag() == null ? null : eo.getTaxResidentFlag().getValue());
        entity.setNation(eo.getNation() == null ? null : eo.getNation().getValue());
        entity.setSpokenLanguage(eo.getSpokenLanguage() == null ? null : eo.getSpokenLanguage().getValue());
        entity.setIndustry(eo.getIndustry() == null ? null : eo.getIndustry().getValue());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setLastChangeUserId(eo.getLastChangeUserId());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setSyncTranTimestamp(eo.getSyncTranTimestamp());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        return entity;
    }

    public static FmClientCopyExample eoToEntityExample(FmClientCopyEO eo) {
        if (eo == null) {
            return null;
        }
        FmClientCopyExample example = new FmClientCopyExample();
        FmClientCopyExample.Criteria criteria = example.createCriteria();
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getClientName() != null) criteria.andClientNameEqualTo(eo.getClientName());
        if (eo.getEnClientName() != null) criteria.andEnClientNameEqualTo(eo.getEnClientName());
        if (eo.getChClientName() != null) criteria.andChClientNameEqualTo(eo.getChClientName());
        if (eo.getClientShort() != null) criteria.andClientShortEqualTo(eo.getClientShort());
        if (eo.getClientIndicator() != null) criteria.andClientIndicatorEqualTo(eo.getClientIndicator().getValue());
        if (eo.getClientType() != null) criteria.andClientTypeEqualTo(eo.getClientType().getValue());
        if (eo.getClientStatus() != null) criteria.andClientStatusEqualTo(eo.getClientStatus().getValue());
        if (eo.getIsIndividual() != null) criteria.andIsIndividualEqualTo(eo.getIsIndividual().getValue());
        if (eo.getAddress() != null) criteria.andAddressEqualTo(eo.getAddress());
        if (eo.getInternalIndFlag() != null) criteria.andInternalIndFlagEqualTo(eo.getInternalIndFlag().getValue());
        if (eo.getOccupationCode() != null) criteria.andOccupationCodeEqualTo(eo.getOccupationCode().getValue());
        if (eo.getVerificationResult() != null) criteria.andVerificationResultEqualTo(eo.getVerificationResult().getValue());
        if (eo.getResidentFlag() != null) criteria.andResidentFlagEqualTo(eo.getResidentFlag().getValue());
        if (eo.getMaturityDate() != null) criteria.andMaturityDateEqualTo(eo.getMaturityDate());
        if (eo.getInlandOffshore() != null) criteria.andInlandOffshoreEqualTo(eo.getInlandOffshore().getValue());
        if (eo.getDocumentId() != null) criteria.andDocumentIdEqualTo(eo.getDocumentId());
        if (eo.getDocumentType() != null) criteria.andDocumentTypeEqualTo(eo.getDocumentType().getValue());
        if (eo.getIssCountry() != null) criteria.andIssCountryEqualTo(eo.getIssCountry().getValue());
        if (eo.getIssPlace() != null) criteria.andIssPlaceEqualTo(eo.getIssPlace());
        if (eo.getIssDate() != null) criteria.andIssDateEqualTo(eo.getIssDate());
        if (eo.getRepDocumentId() != null) criteria.andRepDocumentIdEqualTo(eo.getRepDocumentId());
        if (eo.getRepDocumentType() != null) criteria.andRepDocumentTypeEqualTo(eo.getRepDocumentType().getValue());
        if (eo.getLegalRep() != null) criteria.andLegalRepEqualTo(eo.getLegalRep());
        if (eo.getRepExpiryDate() != null) criteria.andRepExpiryDateEqualTo(eo.getRepExpiryDate());
        if (eo.getCategoryType() != null) criteria.andCategoryTypeEqualTo(eo.getCategoryType().getValue());
        if (eo.getSex() != null) criteria.andSexEqualTo(eo.getSex().getValue());
        if (eo.getState() != null) criteria.andStateEqualTo(eo.getState().getValue());
        if (eo.getCtrlBranch() != null) criteria.andCtrlBranchEqualTo(eo.getCtrlBranch().getValue());
        if (eo.getBusinessScope() != null) criteria.andBusinessScopeEqualTo(eo.getBusinessScope());
        if (eo.getEducation() != null) criteria.andEducationEqualTo(eo.getEducation().getValue());
        if (eo.getWrnFlag() != null) criteria.andWrnFlagEqualTo(eo.getWrnFlag().getValue());
        if (eo.getCorpFlag() != null) criteria.andCorpFlagEqualTo(eo.getCorpFlag().getValue());
        if (eo.getIndustryLevel() != null) criteria.andIndustryLevelEqualTo(eo.getIndustryLevel().getValue());
        if (eo.getBranchInnerFlag() != null) criteria.andBranchInnerFlagEqualTo(eo.getBranchInnerFlag().getValue());
        if (eo.getPostalCode() != null) criteria.andPostalCodeEqualTo(eo.getPostalCode());
        if (eo.getTaxFlag() != null) criteria.andTaxFlagEqualTo(eo.getTaxFlag().getValue());
        if (eo.getCity() != null) criteria.andCityEqualTo(eo.getCity().getValue());
        if (eo.getCountryLoc() != null) criteria.andCountryLocEqualTo(eo.getCountryLoc().getValue());
        if (eo.getContactType() != null) criteria.andContactTypeEqualTo(eo.getContactType().getValue());
        if (eo.getContactTel() != null) criteria.andContactTelEqualTo(eo.getContactTel());
        if (eo.getMobilePhone() != null) criteria.andMobilePhoneEqualTo(eo.getMobilePhone());
        if (eo.getBirthDate() != null) criteria.andBirthDateEqualTo(eo.getBirthDate());
        if (eo.getCrRating() != null) criteria.andCrRatingEqualTo(eo.getCrRating().getValue());
        if (eo.getGhoCustomerClass() != null) criteria.andGhoCustomerClassEqualTo(eo.getGhoCustomerClass());
        if (eo.getClientClass() != null) criteria.andClientClassEqualTo(eo.getClientClass().getValue());
        if (eo.getClassLevel() != null) criteria.andClassLevelEqualTo(eo.getClassLevel().getValue());
        if (eo.getPrefFlag() != null) criteria.andPrefFlagEqualTo(eo.getPrefFlag().getValue());
        if (eo.getCorporationFlag() != null) criteria.andCorporationFlagEqualTo(eo.getCorporationFlag().getValue());
        if (eo.getTaxResidentFlag() != null) criteria.andTaxResidentFlagEqualTo(eo.getTaxResidentFlag().getValue());
        if (eo.getNation() != null) criteria.andNationEqualTo(eo.getNation().getValue());
        if (eo.getSpokenLanguage() != null) criteria.andSpokenLanguageEqualTo(eo.getSpokenLanguage().getValue());
        if (eo.getIndustry() != null) criteria.andIndustryEqualTo(eo.getIndustry().getValue());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getLastChangeUserId() != null) criteria.andLastChangeUserIdEqualTo(eo.getLastChangeUserId());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getSyncTranTimestamp() != null) criteria.andSyncTranTimestampEqualTo(eo.getSyncTranTimestamp());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        return example;
    }
}