package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbAcct;
import com.dcits.deposit.entity.RbAcctExample;
import com.dcits.deposit.facade.eo.RbAcctEO;
import com.dcits.deposit.enums.ClientType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.AcctClass;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.ProfitCenter;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.SourceType;
import com.dcits.deposit.enums.AcctStatus;
import com.dcits.deposit.enums.AcctStatus;
import com.dcits.deposit.enums.AcctType;
import com.dcits.deposit.enums.TermType;
import com.dcits.deposit.enums.AcctNature;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AllDraInd;
import com.dcits.deposit.enums.FixedCall;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.ReasonCode;
import com.dcits.deposit.enums.AutoRenewRollover;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.IntIndFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.BalType;
import com.dcits.deposit.enums.GlType;
import com.dcits.deposit.enums.OsaFlag;
import com.dcits.deposit.enums.OwnershipType;
import com.dcits.deposit.enums.RegionFlag;
import com.dcits.deposit.enums.AccountingStatus;
import com.dcits.deposit.enums.AccountingStatus;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.BusinessUnit;
import com.dcits.deposit.enums.SourceModule;
import com.dcits.deposit.enums.Company;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;

public final class RbAcctValueUtil {
    private RbAcctValueUtil() {
    }

    public static RbAcctEO entityToEo(RbAcct entity) {
        if (entity == null) {
            return null;
        }
        RbAcctEO eo = new RbAcctEO();
        eo.setInternalKey(entity.getInternalKey());
        eo.setClientNo(entity.getClientNo());
        eo.setClientType(ClientType.byValue(entity.getClientType()));
        eo.setIndividualFlag(IndividualFlag.byValue(entity.getIndividualFlag()));
        eo.setDocumentId(entity.getDocumentId());
        eo.setDocumentType(DocumentType.byValue(entity.getDocumentType()));
        eo.setIssCountry(IssCountry.byValue(entity.getIssCountry()));
        eo.setAcctClass(AcctClass.byValue(entity.getAcctClass()));
        eo.setCardNo(entity.getCardNo());
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setProdType(entity.getProdType());
        eo.setAcctCcy(AcctCcy.byValue(entity.getAcctCcy()));
        eo.setProfitCenter(ProfitCenter.byValue(entity.getProfitCenter()));
        eo.setAcctName(entity.getAcctName());
        eo.setAltAcctName(entity.getAltAcctName());
        eo.setAcctBranch(AcctBranch.byValue(entity.getAcctBranch()));
        eo.setAcctDesc(entity.getAcctDesc());
        eo.setSourceType(SourceType.byValue(entity.getSourceType()));
        eo.setAcctOpenDate(entity.getAcctOpenDate());
        eo.setEffectDate(entity.getEffectDate());
        eo.setOpenTranDate(entity.getOpenTranDate());
        eo.setAcctStatus(AcctStatus.byValue(entity.getAcctStatus()));
        eo.setAcctStatusPrev(AcctStatus.byValue(entity.getAcctStatusPrev()));
        eo.setAcctStatusUpdDate(entity.getAcctStatusUpdDate());
        eo.setAcctCloseDate(entity.getAcctCloseDate());
        eo.setAcctCloseUserId(entity.getAcctCloseUserId());
        eo.setAcctCloseReason(entity.getAcctCloseReason());
        eo.setAcctType(AcctType.byValue(entity.getAcctType()));
        eo.setTerm(entity.getTerm());
        eo.setTermType(TermType.byValue(entity.getTermType()));
        eo.setMaturityDate(entity.getMaturityDate());
        eo.setOriMaturityDate(entity.getOriMaturityDate());
        eo.setOrigAcctOpenDate(entity.getOrigAcctOpenDate());
        eo.setAcctNature(AcctNature.byValue(entity.getAcctNature()));
        eo.setAcctDueDate(entity.getAcctDueDate());
        eo.setAcctRealFlag(IndividualFlag.byValue(entity.getAcctRealFlag()));
        eo.setAcctResStatus(IndividualFlag.byValue(entity.getAcctResStatus()));
        eo.setAcctStopPay(IndividualFlag.byValue(entity.getAcctStopPay()));
        eo.setAllDepInd(IndividualFlag.byValue(entity.getAllDepInd()));
        eo.setAllDraInd(AllDraInd.byValue(entity.getAllDraInd()));
        eo.setFixedCall(FixedCall.byValue(entity.getFixedCall()));
        eo.setLeadAcctFlag(IndividualFlag.byValue(entity.getLeadAcctFlag()));
        eo.setAcctLicenseDate(entity.getAcctLicenseDate());
        eo.setAcctLicenseNo(entity.getAcctLicenseNo());
        eo.setMainProdType(entity.getMainProdType());
        eo.setMainBalFlag(IndividualFlag.byValue(entity.getMainBalFlag()));
        eo.setMainIntFlag(IndividualFlag.byValue(entity.getMainIntFlag()));
        eo.setParentInternalKey(entity.getParentInternalKey());
        eo.setReasonCode(ReasonCode.byValue(entity.getReasonCode()));
        eo.setAccountingStatusUpdDate(entity.getAccountingStatusUpdDate());
        eo.setApprovalDate(entity.getApprovalDate());
        eo.setAutoRenewRollover(AutoRenewRollover.byValue(entity.getAutoRenewRollover()));
        eo.setPartialRenewRoll(IndividualFlag.byValue(entity.getPartialRenewRoll()));
        eo.setTimesRenewed(entity.getTimesRenewed());
        eo.setRenewNo(entity.getRenewNo());
        eo.setRolloverNo(entity.getRolloverNo());
        eo.setTimesRolledover(entity.getTimesRolledover());
        eo.setAddtlPrincipal(IndividualFlag.byValue(entity.getAddtlPrincipal()));
        eo.setDormantDate(entity.getDormantDate());
        eo.setLastTranDate(entity.getLastTranDate());
        eo.setApplyBranch(AcctBranch.byValue(entity.getApplyBranch()));
        eo.setHomeBranch(AcctBranch.byValue(entity.getHomeBranch()));
        eo.setApprLetterNo(entity.getApprLetterNo());
        eo.setIntIndFlag(IntIndFlag.byValue(entity.getIntIndFlag()));
        eo.setAutoSettleFlag(IndividualFlag.byValue(entity.getAutoSettleFlag()));
        eo.setBalType(BalType.byValue(entity.getBalType()));
        eo.setGlType(GlType.byValue(entity.getGlType()));
        eo.setOsaFlag(OsaFlag.byValue(entity.getOsaFlag()));
        eo.setOwnershipType(OwnershipType.byValue(entity.getOwnershipType()));
        eo.setRegionFlag(RegionFlag.byValue(entity.getRegionFlag()));
        eo.setAccountingStatus(AccountingStatus.byValue(entity.getAccountingStatus()));
        eo.setAccountingStatusPrev(AccountingStatus.byValue(entity.getAccountingStatusPrev()));
        eo.setAcctExec(entity.getAcctExec());
        eo.setCheckedFlag(IndividualFlag.byValue(entity.getCheckedFlag()));
        eo.setManagementFreeFlag(IndividualFlag.byValue(entity.getManagementFreeFlag()));
        eo.setOldProdType(entity.getOldProdType());
        eo.setImpoundFad(IndividualFlag.byValue(entity.getImpoundFad()));
        eo.setBusinessUnit(BusinessUnit.byValue(entity.getBusinessUnit()));
        eo.setDacValue(entity.getDacValue());
        eo.setSourceModule(SourceModule.byValue(entity.getSourceModule()));
        eo.setTerminalId(entity.getTerminalId());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setApprUserId(entity.getApprUserId());
        eo.setUserId(entity.getUserId());
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setLastChangeUserId(entity.getLastChangeUserId());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setRecoverFlag(IndividualFlag.byValue(entity.getRecoverFlag()));
        eo.setJointAcctFlag(IndividualFlag.byValue(entity.getJointAcctFlag()));
        eo.setAgreementId(entity.getAgreementId());
        eo.setAgreProdType(entity.getAgreProdType());
        eo.setAcctNameEn(entity.getAcctNameEn());
        eo.setAmendDate(entity.getAmendDate());
        eo.setOpenUserId(entity.getOpenUserId());
        eo.setInnerAcctNo(entity.getInnerAcctNo());
        eo.setAcctNo(entity.getAcctNo());
        return eo;
    }

    public static RbAcct eoToEntity(RbAcctEO eo) {
        if (eo == null) {
            return null;
        }
        RbAcct entity = new RbAcct();
        entity.setInternalKey(eo.getInternalKey());
        entity.setClientNo(eo.getClientNo());
        entity.setClientType(eo.getClientType() == null ? null : eo.getClientType().getValue());
        entity.setIndividualFlag(eo.getIndividualFlag() == null ? null : eo.getIndividualFlag().getValue());
        entity.setDocumentId(eo.getDocumentId());
        entity.setDocumentType(eo.getDocumentType() == null ? null : eo.getDocumentType().getValue());
        entity.setIssCountry(eo.getIssCountry() == null ? null : eo.getIssCountry().getValue());
        entity.setAcctClass(eo.getAcctClass() == null ? null : eo.getAcctClass().getValue());
        entity.setCardNo(eo.getCardNo());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setProdType(eo.getProdType());
        entity.setAcctCcy(eo.getAcctCcy() == null ? null : eo.getAcctCcy().getValue());
        entity.setProfitCenter(eo.getProfitCenter() == null ? null : eo.getProfitCenter().getValue());
        entity.setAcctName(eo.getAcctName());
        entity.setAltAcctName(eo.getAltAcctName());
        entity.setAcctBranch(eo.getAcctBranch() == null ? null : eo.getAcctBranch().getValue());
        entity.setAcctDesc(eo.getAcctDesc());
        entity.setSourceType(eo.getSourceType() == null ? null : eo.getSourceType().getValue());
        entity.setAcctOpenDate(eo.getAcctOpenDate());
        entity.setEffectDate(eo.getEffectDate());
        entity.setOpenTranDate(eo.getOpenTranDate());
        entity.setAcctStatus(eo.getAcctStatus() == null ? null : eo.getAcctStatus().getValue());
        entity.setAcctStatusPrev(eo.getAcctStatusPrev() == null ? null : eo.getAcctStatusPrev().getValue());
        entity.setAcctStatusUpdDate(eo.getAcctStatusUpdDate());
        entity.setAcctCloseDate(eo.getAcctCloseDate());
        entity.setAcctCloseUserId(eo.getAcctCloseUserId());
        entity.setAcctCloseReason(eo.getAcctCloseReason());
        entity.setAcctType(eo.getAcctType() == null ? null : eo.getAcctType().getValue());
        entity.setTerm(eo.getTerm());
        entity.setTermType(eo.getTermType() == null ? null : eo.getTermType().getValue());
        entity.setMaturityDate(eo.getMaturityDate());
        entity.setOriMaturityDate(eo.getOriMaturityDate());
        entity.setOrigAcctOpenDate(eo.getOrigAcctOpenDate());
        entity.setAcctNature(eo.getAcctNature() == null ? null : eo.getAcctNature().getValue());
        entity.setAcctDueDate(eo.getAcctDueDate());
        entity.setAcctRealFlag(eo.getAcctRealFlag() == null ? null : eo.getAcctRealFlag().getValue());
        entity.setAcctResStatus(eo.getAcctResStatus() == null ? null : eo.getAcctResStatus().getValue());
        entity.setAcctStopPay(eo.getAcctStopPay() == null ? null : eo.getAcctStopPay().getValue());
        entity.setAllDepInd(eo.getAllDepInd() == null ? null : eo.getAllDepInd().getValue());
        entity.setAllDraInd(eo.getAllDraInd() == null ? null : eo.getAllDraInd().getValue());
        entity.setFixedCall(eo.getFixedCall() == null ? null : eo.getFixedCall().getValue());
        entity.setLeadAcctFlag(eo.getLeadAcctFlag() == null ? null : eo.getLeadAcctFlag().getValue());
        entity.setAcctLicenseDate(eo.getAcctLicenseDate());
        entity.setAcctLicenseNo(eo.getAcctLicenseNo());
        entity.setMainProdType(eo.getMainProdType());
        entity.setMainBalFlag(eo.getMainBalFlag() == null ? null : eo.getMainBalFlag().getValue());
        entity.setMainIntFlag(eo.getMainIntFlag() == null ? null : eo.getMainIntFlag().getValue());
        entity.setParentInternalKey(eo.getParentInternalKey());
        entity.setReasonCode(eo.getReasonCode() == null ? null : eo.getReasonCode().getValue());
        entity.setAccountingStatusUpdDate(eo.getAccountingStatusUpdDate());
        entity.setApprovalDate(eo.getApprovalDate());
        entity.setAutoRenewRollover(eo.getAutoRenewRollover() == null ? null : eo.getAutoRenewRollover().getValue());
        entity.setPartialRenewRoll(eo.getPartialRenewRoll() == null ? null : eo.getPartialRenewRoll().getValue());
        entity.setTimesRenewed(eo.getTimesRenewed());
        entity.setRenewNo(eo.getRenewNo());
        entity.setRolloverNo(eo.getRolloverNo());
        entity.setTimesRolledover(eo.getTimesRolledover());
        entity.setAddtlPrincipal(eo.getAddtlPrincipal() == null ? null : eo.getAddtlPrincipal().getValue());
        entity.setDormantDate(eo.getDormantDate());
        entity.setLastTranDate(eo.getLastTranDate());
        entity.setApplyBranch(eo.getApplyBranch() == null ? null : eo.getApplyBranch().getValue());
        entity.setHomeBranch(eo.getHomeBranch() == null ? null : eo.getHomeBranch().getValue());
        entity.setApprLetterNo(eo.getApprLetterNo());
        entity.setIntIndFlag(eo.getIntIndFlag() == null ? null : eo.getIntIndFlag().getValue());
        entity.setAutoSettleFlag(eo.getAutoSettleFlag() == null ? null : eo.getAutoSettleFlag().getValue());
        entity.setBalType(eo.getBalType() == null ? null : eo.getBalType().getValue());
        entity.setGlType(eo.getGlType() == null ? null : eo.getGlType().getValue());
        entity.setOsaFlag(eo.getOsaFlag() == null ? null : eo.getOsaFlag().getValue());
        entity.setOwnershipType(eo.getOwnershipType() == null ? null : eo.getOwnershipType().getValue());
        entity.setRegionFlag(eo.getRegionFlag() == null ? null : eo.getRegionFlag().getValue());
        entity.setAccountingStatus(eo.getAccountingStatus() == null ? null : eo.getAccountingStatus().getValue());
        entity.setAccountingStatusPrev(eo.getAccountingStatusPrev() == null ? null : eo.getAccountingStatusPrev().getValue());
        entity.setAcctExec(eo.getAcctExec());
        entity.setCheckedFlag(eo.getCheckedFlag() == null ? null : eo.getCheckedFlag().getValue());
        entity.setManagementFreeFlag(eo.getManagementFreeFlag() == null ? null : eo.getManagementFreeFlag().getValue());
        entity.setOldProdType(eo.getOldProdType());
        entity.setImpoundFad(eo.getImpoundFad() == null ? null : eo.getImpoundFad().getValue());
        entity.setBusinessUnit(eo.getBusinessUnit() == null ? null : eo.getBusinessUnit().getValue());
        entity.setDacValue(eo.getDacValue());
        entity.setSourceModule(eo.getSourceModule() == null ? null : eo.getSourceModule().getValue());
        entity.setTerminalId(eo.getTerminalId());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setApprUserId(eo.getApprUserId());
        entity.setUserId(eo.getUserId());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setLastChangeUserId(eo.getLastChangeUserId());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setRecoverFlag(eo.getRecoverFlag() == null ? null : eo.getRecoverFlag().getValue());
        entity.setJointAcctFlag(eo.getJointAcctFlag() == null ? null : eo.getJointAcctFlag().getValue());
        entity.setAgreementId(eo.getAgreementId());
        entity.setAgreProdType(eo.getAgreProdType());
        entity.setAcctNameEn(eo.getAcctNameEn());
        entity.setAmendDate(eo.getAmendDate());
        entity.setOpenUserId(eo.getOpenUserId());
        entity.setInnerAcctNo(eo.getInnerAcctNo());
        entity.setAcctNo(eo.getAcctNo());
        return entity;
    }

    public static RbAcctExample eoToEntityExample(RbAcctEO eo) {
        if (eo == null) {
            return null;
        }
        RbAcctExample example = new RbAcctExample();
        RbAcctExample.Criteria criteria = example.createCriteria();
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getClientType() != null) criteria.andClientTypeEqualTo(eo.getClientType().getValue());
        if (eo.getIndividualFlag() != null) criteria.andIndividualFlagEqualTo(eo.getIndividualFlag().getValue());
        if (eo.getDocumentId() != null) criteria.andDocumentIdEqualTo(eo.getDocumentId());
        if (eo.getDocumentType() != null) criteria.andDocumentTypeEqualTo(eo.getDocumentType().getValue());
        if (eo.getIssCountry() != null) criteria.andIssCountryEqualTo(eo.getIssCountry().getValue());
        if (eo.getAcctClass() != null) criteria.andAcctClassEqualTo(eo.getAcctClass().getValue());
        if (eo.getCardNo() != null) criteria.andCardNoEqualTo(eo.getCardNo());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getProdType() != null) criteria.andProdTypeEqualTo(eo.getProdType());
        if (eo.getAcctCcy() != null) criteria.andAcctCcyEqualTo(eo.getAcctCcy().getValue());
        if (eo.getProfitCenter() != null) criteria.andProfitCenterEqualTo(eo.getProfitCenter().getValue());
        if (eo.getAcctName() != null) criteria.andAcctNameEqualTo(eo.getAcctName());
        if (eo.getAltAcctName() != null) criteria.andAltAcctNameEqualTo(eo.getAltAcctName());
        if (eo.getAcctBranch() != null) criteria.andAcctBranchEqualTo(eo.getAcctBranch().getValue());
        if (eo.getAcctDesc() != null) criteria.andAcctDescEqualTo(eo.getAcctDesc());
        if (eo.getSourceType() != null) criteria.andSourceTypeEqualTo(eo.getSourceType().getValue());
        if (eo.getAcctOpenDate() != null) criteria.andAcctOpenDateEqualTo(eo.getAcctOpenDate());
        if (eo.getEffectDate() != null) criteria.andEffectDateEqualTo(eo.getEffectDate());
        if (eo.getOpenTranDate() != null) criteria.andOpenTranDateEqualTo(eo.getOpenTranDate());
        if (eo.getAcctStatus() != null) criteria.andAcctStatusEqualTo(eo.getAcctStatus().getValue());
        if (eo.getAcctStatusPrev() != null) criteria.andAcctStatusPrevEqualTo(eo.getAcctStatusPrev().getValue());
        if (eo.getAcctStatusUpdDate() != null) criteria.andAcctStatusUpdDateEqualTo(eo.getAcctStatusUpdDate());
        if (eo.getAcctCloseDate() != null) criteria.andAcctCloseDateEqualTo(eo.getAcctCloseDate());
        if (eo.getAcctCloseUserId() != null) criteria.andAcctCloseUserIdEqualTo(eo.getAcctCloseUserId());
        if (eo.getAcctCloseReason() != null) criteria.andAcctCloseReasonEqualTo(eo.getAcctCloseReason());
        if (eo.getAcctType() != null) criteria.andAcctTypeEqualTo(eo.getAcctType().getValue());
        if (eo.getTerm() != null) criteria.andTermEqualTo(eo.getTerm());
        if (eo.getTermType() != null) criteria.andTermTypeEqualTo(eo.getTermType().getValue());
        if (eo.getMaturityDate() != null) criteria.andMaturityDateEqualTo(eo.getMaturityDate());
        if (eo.getOriMaturityDate() != null) criteria.andOriMaturityDateEqualTo(eo.getOriMaturityDate());
        if (eo.getOrigAcctOpenDate() != null) criteria.andOrigAcctOpenDateEqualTo(eo.getOrigAcctOpenDate());
        if (eo.getAcctNature() != null) criteria.andAcctNatureEqualTo(eo.getAcctNature().getValue());
        if (eo.getAcctDueDate() != null) criteria.andAcctDueDateEqualTo(eo.getAcctDueDate());
        if (eo.getAcctRealFlag() != null) criteria.andAcctRealFlagEqualTo(eo.getAcctRealFlag().getValue());
        if (eo.getAcctResStatus() != null) criteria.andAcctResStatusEqualTo(eo.getAcctResStatus().getValue());
        if (eo.getAcctStopPay() != null) criteria.andAcctStopPayEqualTo(eo.getAcctStopPay().getValue());
        if (eo.getAllDepInd() != null) criteria.andAllDepIndEqualTo(eo.getAllDepInd().getValue());
        if (eo.getAllDraInd() != null) criteria.andAllDraIndEqualTo(eo.getAllDraInd().getValue());
        if (eo.getFixedCall() != null) criteria.andFixedCallEqualTo(eo.getFixedCall().getValue());
        if (eo.getLeadAcctFlag() != null) criteria.andLeadAcctFlagEqualTo(eo.getLeadAcctFlag().getValue());
        if (eo.getAcctLicenseDate() != null) criteria.andAcctLicenseDateEqualTo(eo.getAcctLicenseDate());
        if (eo.getAcctLicenseNo() != null) criteria.andAcctLicenseNoEqualTo(eo.getAcctLicenseNo());
        if (eo.getMainProdType() != null) criteria.andMainProdTypeEqualTo(eo.getMainProdType());
        if (eo.getMainBalFlag() != null) criteria.andMainBalFlagEqualTo(eo.getMainBalFlag().getValue());
        if (eo.getMainIntFlag() != null) criteria.andMainIntFlagEqualTo(eo.getMainIntFlag().getValue());
        if (eo.getParentInternalKey() != null) criteria.andParentInternalKeyEqualTo(eo.getParentInternalKey());
        if (eo.getReasonCode() != null) criteria.andReasonCodeEqualTo(eo.getReasonCode().getValue());
        if (eo.getAccountingStatusUpdDate() != null) criteria.andAccountingStatusUpdDateEqualTo(eo.getAccountingStatusUpdDate());
        if (eo.getApprovalDate() != null) criteria.andApprovalDateEqualTo(eo.getApprovalDate());
        if (eo.getAutoRenewRollover() != null) criteria.andAutoRenewRolloverEqualTo(eo.getAutoRenewRollover().getValue());
        if (eo.getPartialRenewRoll() != null) criteria.andPartialRenewRollEqualTo(eo.getPartialRenewRoll().getValue());
        if (eo.getTimesRenewed() != null) criteria.andTimesRenewedEqualTo(eo.getTimesRenewed());
        if (eo.getRenewNo() != null) criteria.andRenewNoEqualTo(eo.getRenewNo());
        if (eo.getRolloverNo() != null) criteria.andRolloverNoEqualTo(eo.getRolloverNo());
        if (eo.getTimesRolledover() != null) criteria.andTimesRolledoverEqualTo(eo.getTimesRolledover());
        if (eo.getAddtlPrincipal() != null) criteria.andAddtlPrincipalEqualTo(eo.getAddtlPrincipal().getValue());
        if (eo.getDormantDate() != null) criteria.andDormantDateEqualTo(eo.getDormantDate());
        if (eo.getLastTranDate() != null) criteria.andLastTranDateEqualTo(eo.getLastTranDate());
        if (eo.getApplyBranch() != null) criteria.andApplyBranchEqualTo(eo.getApplyBranch().getValue());
        if (eo.getHomeBranch() != null) criteria.andHomeBranchEqualTo(eo.getHomeBranch().getValue());
        if (eo.getApprLetterNo() != null) criteria.andApprLetterNoEqualTo(eo.getApprLetterNo());
        if (eo.getIntIndFlag() != null) criteria.andIntIndFlagEqualTo(eo.getIntIndFlag().getValue());
        if (eo.getAutoSettleFlag() != null) criteria.andAutoSettleFlagEqualTo(eo.getAutoSettleFlag().getValue());
        if (eo.getBalType() != null) criteria.andBalTypeEqualTo(eo.getBalType().getValue());
        if (eo.getGlType() != null) criteria.andGlTypeEqualTo(eo.getGlType().getValue());
        if (eo.getOsaFlag() != null) criteria.andOsaFlagEqualTo(eo.getOsaFlag().getValue());
        if (eo.getOwnershipType() != null) criteria.andOwnershipTypeEqualTo(eo.getOwnershipType().getValue());
        if (eo.getRegionFlag() != null) criteria.andRegionFlagEqualTo(eo.getRegionFlag().getValue());
        if (eo.getAccountingStatus() != null) criteria.andAccountingStatusEqualTo(eo.getAccountingStatus().getValue());
        if (eo.getAccountingStatusPrev() != null) criteria.andAccountingStatusPrevEqualTo(eo.getAccountingStatusPrev().getValue());
        if (eo.getAcctExec() != null) criteria.andAcctExecEqualTo(eo.getAcctExec());
        if (eo.getCheckedFlag() != null) criteria.andCheckedFlagEqualTo(eo.getCheckedFlag().getValue());
        if (eo.getManagementFreeFlag() != null) criteria.andManagementFreeFlagEqualTo(eo.getManagementFreeFlag().getValue());
        if (eo.getOldProdType() != null) criteria.andOldProdTypeEqualTo(eo.getOldProdType());
        if (eo.getImpoundFad() != null) criteria.andImpoundFadEqualTo(eo.getImpoundFad().getValue());
        if (eo.getBusinessUnit() != null) criteria.andBusinessUnitEqualTo(eo.getBusinessUnit().getValue());
        if (eo.getDacValue() != null) criteria.andDacValueEqualTo(eo.getDacValue());
        if (eo.getSourceModule() != null) criteria.andSourceModuleEqualTo(eo.getSourceModule().getValue());
        if (eo.getTerminalId() != null) criteria.andTerminalIdEqualTo(eo.getTerminalId());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getApprUserId() != null) criteria.andApprUserIdEqualTo(eo.getApprUserId());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getLastChangeUserId() != null) criteria.andLastChangeUserIdEqualTo(eo.getLastChangeUserId());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getRecoverFlag() != null) criteria.andRecoverFlagEqualTo(eo.getRecoverFlag().getValue());
        if (eo.getJointAcctFlag() != null) criteria.andJointAcctFlagEqualTo(eo.getJointAcctFlag().getValue());
        if (eo.getAgreementId() != null) criteria.andAgreementIdEqualTo(eo.getAgreementId());
        if (eo.getAgreProdType() != null) criteria.andAgreProdTypeEqualTo(eo.getAgreProdType());
        if (eo.getAcctNameEn() != null) criteria.andAcctNameEnEqualTo(eo.getAcctNameEn());
        if (eo.getAmendDate() != null) criteria.andAmendDateEqualTo(eo.getAmendDate());
        if (eo.getOpenUserId() != null) criteria.andOpenUserIdEqualTo(eo.getOpenUserId());
        if (eo.getInnerAcctNo() != null) criteria.andInnerAcctNoEqualTo(eo.getInnerAcctNo());
        if (eo.getAcctNo() != null) criteria.andAcctNoEqualTo(eo.getAcctNo());
        return example;
    }
}