package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbAcctAttach;
import com.dcits.deposit.entity.RbAcctAttachExample;
import com.dcits.deposit.facade.eo.RbAcctAttachEO;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AcctNature;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.BalUpdType;
import com.dcits.deposit.enums.BalanceWay;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.HangWriteOffFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.ProdClass;
import com.dcits.deposit.enums.SpecialProdClass;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AnnualStatus;
import com.dcits.deposit.enums.BlacklistStatus;
import com.dcits.deposit.enums.MsgStatus;
import com.dcits.deposit.enums.Company;
import com.dcits.deposit.enums.TermType;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.DepositNature;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.CaseInvolvedFlag;
import com.dcits.deposit.enums.AcctOpenMode;
import com.dcits.deposit.enums.AgreementDepositType;
import com.dcits.deposit.enums.AcctOpenType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AcctRiskLevel;
import com.dcits.deposit.enums.FarmerFlag;
import com.dcits.deposit.enums.AmountNature;
import com.dcits.deposit.enums.ManageType;
import com.dcits.deposit.enums.AcctProperty2;
import com.dcits.deposit.enums.CheckCertificateType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.Treatment;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.StageLimitClass;
import com.dcits.deposit.enums.SimpleAcct;
import com.dcits.deposit.enums.LoanFundFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AcctVerifyResult;
import com.dcits.deposit.enums.AcctTellerSignFlag;

public final class RbAcctAttachValueUtil {
    private RbAcctAttachValueUtil() {
    }

    public static RbAcctAttachEO entityToEo(RbAcctAttach entity) {
        if (entity == null) {
            return null;
        }
        RbAcctAttachEO eo = new RbAcctAttachEO();
        eo.setCounterCroBrchDebtFlag(IndividualFlag.byValue(entity.getCounterCroBrchDebtFlag()));
        eo.setCounterCroBrchCretFlag(IndividualFlag.byValue(entity.getCounterCroBrchCretFlag()));
        eo.setInternalKey(entity.getInternalKey());
        eo.setGlCode(entity.getGlCode());
        eo.setAcctProofReason(entity.getAcctProofReason());
        eo.setAcctProperty(AcctNature.byValue(entity.getAcctProperty()));
        eo.setBalChgInd(IndividualFlag.byValue(entity.getBalChgInd()));
        eo.setBalUpdType(BalUpdType.byValue(entity.getBalUpdType()));
        eo.setBalanceWay(BalanceWay.byValue(entity.getBalanceWay()));
        eo.setOdFacility(IndividualFlag.byValue(entity.getOdFacility()));
        eo.setCycleIntFlag(IndividualFlag.byValue(entity.getCycleIntFlag()));
        eo.setAutoSettleFlag(IndividualFlag.byValue(entity.getAutoSettleFlag()));
        eo.setAutoDep(IndividualFlag.byValue(entity.getAutoDep()));
        eo.setManualAccountFlag(IndividualFlag.byValue(entity.getManualAccountFlag()));
        eo.setFtaAcctFlag(IndividualFlag.byValue(entity.getFtaAcctFlag()));
        eo.setFtaCode(entity.getFtaCode());
        eo.setHangWriteOffFlag(HangWriteOffFlag.byValue(entity.getHangWriteOffFlag()));
        eo.setHangTerm(entity.getHangTerm());
        eo.setUnBindDepFlag(IndividualFlag.byValue(entity.getUnBindDepFlag()));
        eo.setProdClass(ProdClass.byValue(entity.getProdClass()));
        eo.setSpecialProdClass(SpecialProdClass.byValue(entity.getSpecialProdClass()));
        eo.setStageCode(entity.getStageCode());
        eo.setAnnualFlag(IndividualFlag.byValue(entity.getAnnualFlag()));
        eo.setAnnualStatus(AnnualStatus.byValue(entity.getAnnualStatus()));
        eo.setLastResetDate(entity.getLastResetDate());
        eo.setLastStopDate(entity.getLastStopDate());
        eo.setBlacklistStatus(BlacklistStatus.byValue(entity.getBlacklistStatus()));
        eo.setLastBlacklistDate(entity.getLastBlacklistDate());
        eo.setFreeSum(entity.getFreeSum());
        eo.setMsgStatus(MsgStatus.byValue(entity.getMsgStatus()));
        eo.setClientNo(entity.getClientNo());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setAutoRenewTerm(entity.getAutoRenewTerm());
        eo.setAutoRenewTermType(TermType.byValue(entity.getAutoRenewTermType()));
        eo.setTotalDrawAmt(entity.getTotalDrawAmt());
        eo.setAllDraIntBranch(AcctBranch.byValue(entity.getAllDraIntBranch()));
        eo.setAllowSuspendFlag(IndividualFlag.byValue(entity.getAllowSuspendFlag()));
        eo.setDepositNature(DepositNature.byValue(entity.getDepositNature()));
        eo.setIsSellCheque(IndividualFlag.byValue(entity.getIsSellCheque()));
        eo.setCaseInvolvedFlag(CaseInvolvedFlag.byValue(entity.getCaseInvolvedFlag()));
        eo.setPreDebtDate(entity.getPreDebtDate());
        eo.setApprovalNo(entity.getApprovalNo());
        eo.setAgreementId(entity.getAgreementId());
        eo.setAcctOpenMode(AcctOpenMode.byValue(entity.getAcctOpenMode()));
        eo.setAgreementDepositType(AgreementDepositType.byValue(entity.getAgreementDepositType()));
        eo.setNextDepDay(entity.getNextDepDay());
        eo.setReOpenDate(entity.getReOpenDate());
        eo.setAcctOpenType(AcctOpenType.byValue(entity.getAcctOpenType()));
        eo.setTaxRate(entity.getTaxRate());
        eo.setManageFlag(IndividualFlag.byValue(entity.getManageFlag()));
        eo.setIntTaxLevy(IndividualFlag.byValue(entity.getIntTaxLevy()));
        eo.setAcctRiskLevel(AcctRiskLevel.byValue(entity.getAcctRiskLevel()));
        eo.setFarmerFlag(FarmerFlag.byValue(entity.getFarmerFlag()));
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setCheckCertificateAmt(entity.getCheckCertificateAmt());
        eo.setManageContent(entity.getManageContent());
        eo.setTaxDiscountMaturityDate(entity.getTaxDiscountMaturityDate());
        eo.setAmountNature(AmountNature.byValue(entity.getAmountNature()));
        eo.setManageType(ManageType.byValue(entity.getManageType()));
        eo.setAcctChannelFlag(entity.getAcctChannelFlag());
        eo.setAcctProperty2(AcctProperty2.byValue(entity.getAcctProperty2()));
        eo.setCheckCertificateType(CheckCertificateType.byValue(entity.getCheckCertificateType()));
        eo.setDelayPayInt(IndividualFlag.byValue(entity.getDelayPayInt()));
        eo.setFastOpenAcctFlag(IndividualFlag.byValue(entity.getFastOpenAcctFlag()));
        eo.setFirstDrawDate(entity.getFirstDrawDate());
        eo.setOnlineFlag(entity.getOnlineFlag());
        eo.setSpecDay(entity.getSpecDay());
        eo.setTreatment(Treatment.byValue(entity.getTreatment()));
        eo.setBackToDate(entity.getBackToDate());
        eo.setBothLimitFlag(IndividualFlag.byValue(entity.getBothLimitFlag()));
        eo.setCaseInvolvedDate(entity.getCaseInvolvedDate());
        eo.setCaseInvolvedReason(entity.getCaseInvolvedReason());
        eo.setPrivateAcctFlag(IndividualFlag.byValue(entity.getPrivateAcctFlag()));
        eo.setAnnualDate(entity.getAnnualDate());
        eo.setSecretAcct(IndividualFlag.byValue(entity.getSecretAcct()));
        eo.setPromoterName(entity.getPromoterName());
        eo.setPromoterCode(entity.getPromoterCode());
        eo.setAcctExecName(entity.getAcctExecName());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setAcctExecCode(entity.getAcctExecCode());
        eo.setLineOwnerShip(entity.getLineOwnerShip());
        eo.setIsAllowClose(IndividualFlag.byValue(entity.getIsAllowClose()));
        eo.setStageLimitClass(StageLimitClass.byValue(entity.getStageLimitClass()));
        eo.setTermLack(entity.getTermLack());
        eo.setAddTotalTerm(entity.getAddTotalTerm());
        eo.setSimpleAcct(SimpleAcct.byValue(entity.getSimpleAcct()));
        eo.setLoanFundFlag(LoanFundFlag.byValue(entity.getLoanFundFlag()));
        eo.setCollatInd(IndividualFlag.byValue(entity.getCollatInd()));
        eo.setAcctVerifyFlag(IndividualFlag.byValue(entity.getAcctVerifyFlag()));
        eo.setAcctVerifyResult(AcctVerifyResult.byValue(entity.getAcctVerifyResult()));
        eo.setAcctProofFlag(entity.getAcctProofFlag());
        eo.setAcctTellerSignFlag(AcctTellerSignFlag.byValue(entity.getAcctTellerSignFlag()));
        return eo;
    }

    public static RbAcctAttach eoToEntity(RbAcctAttachEO eo) {
        if (eo == null) {
            return null;
        }
        RbAcctAttach entity = new RbAcctAttach();
        entity.setCounterCroBrchDebtFlag(eo.getCounterCroBrchDebtFlag() == null ? null : eo.getCounterCroBrchDebtFlag().getValue());
        entity.setCounterCroBrchCretFlag(eo.getCounterCroBrchCretFlag() == null ? null : eo.getCounterCroBrchCretFlag().getValue());
        entity.setInternalKey(eo.getInternalKey());
        entity.setGlCode(eo.getGlCode());
        entity.setAcctProofReason(eo.getAcctProofReason());
        entity.setAcctProperty(eo.getAcctProperty() == null ? null : eo.getAcctProperty().getValue());
        entity.setBalChgInd(eo.getBalChgInd() == null ? null : eo.getBalChgInd().getValue());
        entity.setBalUpdType(eo.getBalUpdType() == null ? null : eo.getBalUpdType().getValue());
        entity.setBalanceWay(eo.getBalanceWay() == null ? null : eo.getBalanceWay().getValue());
        entity.setOdFacility(eo.getOdFacility() == null ? null : eo.getOdFacility().getValue());
        entity.setCycleIntFlag(eo.getCycleIntFlag() == null ? null : eo.getCycleIntFlag().getValue());
        entity.setAutoSettleFlag(eo.getAutoSettleFlag() == null ? null : eo.getAutoSettleFlag().getValue());
        entity.setAutoDep(eo.getAutoDep() == null ? null : eo.getAutoDep().getValue());
        entity.setManualAccountFlag(eo.getManualAccountFlag() == null ? null : eo.getManualAccountFlag().getValue());
        entity.setFtaAcctFlag(eo.getFtaAcctFlag() == null ? null : eo.getFtaAcctFlag().getValue());
        entity.setFtaCode(eo.getFtaCode());
        entity.setHangWriteOffFlag(eo.getHangWriteOffFlag() == null ? null : eo.getHangWriteOffFlag().getValue());
        entity.setHangTerm(eo.getHangTerm());
        entity.setUnBindDepFlag(eo.getUnBindDepFlag() == null ? null : eo.getUnBindDepFlag().getValue());
        entity.setProdClass(eo.getProdClass() == null ? null : eo.getProdClass().getValue());
        entity.setSpecialProdClass(eo.getSpecialProdClass() == null ? null : eo.getSpecialProdClass().getValue());
        entity.setStageCode(eo.getStageCode());
        entity.setAnnualFlag(eo.getAnnualFlag() == null ? null : eo.getAnnualFlag().getValue());
        entity.setAnnualStatus(eo.getAnnualStatus() == null ? null : eo.getAnnualStatus().getValue());
        entity.setLastResetDate(eo.getLastResetDate());
        entity.setLastStopDate(eo.getLastStopDate());
        entity.setBlacklistStatus(eo.getBlacklistStatus() == null ? null : eo.getBlacklistStatus().getValue());
        entity.setLastBlacklistDate(eo.getLastBlacklistDate());
        entity.setFreeSum(eo.getFreeSum());
        entity.setMsgStatus(eo.getMsgStatus() == null ? null : eo.getMsgStatus().getValue());
        entity.setClientNo(eo.getClientNo());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setAutoRenewTerm(eo.getAutoRenewTerm());
        entity.setAutoRenewTermType(eo.getAutoRenewTermType() == null ? null : eo.getAutoRenewTermType().getValue());
        entity.setTotalDrawAmt(eo.getTotalDrawAmt());
        entity.setAllDraIntBranch(eo.getAllDraIntBranch() == null ? null : eo.getAllDraIntBranch().getValue());
        entity.setAllowSuspendFlag(eo.getAllowSuspendFlag() == null ? null : eo.getAllowSuspendFlag().getValue());
        entity.setDepositNature(eo.getDepositNature() == null ? null : eo.getDepositNature().getValue());
        entity.setIsSellCheque(eo.getIsSellCheque() == null ? null : eo.getIsSellCheque().getValue());
        entity.setCaseInvolvedFlag(eo.getCaseInvolvedFlag() == null ? null : eo.getCaseInvolvedFlag().getValue());
        entity.setPreDebtDate(eo.getPreDebtDate());
        entity.setApprovalNo(eo.getApprovalNo());
        entity.setAgreementId(eo.getAgreementId());
        entity.setAcctOpenMode(eo.getAcctOpenMode() == null ? null : eo.getAcctOpenMode().getValue());
        entity.setAgreementDepositType(eo.getAgreementDepositType() == null ? null : eo.getAgreementDepositType().getValue());
        entity.setNextDepDay(eo.getNextDepDay());
        entity.setReOpenDate(eo.getReOpenDate());
        entity.setAcctOpenType(eo.getAcctOpenType() == null ? null : eo.getAcctOpenType().getValue());
        entity.setTaxRate(eo.getTaxRate());
        entity.setManageFlag(eo.getManageFlag() == null ? null : eo.getManageFlag().getValue());
        entity.setIntTaxLevy(eo.getIntTaxLevy() == null ? null : eo.getIntTaxLevy().getValue());
        entity.setAcctRiskLevel(eo.getAcctRiskLevel() == null ? null : eo.getAcctRiskLevel().getValue());
        entity.setFarmerFlag(eo.getFarmerFlag() == null ? null : eo.getFarmerFlag().getValue());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setCheckCertificateAmt(eo.getCheckCertificateAmt());
        entity.setManageContent(eo.getManageContent());
        entity.setTaxDiscountMaturityDate(eo.getTaxDiscountMaturityDate());
        entity.setAmountNature(eo.getAmountNature() == null ? null : eo.getAmountNature().getValue());
        entity.setManageType(eo.getManageType() == null ? null : eo.getManageType().getValue());
        entity.setAcctChannelFlag(eo.getAcctChannelFlag());
        entity.setAcctProperty2(eo.getAcctProperty2() == null ? null : eo.getAcctProperty2().getValue());
        entity.setCheckCertificateType(eo.getCheckCertificateType() == null ? null : eo.getCheckCertificateType().getValue());
        entity.setDelayPayInt(eo.getDelayPayInt() == null ? null : eo.getDelayPayInt().getValue());
        entity.setFastOpenAcctFlag(eo.getFastOpenAcctFlag() == null ? null : eo.getFastOpenAcctFlag().getValue());
        entity.setFirstDrawDate(eo.getFirstDrawDate());
        entity.setOnlineFlag(eo.getOnlineFlag());
        entity.setSpecDay(eo.getSpecDay());
        entity.setTreatment(eo.getTreatment() == null ? null : eo.getTreatment().getValue());
        entity.setBackToDate(eo.getBackToDate());
        entity.setBothLimitFlag(eo.getBothLimitFlag() == null ? null : eo.getBothLimitFlag().getValue());
        entity.setCaseInvolvedDate(eo.getCaseInvolvedDate());
        entity.setCaseInvolvedReason(eo.getCaseInvolvedReason());
        entity.setPrivateAcctFlag(eo.getPrivateAcctFlag() == null ? null : eo.getPrivateAcctFlag().getValue());
        entity.setAnnualDate(eo.getAnnualDate());
        entity.setSecretAcct(eo.getSecretAcct() == null ? null : eo.getSecretAcct().getValue());
        entity.setPromoterName(eo.getPromoterName());
        entity.setPromoterCode(eo.getPromoterCode());
        entity.setAcctExecName(eo.getAcctExecName());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setAcctExecCode(eo.getAcctExecCode());
        entity.setLineOwnerShip(eo.getLineOwnerShip());
        entity.setIsAllowClose(eo.getIsAllowClose() == null ? null : eo.getIsAllowClose().getValue());
        entity.setStageLimitClass(eo.getStageLimitClass() == null ? null : eo.getStageLimitClass().getValue());
        entity.setTermLack(eo.getTermLack());
        entity.setAddTotalTerm(eo.getAddTotalTerm());
        entity.setSimpleAcct(eo.getSimpleAcct() == null ? null : eo.getSimpleAcct().getValue());
        entity.setLoanFundFlag(eo.getLoanFundFlag() == null ? null : eo.getLoanFundFlag().getValue());
        entity.setCollatInd(eo.getCollatInd() == null ? null : eo.getCollatInd().getValue());
        entity.setAcctVerifyFlag(eo.getAcctVerifyFlag() == null ? null : eo.getAcctVerifyFlag().getValue());
        entity.setAcctVerifyResult(eo.getAcctVerifyResult() == null ? null : eo.getAcctVerifyResult().getValue());
        entity.setAcctProofFlag(eo.getAcctProofFlag());
        entity.setAcctTellerSignFlag(eo.getAcctTellerSignFlag() == null ? null : eo.getAcctTellerSignFlag().getValue());
        return entity;
    }

    public static RbAcctAttachExample eoToEntityExample(RbAcctAttachEO eo) {
        if (eo == null) {
            return null;
        }
        RbAcctAttachExample example = new RbAcctAttachExample();
        RbAcctAttachExample.Criteria criteria = example.createCriteria();
        if (eo.getCounterCroBrchDebtFlag() != null) criteria.andCounterCroBrchDebtFlagEqualTo(eo.getCounterCroBrchDebtFlag().getValue());
        if (eo.getCounterCroBrchCretFlag() != null) criteria.andCounterCroBrchCretFlagEqualTo(eo.getCounterCroBrchCretFlag().getValue());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getGlCode() != null) criteria.andGlCodeEqualTo(eo.getGlCode());
        if (eo.getAcctProofReason() != null) criteria.andAcctProofReasonEqualTo(eo.getAcctProofReason());
        if (eo.getAcctProperty() != null) criteria.andAcctPropertyEqualTo(eo.getAcctProperty().getValue());
        if (eo.getBalChgInd() != null) criteria.andBalChgIndEqualTo(eo.getBalChgInd().getValue());
        if (eo.getBalUpdType() != null) criteria.andBalUpdTypeEqualTo(eo.getBalUpdType().getValue());
        if (eo.getBalanceWay() != null) criteria.andBalanceWayEqualTo(eo.getBalanceWay().getValue());
        if (eo.getOdFacility() != null) criteria.andOdFacilityEqualTo(eo.getOdFacility().getValue());
        if (eo.getCycleIntFlag() != null) criteria.andCycleIntFlagEqualTo(eo.getCycleIntFlag().getValue());
        if (eo.getAutoSettleFlag() != null) criteria.andAutoSettleFlagEqualTo(eo.getAutoSettleFlag().getValue());
        if (eo.getAutoDep() != null) criteria.andAutoDepEqualTo(eo.getAutoDep().getValue());
        if (eo.getManualAccountFlag() != null) criteria.andManualAccountFlagEqualTo(eo.getManualAccountFlag().getValue());
        if (eo.getFtaAcctFlag() != null) criteria.andFtaAcctFlagEqualTo(eo.getFtaAcctFlag().getValue());
        if (eo.getFtaCode() != null) criteria.andFtaCodeEqualTo(eo.getFtaCode());
        if (eo.getHangWriteOffFlag() != null) criteria.andHangWriteOffFlagEqualTo(eo.getHangWriteOffFlag().getValue());
        if (eo.getHangTerm() != null) criteria.andHangTermEqualTo(eo.getHangTerm());
        if (eo.getUnBindDepFlag() != null) criteria.andUnBindDepFlagEqualTo(eo.getUnBindDepFlag().getValue());
        if (eo.getProdClass() != null) criteria.andProdClassEqualTo(eo.getProdClass().getValue());
        if (eo.getSpecialProdClass() != null) criteria.andSpecialProdClassEqualTo(eo.getSpecialProdClass().getValue());
        if (eo.getStageCode() != null) criteria.andStageCodeEqualTo(eo.getStageCode());
        if (eo.getAnnualFlag() != null) criteria.andAnnualFlagEqualTo(eo.getAnnualFlag().getValue());
        if (eo.getAnnualStatus() != null) criteria.andAnnualStatusEqualTo(eo.getAnnualStatus().getValue());
        if (eo.getLastResetDate() != null) criteria.andLastResetDateEqualTo(eo.getLastResetDate());
        if (eo.getLastStopDate() != null) criteria.andLastStopDateEqualTo(eo.getLastStopDate());
        if (eo.getBlacklistStatus() != null) criteria.andBlacklistStatusEqualTo(eo.getBlacklistStatus().getValue());
        if (eo.getLastBlacklistDate() != null) criteria.andLastBlacklistDateEqualTo(eo.getLastBlacklistDate());
        if (eo.getFreeSum() != null) criteria.andFreeSumEqualTo(eo.getFreeSum());
        if (eo.getMsgStatus() != null) criteria.andMsgStatusEqualTo(eo.getMsgStatus().getValue());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getAutoRenewTerm() != null) criteria.andAutoRenewTermEqualTo(eo.getAutoRenewTerm());
        if (eo.getAutoRenewTermType() != null) criteria.andAutoRenewTermTypeEqualTo(eo.getAutoRenewTermType().getValue());
        if (eo.getTotalDrawAmt() != null) criteria.andTotalDrawAmtEqualTo(eo.getTotalDrawAmt());
        if (eo.getAllDraIntBranch() != null) criteria.andAllDraIntBranchEqualTo(eo.getAllDraIntBranch().getValue());
        if (eo.getAllowSuspendFlag() != null) criteria.andAllowSuspendFlagEqualTo(eo.getAllowSuspendFlag().getValue());
        if (eo.getDepositNature() != null) criteria.andDepositNatureEqualTo(eo.getDepositNature().getValue());
        if (eo.getIsSellCheque() != null) criteria.andIsSellChequeEqualTo(eo.getIsSellCheque().getValue());
        if (eo.getCaseInvolvedFlag() != null) criteria.andCaseInvolvedFlagEqualTo(eo.getCaseInvolvedFlag().getValue());
        if (eo.getPreDebtDate() != null) criteria.andPreDebtDateEqualTo(eo.getPreDebtDate());
        if (eo.getApprovalNo() != null) criteria.andApprovalNoEqualTo(eo.getApprovalNo());
        if (eo.getAgreementId() != null) criteria.andAgreementIdEqualTo(eo.getAgreementId());
        if (eo.getAcctOpenMode() != null) criteria.andAcctOpenModeEqualTo(eo.getAcctOpenMode().getValue());
        if (eo.getAgreementDepositType() != null) criteria.andAgreementDepositTypeEqualTo(eo.getAgreementDepositType().getValue());
        if (eo.getNextDepDay() != null) criteria.andNextDepDayEqualTo(eo.getNextDepDay());
        if (eo.getReOpenDate() != null) criteria.andReOpenDateEqualTo(eo.getReOpenDate());
        if (eo.getAcctOpenType() != null) criteria.andAcctOpenTypeEqualTo(eo.getAcctOpenType().getValue());
        if (eo.getTaxRate() != null) criteria.andTaxRateEqualTo(eo.getTaxRate());
        if (eo.getManageFlag() != null) criteria.andManageFlagEqualTo(eo.getManageFlag().getValue());
        if (eo.getIntTaxLevy() != null) criteria.andIntTaxLevyEqualTo(eo.getIntTaxLevy().getValue());
        if (eo.getAcctRiskLevel() != null) criteria.andAcctRiskLevelEqualTo(eo.getAcctRiskLevel().getValue());
        if (eo.getFarmerFlag() != null) criteria.andFarmerFlagEqualTo(eo.getFarmerFlag().getValue());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getCheckCertificateAmt() != null) criteria.andCheckCertificateAmtEqualTo(eo.getCheckCertificateAmt());
        if (eo.getManageContent() != null) criteria.andManageContentEqualTo(eo.getManageContent());
        if (eo.getTaxDiscountMaturityDate() != null) criteria.andTaxDiscountMaturityDateEqualTo(eo.getTaxDiscountMaturityDate());
        if (eo.getAmountNature() != null) criteria.andAmountNatureEqualTo(eo.getAmountNature().getValue());
        if (eo.getManageType() != null) criteria.andManageTypeEqualTo(eo.getManageType().getValue());
        if (eo.getAcctChannelFlag() != null) criteria.andAcctChannelFlagEqualTo(eo.getAcctChannelFlag());
        if (eo.getAcctProperty2() != null) criteria.andAcctProperty2EqualTo(eo.getAcctProperty2().getValue());
        if (eo.getCheckCertificateType() != null) criteria.andCheckCertificateTypeEqualTo(eo.getCheckCertificateType().getValue());
        if (eo.getDelayPayInt() != null) criteria.andDelayPayIntEqualTo(eo.getDelayPayInt().getValue());
        if (eo.getFastOpenAcctFlag() != null) criteria.andFastOpenAcctFlagEqualTo(eo.getFastOpenAcctFlag().getValue());
        if (eo.getFirstDrawDate() != null) criteria.andFirstDrawDateEqualTo(eo.getFirstDrawDate());
        if (eo.getOnlineFlag() != null) criteria.andOnlineFlagEqualTo(eo.getOnlineFlag());
        if (eo.getSpecDay() != null) criteria.andSpecDayEqualTo(eo.getSpecDay());
        if (eo.getTreatment() != null) criteria.andTreatmentEqualTo(eo.getTreatment().getValue());
        if (eo.getBackToDate() != null) criteria.andBackToDateEqualTo(eo.getBackToDate());
        if (eo.getBothLimitFlag() != null) criteria.andBothLimitFlagEqualTo(eo.getBothLimitFlag().getValue());
        if (eo.getCaseInvolvedDate() != null) criteria.andCaseInvolvedDateEqualTo(eo.getCaseInvolvedDate());
        if (eo.getCaseInvolvedReason() != null) criteria.andCaseInvolvedReasonEqualTo(eo.getCaseInvolvedReason());
        if (eo.getPrivateAcctFlag() != null) criteria.andPrivateAcctFlagEqualTo(eo.getPrivateAcctFlag().getValue());
        if (eo.getAnnualDate() != null) criteria.andAnnualDateEqualTo(eo.getAnnualDate());
        if (eo.getSecretAcct() != null) criteria.andSecretAcctEqualTo(eo.getSecretAcct().getValue());
        if (eo.getPromoterName() != null) criteria.andPromoterNameEqualTo(eo.getPromoterName());
        if (eo.getPromoterCode() != null) criteria.andPromoterCodeEqualTo(eo.getPromoterCode());
        if (eo.getAcctExecName() != null) criteria.andAcctExecNameEqualTo(eo.getAcctExecName());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getAcctExecCode() != null) criteria.andAcctExecCodeEqualTo(eo.getAcctExecCode());
        if (eo.getLineOwnerShip() != null) criteria.andLineOwnerShipEqualTo(eo.getLineOwnerShip());
        if (eo.getIsAllowClose() != null) criteria.andIsAllowCloseEqualTo(eo.getIsAllowClose().getValue());
        if (eo.getStageLimitClass() != null) criteria.andStageLimitClassEqualTo(eo.getStageLimitClass().getValue());
        if (eo.getTermLack() != null) criteria.andTermLackEqualTo(eo.getTermLack());
        if (eo.getAddTotalTerm() != null) criteria.andAddTotalTermEqualTo(eo.getAddTotalTerm());
        if (eo.getSimpleAcct() != null) criteria.andSimpleAcctEqualTo(eo.getSimpleAcct().getValue());
        if (eo.getLoanFundFlag() != null) criteria.andLoanFundFlagEqualTo(eo.getLoanFundFlag().getValue());
        if (eo.getCollatInd() != null) criteria.andCollatIndEqualTo(eo.getCollatInd().getValue());
        if (eo.getAcctVerifyFlag() != null) criteria.andAcctVerifyFlagEqualTo(eo.getAcctVerifyFlag().getValue());
        if (eo.getAcctVerifyResult() != null) criteria.andAcctVerifyResultEqualTo(eo.getAcctVerifyResult().getValue());
        if (eo.getAcctProofFlag() != null) criteria.andAcctProofFlagEqualTo(eo.getAcctProofFlag());
        if (eo.getAcctTellerSignFlag() != null) criteria.andAcctTellerSignFlagEqualTo(eo.getAcctTellerSignFlag().getValue());
        return example;
    }
}