package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbAcctIntDetailPre;
import com.dcits.deposit.entity.RbAcctIntDetailPreExample;
import com.dcits.deposit.facade.eo.RbAcctIntDetailPreEO;
import com.dcits.deposit.enums.IntClass;
import com.dcits.deposit.enums.CycleFreq;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.CycleFreq;
import com.dcits.deposit.enums.IntType;
import com.dcits.deposit.enums.RateEffectType;
import com.dcits.deposit.enums.FloatType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.MonthBasis;
import com.dcits.deposit.enums.YearBasis;
import com.dcits.deposit.enums.PenaltyOdiRateType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IntCalcBal;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IntApplType;
import com.dcits.deposit.enums.IntApplType;
import com.dcits.deposit.enums.CycleFreq;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.TaxType;
import com.dcits.deposit.enums.FollowIntDayType;
import com.dcits.deposit.enums.AgreeChangeType;
import com.dcits.deposit.enums.IntType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.Company;
import com.dcits.deposit.enums.IndividualFlag;

public final class RbAcctIntDetailPreValueUtil {
    private RbAcctIntDetailPreValueUtil() {
    }

    public static RbAcctIntDetailPreEO entityToEo(RbAcctIntDetailPre entity) {
        if (entity == null) {
            return null;
        }
        RbAcctIntDetailPreEO eo = new RbAcctIntDetailPreEO();
        eo.setInternalKey(entity.getInternalKey());
        eo.setIntClass(IntClass.byValue(entity.getIntClass()));
        eo.setAccrPeriodFreq(CycleFreq.byValue(entity.getAccrPeriodFreq()));
        eo.setNextAccrDate(entity.getNextAccrDate());
        eo.setLastAccrualDate(entity.getLastAccrualDate());
        eo.setCycleFlag(IndividualFlag.byValue(entity.getCycleFlag()));
        eo.setIntCapFlag(IndividualFlag.byValue(entity.getIntCapFlag()));
        eo.setNextCycleDate(entity.getNextCycleDate());
        eo.setLastCycleDate(entity.getLastCycleDate());
        eo.setLastTrueCycleDate(entity.getLastTrueCycleDate());
        eo.setLastCycleDatePre(entity.getLastCycleDatePre());
        eo.setCycleFreq(CycleFreq.byValue(entity.getCycleFreq()));
        eo.setAccrIntDay(entity.getAccrIntDay());
        eo.setIntDay(entity.getIntDay());
        eo.setIntType(IntType.byValue(entity.getIntType()));
        eo.setRateEffectType(RateEffectType.byValue(entity.getRateEffectType()));
        eo.setActualRate(entity.getActualRate());
        eo.setFloatRate(entity.getFloatRate());
        eo.setFloatType(FloatType.byValue(entity.getFloatType()));
        eo.setSpreadPercent(entity.getSpreadPercent());
        eo.setSpreadRate(entity.getSpreadRate());
        eo.setAcctFixedRate(entity.getAcctFixedRate());
        eo.setAcctSpreadRate(entity.getAcctSpreadRate());
        eo.setRealRate(entity.getRealRate());
        eo.setSplitRateFlag(IndividualFlag.byValue(entity.getSplitRateFlag()));
        eo.setMinIntRate(entity.getMinIntRate());
        eo.setMaxIntRate(entity.getMaxIntRate());
        eo.setMonthBasis(MonthBasis.byValue(entity.getMonthBasis()));
        eo.setYearBasis(YearBasis.byValue(entity.getYearBasis()));
        eo.setPenaltyOdiRateType(PenaltyOdiRateType.byValue(entity.getPenaltyOdiRateType()));
        eo.setRateChangeInd(IndividualFlag.byValue(entity.getRateChangeInd()));
        eo.setIntAccrued(entity.getIntAccrued());
        eo.setAgg(entity.getAgg());
        eo.setIntAccruedCalcCtd(entity.getIntAccruedCalcCtd());
        eo.setIntAccruedCtd(entity.getIntAccruedCtd());
        eo.setIntAccruedDiff(entity.getIntAccruedDiff());
        eo.setIntAccruedPrev(entity.getIntAccruedPrev());
        eo.setIntAccruedLastPrev(entity.getIntAccruedLastPrev());
        eo.setIntAccruedT(entity.getIntAccruedT());
        eo.setIntAdj(entity.getIntAdj());
        eo.setIntAdjCtd(entity.getIntAdjCtd());
        eo.setIntAdjPrev(entity.getIntAdjPrev());
        eo.setIntAdjLastPrev(entity.getIntAdjLastPrev());
        eo.setIntCalcBal(IntCalcBal.byValue(entity.getIntCalcBal()));
        eo.setIntPastDue(entity.getIntPastDue());
        eo.setIntPosted(entity.getIntPosted());
        eo.setIntPostedCtd(entity.getIntPostedCtd());
        eo.setIntRemDays(entity.getIntRemDays());
        eo.setDiscntInt(entity.getDiscntInt());
        eo.setDiscntIntPrev(entity.getDiscntIntPrev());
        eo.setDiscntIntLastPrev(entity.getDiscntIntLastPrev());
        eo.setDiscntRetainInt(entity.getDiscntRetainInt());
        eo.setDiscntUiFlag(IndividualFlag.byValue(entity.getDiscntUiFlag()));
        eo.setUiPenaltyAmt(entity.getUiPenaltyAmt());
        eo.setUiInt(entity.getUiInt());
        eo.setCalcBalance(entity.getCalcBalance());
        eo.setCalcEndDate(entity.getCalcEndDate());
        eo.setIntApplType(IntApplType.byValue(entity.getIntApplType()));
        eo.setIntApplTypePrev(IntApplType.byValue(entity.getIntApplTypePrev()));
        eo.setRollDay(entity.getRollDay());
        eo.setRollFreq(CycleFreq.byValue(entity.getRollFreq()));
        eo.setCalcByInt(IndividualFlag.byValue(entity.getCalcByInt()));
        eo.setLastRollDate(entity.getLastRollDate());
        eo.setNextRollDate(entity.getNextRollDate());
        eo.setTdAccrIntDay(entity.getTdAccrIntDay());
        eo.setTdIntNumDays(entity.getTdIntNumDays());
        eo.setTdLastAccrDate(entity.getTdLastAccrDate());
        eo.setAgreeReduceAmt(entity.getAgreeReduceAmt());
        eo.setIntAmt(entity.getIntAmt());
        eo.setIntCapAmt(entity.getIntCapAmt());
        eo.setSettleCycleDate(entity.getSettleCycleDate());
        eo.setAgreeFixedRate(entity.getAgreeFixedRate());
        eo.setAgreeSpreadRate(entity.getAgreeSpreadRate());
        eo.setAgreeInt(entity.getAgreeInt());
        eo.setLastIntPastDue(entity.getLastIntPastDue());
        eo.setTaxType(TaxType.byValue(entity.getTaxType()));
        eo.setTaxRate(entity.getTaxRate());
        eo.setAcctFixedTaxRate(entity.getAcctFixedTaxRate());
        eo.setAcctPercentTaxRate(entity.getAcctPercentTaxRate());
        eo.setAcctSpreadTaxRate(entity.getAcctSpreadTaxRate());
        eo.setTaxAccrued(entity.getTaxAccrued());
        eo.setTaxAccruedCalcCtd(entity.getTaxAccruedCalcCtd());
        eo.setTaxAccruedCtd(entity.getTaxAccruedCtd());
        eo.setTaxAccruedDiff(entity.getTaxAccruedDiff());
        eo.setTaxPostedCtd(entity.getTaxPostedCtd());
        eo.setTaxPosted(entity.getTaxPosted());
        eo.setIntTaxT(entity.getIntTaxT());
        eo.setFollowIntDayType(FollowIntDayType.byValue(entity.getFollowIntDayType()));
        eo.setRetryFlag(entity.getRetryFlag());
        eo.setAgreeChangeType(AgreeChangeType.byValue(entity.getAgreeChangeType()));
        eo.setAgreeAgg(entity.getAgreeAgg());
        eo.setAgreePercentRate(entity.getAgreePercentRate());
        eo.setLayerAgreement(IntType.byValue(entity.getLayerAgreement()));
        eo.setFollowTraceNaturalDays(entity.getFollowTraceNaturalDays());
        eo.setFollowTraceWorkdayDays(entity.getFollowTraceWorkdayDays());
        eo.setIntFlag(IndividualFlag.byValue(entity.getIntFlag()));
        eo.setDacValue(entity.getDacValue());
        eo.setSystemId(entity.getSystemId());
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setLastChangeUserId(entity.getLastChangeUserId());
        eo.setClientNo(entity.getClientNo());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setAdjUpdLastDate(entity.getAdjUpdLastDate());
        eo.setAdvUpdLastDate(entity.getAdvUpdLastDate());
        eo.setPastFadRate(entity.getPastFadRate());
        eo.setTotalAgg(entity.getTotalAgg());
        eo.setDelayTotalAmt(entity.getDelayTotalAmt());
        eo.setDelayIntAmt(entity.getDelayIntAmt());
        eo.setDelayIntAmtPrev(entity.getDelayIntAmtPrev());
        eo.setDelayIntAmtLastPrev(entity.getDelayIntAmtLastPrev());
        eo.setSuccessFlag(IndividualFlag.byValue(entity.getSuccessFlag()));
        eo.setCalcBeginDate(entity.getCalcBeginDate());
        return eo;
    }

    public static RbAcctIntDetailPre eoToEntity(RbAcctIntDetailPreEO eo) {
        if (eo == null) {
            return null;
        }
        RbAcctIntDetailPre entity = new RbAcctIntDetailPre();
        entity.setInternalKey(eo.getInternalKey());
        entity.setIntClass(eo.getIntClass() == null ? null : eo.getIntClass().getValue());
        entity.setAccrPeriodFreq(eo.getAccrPeriodFreq() == null ? null : eo.getAccrPeriodFreq().getValue());
        entity.setNextAccrDate(eo.getNextAccrDate());
        entity.setLastAccrualDate(eo.getLastAccrualDate());
        entity.setCycleFlag(eo.getCycleFlag() == null ? null : eo.getCycleFlag().getValue());
        entity.setIntCapFlag(eo.getIntCapFlag() == null ? null : eo.getIntCapFlag().getValue());
        entity.setNextCycleDate(eo.getNextCycleDate());
        entity.setLastCycleDate(eo.getLastCycleDate());
        entity.setLastTrueCycleDate(eo.getLastTrueCycleDate());
        entity.setLastCycleDatePre(eo.getLastCycleDatePre());
        entity.setCycleFreq(eo.getCycleFreq() == null ? null : eo.getCycleFreq().getValue());
        entity.setAccrIntDay(eo.getAccrIntDay());
        entity.setIntDay(eo.getIntDay());
        entity.setIntType(eo.getIntType() == null ? null : eo.getIntType().getValue());
        entity.setRateEffectType(eo.getRateEffectType() == null ? null : eo.getRateEffectType().getValue());
        entity.setActualRate(eo.getActualRate());
        entity.setFloatRate(eo.getFloatRate());
        entity.setFloatType(eo.getFloatType() == null ? null : eo.getFloatType().getValue());
        entity.setSpreadPercent(eo.getSpreadPercent());
        entity.setSpreadRate(eo.getSpreadRate());
        entity.setAcctFixedRate(eo.getAcctFixedRate());
        entity.setAcctSpreadRate(eo.getAcctSpreadRate());
        entity.setRealRate(eo.getRealRate());
        entity.setSplitRateFlag(eo.getSplitRateFlag() == null ? null : eo.getSplitRateFlag().getValue());
        entity.setMinIntRate(eo.getMinIntRate());
        entity.setMaxIntRate(eo.getMaxIntRate());
        entity.setMonthBasis(eo.getMonthBasis() == null ? null : eo.getMonthBasis().getValue());
        entity.setYearBasis(eo.getYearBasis() == null ? null : eo.getYearBasis().getValue());
        entity.setPenaltyOdiRateType(eo.getPenaltyOdiRateType() == null ? null : eo.getPenaltyOdiRateType().getValue());
        entity.setRateChangeInd(eo.getRateChangeInd() == null ? null : eo.getRateChangeInd().getValue());
        entity.setIntAccrued(eo.getIntAccrued());
        entity.setAgg(eo.getAgg());
        entity.setIntAccruedCalcCtd(eo.getIntAccruedCalcCtd());
        entity.setIntAccruedCtd(eo.getIntAccruedCtd());
        entity.setIntAccruedDiff(eo.getIntAccruedDiff());
        entity.setIntAccruedPrev(eo.getIntAccruedPrev());
        entity.setIntAccruedLastPrev(eo.getIntAccruedLastPrev());
        entity.setIntAccruedT(eo.getIntAccruedT());
        entity.setIntAdj(eo.getIntAdj());
        entity.setIntAdjCtd(eo.getIntAdjCtd());
        entity.setIntAdjPrev(eo.getIntAdjPrev());
        entity.setIntAdjLastPrev(eo.getIntAdjLastPrev());
        entity.setIntCalcBal(eo.getIntCalcBal() == null ? null : eo.getIntCalcBal().getValue());
        entity.setIntPastDue(eo.getIntPastDue());
        entity.setIntPosted(eo.getIntPosted());
        entity.setIntPostedCtd(eo.getIntPostedCtd());
        entity.setIntRemDays(eo.getIntRemDays());
        entity.setDiscntInt(eo.getDiscntInt());
        entity.setDiscntIntPrev(eo.getDiscntIntPrev());
        entity.setDiscntIntLastPrev(eo.getDiscntIntLastPrev());
        entity.setDiscntRetainInt(eo.getDiscntRetainInt());
        entity.setDiscntUiFlag(eo.getDiscntUiFlag() == null ? null : eo.getDiscntUiFlag().getValue());
        entity.setUiPenaltyAmt(eo.getUiPenaltyAmt());
        entity.setUiInt(eo.getUiInt());
        entity.setCalcBalance(eo.getCalcBalance());
        entity.setCalcEndDate(eo.getCalcEndDate());
        entity.setIntApplType(eo.getIntApplType() == null ? null : eo.getIntApplType().getValue());
        entity.setIntApplTypePrev(eo.getIntApplTypePrev() == null ? null : eo.getIntApplTypePrev().getValue());
        entity.setRollDay(eo.getRollDay());
        entity.setRollFreq(eo.getRollFreq() == null ? null : eo.getRollFreq().getValue());
        entity.setCalcByInt(eo.getCalcByInt() == null ? null : eo.getCalcByInt().getValue());
        entity.setLastRollDate(eo.getLastRollDate());
        entity.setNextRollDate(eo.getNextRollDate());
        entity.setTdAccrIntDay(eo.getTdAccrIntDay());
        entity.setTdIntNumDays(eo.getTdIntNumDays());
        entity.setTdLastAccrDate(eo.getTdLastAccrDate());
        entity.setAgreeReduceAmt(eo.getAgreeReduceAmt());
        entity.setIntAmt(eo.getIntAmt());
        entity.setIntCapAmt(eo.getIntCapAmt());
        entity.setSettleCycleDate(eo.getSettleCycleDate());
        entity.setAgreeFixedRate(eo.getAgreeFixedRate());
        entity.setAgreeSpreadRate(eo.getAgreeSpreadRate());
        entity.setAgreeInt(eo.getAgreeInt());
        entity.setLastIntPastDue(eo.getLastIntPastDue());
        entity.setTaxType(eo.getTaxType() == null ? null : eo.getTaxType().getValue());
        entity.setTaxRate(eo.getTaxRate());
        entity.setAcctFixedTaxRate(eo.getAcctFixedTaxRate());
        entity.setAcctPercentTaxRate(eo.getAcctPercentTaxRate());
        entity.setAcctSpreadTaxRate(eo.getAcctSpreadTaxRate());
        entity.setTaxAccrued(eo.getTaxAccrued());
        entity.setTaxAccruedCalcCtd(eo.getTaxAccruedCalcCtd());
        entity.setTaxAccruedCtd(eo.getTaxAccruedCtd());
        entity.setTaxAccruedDiff(eo.getTaxAccruedDiff());
        entity.setTaxPostedCtd(eo.getTaxPostedCtd());
        entity.setTaxPosted(eo.getTaxPosted());
        entity.setIntTaxT(eo.getIntTaxT());
        entity.setFollowIntDayType(eo.getFollowIntDayType() == null ? null : eo.getFollowIntDayType().getValue());
        entity.setRetryFlag(eo.getRetryFlag());
        entity.setAgreeChangeType(eo.getAgreeChangeType() == null ? null : eo.getAgreeChangeType().getValue());
        entity.setAgreeAgg(eo.getAgreeAgg());
        entity.setAgreePercentRate(eo.getAgreePercentRate());
        entity.setLayerAgreement(eo.getLayerAgreement() == null ? null : eo.getLayerAgreement().getValue());
        entity.setFollowTraceNaturalDays(eo.getFollowTraceNaturalDays());
        entity.setFollowTraceWorkdayDays(eo.getFollowTraceWorkdayDays());
        entity.setIntFlag(eo.getIntFlag() == null ? null : eo.getIntFlag().getValue());
        entity.setDacValue(eo.getDacValue());
        entity.setSystemId(eo.getSystemId());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setLastChangeUserId(eo.getLastChangeUserId());
        entity.setClientNo(eo.getClientNo());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setAdjUpdLastDate(eo.getAdjUpdLastDate());
        entity.setAdvUpdLastDate(eo.getAdvUpdLastDate());
        entity.setPastFadRate(eo.getPastFadRate());
        entity.setTotalAgg(eo.getTotalAgg());
        entity.setDelayTotalAmt(eo.getDelayTotalAmt());
        entity.setDelayIntAmt(eo.getDelayIntAmt());
        entity.setDelayIntAmtPrev(eo.getDelayIntAmtPrev());
        entity.setDelayIntAmtLastPrev(eo.getDelayIntAmtLastPrev());
        entity.setSuccessFlag(eo.getSuccessFlag() == null ? null : eo.getSuccessFlag().getValue());
        entity.setCalcBeginDate(eo.getCalcBeginDate());
        return entity;
    }

    public static RbAcctIntDetailPreExample eoToEntityExample(RbAcctIntDetailPreEO eo) {
        if (eo == null) {
            return null;
        }
        RbAcctIntDetailPreExample example = new RbAcctIntDetailPreExample();
        RbAcctIntDetailPreExample.Criteria criteria = example.createCriteria();
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getIntClass() != null) criteria.andIntClassEqualTo(eo.getIntClass().getValue());
        if (eo.getAccrPeriodFreq() != null) criteria.andAccrPeriodFreqEqualTo(eo.getAccrPeriodFreq().getValue());
        if (eo.getNextAccrDate() != null) criteria.andNextAccrDateEqualTo(eo.getNextAccrDate());
        if (eo.getLastAccrualDate() != null) criteria.andLastAccrualDateEqualTo(eo.getLastAccrualDate());
        if (eo.getCycleFlag() != null) criteria.andCycleFlagEqualTo(eo.getCycleFlag().getValue());
        if (eo.getIntCapFlag() != null) criteria.andIntCapFlagEqualTo(eo.getIntCapFlag().getValue());
        if (eo.getNextCycleDate() != null) criteria.andNextCycleDateEqualTo(eo.getNextCycleDate());
        if (eo.getLastCycleDate() != null) criteria.andLastCycleDateEqualTo(eo.getLastCycleDate());
        if (eo.getLastTrueCycleDate() != null) criteria.andLastTrueCycleDateEqualTo(eo.getLastTrueCycleDate());
        if (eo.getLastCycleDatePre() != null) criteria.andLastCycleDatePreEqualTo(eo.getLastCycleDatePre());
        if (eo.getCycleFreq() != null) criteria.andCycleFreqEqualTo(eo.getCycleFreq().getValue());
        if (eo.getAccrIntDay() != null) criteria.andAccrIntDayEqualTo(eo.getAccrIntDay());
        if (eo.getIntDay() != null) criteria.andIntDayEqualTo(eo.getIntDay());
        if (eo.getIntType() != null) criteria.andIntTypeEqualTo(eo.getIntType().getValue());
        if (eo.getRateEffectType() != null) criteria.andRateEffectTypeEqualTo(eo.getRateEffectType().getValue());
        if (eo.getActualRate() != null) criteria.andActualRateEqualTo(eo.getActualRate());
        if (eo.getFloatRate() != null) criteria.andFloatRateEqualTo(eo.getFloatRate());
        if (eo.getFloatType() != null) criteria.andFloatTypeEqualTo(eo.getFloatType().getValue());
        if (eo.getSpreadPercent() != null) criteria.andSpreadPercentEqualTo(eo.getSpreadPercent());
        if (eo.getSpreadRate() != null) criteria.andSpreadRateEqualTo(eo.getSpreadRate());
        if (eo.getAcctFixedRate() != null) criteria.andAcctFixedRateEqualTo(eo.getAcctFixedRate());
        if (eo.getAcctSpreadRate() != null) criteria.andAcctSpreadRateEqualTo(eo.getAcctSpreadRate());
        if (eo.getRealRate() != null) criteria.andRealRateEqualTo(eo.getRealRate());
        if (eo.getSplitRateFlag() != null) criteria.andSplitRateFlagEqualTo(eo.getSplitRateFlag().getValue());
        if (eo.getMinIntRate() != null) criteria.andMinIntRateEqualTo(eo.getMinIntRate());
        if (eo.getMaxIntRate() != null) criteria.andMaxIntRateEqualTo(eo.getMaxIntRate());
        if (eo.getMonthBasis() != null) criteria.andMonthBasisEqualTo(eo.getMonthBasis().getValue());
        if (eo.getYearBasis() != null) criteria.andYearBasisEqualTo(eo.getYearBasis().getValue());
        if (eo.getPenaltyOdiRateType() != null) criteria.andPenaltyOdiRateTypeEqualTo(eo.getPenaltyOdiRateType().getValue());
        if (eo.getRateChangeInd() != null) criteria.andRateChangeIndEqualTo(eo.getRateChangeInd().getValue());
        if (eo.getIntAccrued() != null) criteria.andIntAccruedEqualTo(eo.getIntAccrued());
        if (eo.getAgg() != null) criteria.andAggEqualTo(eo.getAgg());
        if (eo.getIntAccruedCalcCtd() != null) criteria.andIntAccruedCalcCtdEqualTo(eo.getIntAccruedCalcCtd());
        if (eo.getIntAccruedCtd() != null) criteria.andIntAccruedCtdEqualTo(eo.getIntAccruedCtd());
        if (eo.getIntAccruedDiff() != null) criteria.andIntAccruedDiffEqualTo(eo.getIntAccruedDiff());
        if (eo.getIntAccruedPrev() != null) criteria.andIntAccruedPrevEqualTo(eo.getIntAccruedPrev());
        if (eo.getIntAccruedLastPrev() != null) criteria.andIntAccruedLastPrevEqualTo(eo.getIntAccruedLastPrev());
        if (eo.getIntAccruedT() != null) criteria.andIntAccruedTEqualTo(eo.getIntAccruedT());
        if (eo.getIntAdj() != null) criteria.andIntAdjEqualTo(eo.getIntAdj());
        if (eo.getIntAdjCtd() != null) criteria.andIntAdjCtdEqualTo(eo.getIntAdjCtd());
        if (eo.getIntAdjPrev() != null) criteria.andIntAdjPrevEqualTo(eo.getIntAdjPrev());
        if (eo.getIntAdjLastPrev() != null) criteria.andIntAdjLastPrevEqualTo(eo.getIntAdjLastPrev());
        if (eo.getIntCalcBal() != null) criteria.andIntCalcBalEqualTo(eo.getIntCalcBal().getValue());
        if (eo.getIntPastDue() != null) criteria.andIntPastDueEqualTo(eo.getIntPastDue());
        if (eo.getIntPosted() != null) criteria.andIntPostedEqualTo(eo.getIntPosted());
        if (eo.getIntPostedCtd() != null) criteria.andIntPostedCtdEqualTo(eo.getIntPostedCtd());
        if (eo.getIntRemDays() != null) criteria.andIntRemDaysEqualTo(eo.getIntRemDays());
        if (eo.getDiscntInt() != null) criteria.andDiscntIntEqualTo(eo.getDiscntInt());
        if (eo.getDiscntIntPrev() != null) criteria.andDiscntIntPrevEqualTo(eo.getDiscntIntPrev());
        if (eo.getDiscntIntLastPrev() != null) criteria.andDiscntIntLastPrevEqualTo(eo.getDiscntIntLastPrev());
        if (eo.getDiscntRetainInt() != null) criteria.andDiscntRetainIntEqualTo(eo.getDiscntRetainInt());
        if (eo.getDiscntUiFlag() != null) criteria.andDiscntUiFlagEqualTo(eo.getDiscntUiFlag().getValue());
        if (eo.getUiPenaltyAmt() != null) criteria.andUiPenaltyAmtEqualTo(eo.getUiPenaltyAmt());
        if (eo.getUiInt() != null) criteria.andUiIntEqualTo(eo.getUiInt());
        if (eo.getCalcBalance() != null) criteria.andCalcBalanceEqualTo(eo.getCalcBalance());
        if (eo.getCalcEndDate() != null) criteria.andCalcEndDateEqualTo(eo.getCalcEndDate());
        if (eo.getIntApplType() != null) criteria.andIntApplTypeEqualTo(eo.getIntApplType().getValue());
        if (eo.getIntApplTypePrev() != null) criteria.andIntApplTypePrevEqualTo(eo.getIntApplTypePrev().getValue());
        if (eo.getRollDay() != null) criteria.andRollDayEqualTo(eo.getRollDay());
        if (eo.getRollFreq() != null) criteria.andRollFreqEqualTo(eo.getRollFreq().getValue());
        if (eo.getCalcByInt() != null) criteria.andCalcByIntEqualTo(eo.getCalcByInt().getValue());
        if (eo.getLastRollDate() != null) criteria.andLastRollDateEqualTo(eo.getLastRollDate());
        if (eo.getNextRollDate() != null) criteria.andNextRollDateEqualTo(eo.getNextRollDate());
        if (eo.getTdAccrIntDay() != null) criteria.andTdAccrIntDayEqualTo(eo.getTdAccrIntDay());
        if (eo.getTdIntNumDays() != null) criteria.andTdIntNumDaysEqualTo(eo.getTdIntNumDays());
        if (eo.getTdLastAccrDate() != null) criteria.andTdLastAccrDateEqualTo(eo.getTdLastAccrDate());
        if (eo.getAgreeReduceAmt() != null) criteria.andAgreeReduceAmtEqualTo(eo.getAgreeReduceAmt());
        if (eo.getIntAmt() != null) criteria.andIntAmtEqualTo(eo.getIntAmt());
        if (eo.getIntCapAmt() != null) criteria.andIntCapAmtEqualTo(eo.getIntCapAmt());
        if (eo.getSettleCycleDate() != null) criteria.andSettleCycleDateEqualTo(eo.getSettleCycleDate());
        if (eo.getAgreeFixedRate() != null) criteria.andAgreeFixedRateEqualTo(eo.getAgreeFixedRate());
        if (eo.getAgreeSpreadRate() != null) criteria.andAgreeSpreadRateEqualTo(eo.getAgreeSpreadRate());
        if (eo.getAgreeInt() != null) criteria.andAgreeIntEqualTo(eo.getAgreeInt());
        if (eo.getLastIntPastDue() != null) criteria.andLastIntPastDueEqualTo(eo.getLastIntPastDue());
        if (eo.getTaxType() != null) criteria.andTaxTypeEqualTo(eo.getTaxType().getValue());
        if (eo.getTaxRate() != null) criteria.andTaxRateEqualTo(eo.getTaxRate());
        if (eo.getAcctFixedTaxRate() != null) criteria.andAcctFixedTaxRateEqualTo(eo.getAcctFixedTaxRate());
        if (eo.getAcctPercentTaxRate() != null) criteria.andAcctPercentTaxRateEqualTo(eo.getAcctPercentTaxRate());
        if (eo.getAcctSpreadTaxRate() != null) criteria.andAcctSpreadTaxRateEqualTo(eo.getAcctSpreadTaxRate());
        if (eo.getTaxAccrued() != null) criteria.andTaxAccruedEqualTo(eo.getTaxAccrued());
        if (eo.getTaxAccruedCalcCtd() != null) criteria.andTaxAccruedCalcCtdEqualTo(eo.getTaxAccruedCalcCtd());
        if (eo.getTaxAccruedCtd() != null) criteria.andTaxAccruedCtdEqualTo(eo.getTaxAccruedCtd());
        if (eo.getTaxAccruedDiff() != null) criteria.andTaxAccruedDiffEqualTo(eo.getTaxAccruedDiff());
        if (eo.getTaxPostedCtd() != null) criteria.andTaxPostedCtdEqualTo(eo.getTaxPostedCtd());
        if (eo.getTaxPosted() != null) criteria.andTaxPostedEqualTo(eo.getTaxPosted());
        if (eo.getIntTaxT() != null) criteria.andIntTaxTEqualTo(eo.getIntTaxT());
        if (eo.getFollowIntDayType() != null) criteria.andFollowIntDayTypeEqualTo(eo.getFollowIntDayType().getValue());
        if (eo.getRetryFlag() != null) criteria.andRetryFlagEqualTo(eo.getRetryFlag());
        if (eo.getAgreeChangeType() != null) criteria.andAgreeChangeTypeEqualTo(eo.getAgreeChangeType().getValue());
        if (eo.getAgreeAgg() != null) criteria.andAgreeAggEqualTo(eo.getAgreeAgg());
        if (eo.getAgreePercentRate() != null) criteria.andAgreePercentRateEqualTo(eo.getAgreePercentRate());
        if (eo.getLayerAgreement() != null) criteria.andLayerAgreementEqualTo(eo.getLayerAgreement().getValue());
        if (eo.getFollowTraceNaturalDays() != null) criteria.andFollowTraceNaturalDaysEqualTo(eo.getFollowTraceNaturalDays());
        if (eo.getFollowTraceWorkdayDays() != null) criteria.andFollowTraceWorkdayDaysEqualTo(eo.getFollowTraceWorkdayDays());
        if (eo.getIntFlag() != null) criteria.andIntFlagEqualTo(eo.getIntFlag().getValue());
        if (eo.getDacValue() != null) criteria.andDacValueEqualTo(eo.getDacValue());
        if (eo.getSystemId() != null) criteria.andSystemIdEqualTo(eo.getSystemId());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getLastChangeUserId() != null) criteria.andLastChangeUserIdEqualTo(eo.getLastChangeUserId());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getAdjUpdLastDate() != null) criteria.andAdjUpdLastDateEqualTo(eo.getAdjUpdLastDate());
        if (eo.getAdvUpdLastDate() != null) criteria.andAdvUpdLastDateEqualTo(eo.getAdvUpdLastDate());
        if (eo.getPastFadRate() != null) criteria.andPastFadRateEqualTo(eo.getPastFadRate());
        if (eo.getTotalAgg() != null) criteria.andTotalAggEqualTo(eo.getTotalAgg());
        if (eo.getDelayTotalAmt() != null) criteria.andDelayTotalAmtEqualTo(eo.getDelayTotalAmt());
        if (eo.getDelayIntAmt() != null) criteria.andDelayIntAmtEqualTo(eo.getDelayIntAmt());
        if (eo.getDelayIntAmtPrev() != null) criteria.andDelayIntAmtPrevEqualTo(eo.getDelayIntAmtPrev());
        if (eo.getDelayIntAmtLastPrev() != null) criteria.andDelayIntAmtLastPrevEqualTo(eo.getDelayIntAmtLastPrev());
        if (eo.getSuccessFlag() != null) criteria.andSuccessFlagEqualTo(eo.getSuccessFlag().getValue());
        if (eo.getCalcBeginDate() != null) criteria.andCalcBeginDateEqualTo(eo.getCalcBeginDate());
        return example;
    }
}