package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbAgreementSweep;
import com.dcits.deposit.entity.RbAgreementSweepExample;
import com.dcits.deposit.facade.eo.RbAgreementSweepEO;
import com.dcits.deposit.enums.AgreementType;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.RenewType;
import com.dcits.deposit.enums.AutoRenewRollover;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.OthAcctSort;
import com.dcits.deposit.enums.ReasonCode;
import com.dcits.deposit.enums.TermType;
import com.dcits.deposit.enums.AgreementStatus;
import com.dcits.deposit.enums.Company;
import com.dcits.deposit.enums.RenewAcctType;
import com.dcits.deposit.enums.OpenNumType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctCcy;

public final class RbAgreementSweepValueUtil {
    private RbAgreementSweepValueUtil() {
    }

    public static RbAgreementSweepEO entityToEo(RbAgreementSweep entity) {
        if (entity == null) {
            return null;
        }
        RbAgreementSweepEO eo = new RbAgreementSweepEO();
        eo.setAgreementId(entity.getAgreementId());
        eo.setSeqNo(entity.getSeqNo());
        eo.setSchedNo(entity.getSchedNo());
        eo.setAgreementType(AgreementType.byValue(entity.getAgreementType()));
        eo.setInternalKey(entity.getInternalKey());
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setProdType(entity.getProdType());
        eo.setAcctCcy(AcctCcy.byValue(entity.getAcctCcy()));
        eo.setAcctSeqNo(entity.getAcctSeqNo());
        eo.setAcctName(entity.getAcctName());
        eo.setAcctFixedRate(entity.getAcctFixedRate());
        eo.setAcctPercentRate(entity.getAcctPercentRate());
        eo.setAcctSpreadRate(entity.getAcctSpreadRate());
        eo.setRenewMinAmt(entity.getRenewMinAmt());
        eo.setRenewType(RenewType.byValue(entity.getRenewType()));
        eo.setRenewMethod(AutoRenewRollover.byValue(entity.getRenewMethod()));
        eo.setRenewMultiple(entity.getRenewMultiple());
        eo.setTranAmt(entity.getTranAmt());
        eo.setOthInternalKey(entity.getOthInternalKey());
        eo.setOthBaseAcctNo(entity.getOthBaseAcctNo());
        eo.setOthProdType(entity.getOthProdType());
        eo.setOthAcctCcy(AcctCcy.byValue(entity.getOthAcctCcy()));
        eo.setOthAcctSeqNo(entity.getOthAcctSeqNo());
        eo.setOthBankCode(entity.getOthBankCode());
        eo.setOthAcctDesc(entity.getOthAcctDesc());
        eo.setOthAcctSort(OthAcctSort.byValue(entity.getOthAcctSort()));
        eo.setReasonCode(ReasonCode.byValue(entity.getReasonCode()));
        eo.setBalRatio(entity.getBalRatio());
        eo.setPriority(entity.getPriority());
        eo.setSignDate(entity.getSignDate());
        eo.setStartDate(entity.getStartDate());
        eo.setTerm(entity.getTerm());
        eo.setTermType(TermType.byValue(entity.getTermType()));
        eo.setEndDate(entity.getEndDate());
        eo.setAgreementStatus(AgreementStatus.byValue(entity.getAgreementStatus()));
        eo.setSumAmt(entity.getSumAmt());
        eo.setTranBaseAmt(entity.getTranBaseAmt());
        eo.setSumConCount(entity.getSumConCount());
        eo.setSumCount(entity.getSumCount());
        eo.setConTransferCount(entity.getConTransferCount());
        eo.setClientNo(entity.getClientNo());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setUserId(entity.getUserId());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setNarrative(entity.getNarrative());
        eo.setRenewAcctType(RenewAcctType.byValue(entity.getRenewAcctType()));
        eo.setOpenNumType(OpenNumType.byValue(entity.getOpenNumType()));
        eo.setAutoSettleFlag(IndividualFlag.byValue(entity.getAutoSettleFlag()));
        eo.setPriintBaseAcctNo(entity.getPriintBaseAcctNo());
        eo.setPriintAcctSeqNo(entity.getPriintAcctSeqNo());
        eo.setPriintProdType(entity.getPriintProdType());
        eo.setPriintCcy(AcctCcy.byValue(entity.getPriintCcy()));
        eo.setFinFixedAmt(entity.getFinFixedAmt());
        eo.setLowestAmt(entity.getLowestAmt());
        eo.setSettleBaseAcctNo(entity.getSettleBaseAcctNo());
        eo.setSettleProdType(entity.getSettleProdType());
        eo.setSettleAcctCcy(AcctCcy.byValue(entity.getSettleAcctCcy()));
        eo.setSettleAcctSeqNo(entity.getSettleAcctSeqNo());
        eo.setLimitAmtOutDay(entity.getLimitAmtOutDay());
        eo.setMonthLimit(entity.getMonthLimit());
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setOthClientNo(entity.getOthClientNo());
        return eo;
    }

    public static RbAgreementSweep eoToEntity(RbAgreementSweepEO eo) {
        if (eo == null) {
            return null;
        }
        RbAgreementSweep entity = new RbAgreementSweep();
        entity.setAgreementId(eo.getAgreementId());
        entity.setSeqNo(eo.getSeqNo());
        entity.setSchedNo(eo.getSchedNo());
        entity.setAgreementType(eo.getAgreementType() == null ? null : eo.getAgreementType().getValue());
        entity.setInternalKey(eo.getInternalKey());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setProdType(eo.getProdType());
        entity.setAcctCcy(eo.getAcctCcy() == null ? null : eo.getAcctCcy().getValue());
        entity.setAcctSeqNo(eo.getAcctSeqNo());
        entity.setAcctName(eo.getAcctName());
        entity.setAcctFixedRate(eo.getAcctFixedRate());
        entity.setAcctPercentRate(eo.getAcctPercentRate());
        entity.setAcctSpreadRate(eo.getAcctSpreadRate());
        entity.setRenewMinAmt(eo.getRenewMinAmt());
        entity.setRenewType(eo.getRenewType() == null ? null : eo.getRenewType().getValue());
        entity.setRenewMethod(eo.getRenewMethod() == null ? null : eo.getRenewMethod().getValue());
        entity.setRenewMultiple(eo.getRenewMultiple());
        entity.setTranAmt(eo.getTranAmt());
        entity.setOthInternalKey(eo.getOthInternalKey());
        entity.setOthBaseAcctNo(eo.getOthBaseAcctNo());
        entity.setOthProdType(eo.getOthProdType());
        entity.setOthAcctCcy(eo.getOthAcctCcy() == null ? null : eo.getOthAcctCcy().getValue());
        entity.setOthAcctSeqNo(eo.getOthAcctSeqNo());
        entity.setOthBankCode(eo.getOthBankCode());
        entity.setOthAcctDesc(eo.getOthAcctDesc());
        entity.setOthAcctSort(eo.getOthAcctSort() == null ? null : eo.getOthAcctSort().getValue());
        entity.setReasonCode(eo.getReasonCode() == null ? null : eo.getReasonCode().getValue());
        entity.setBalRatio(eo.getBalRatio());
        entity.setPriority(eo.getPriority());
        entity.setSignDate(eo.getSignDate());
        entity.setStartDate(eo.getStartDate());
        entity.setTerm(eo.getTerm());
        entity.setTermType(eo.getTermType() == null ? null : eo.getTermType().getValue());
        entity.setEndDate(eo.getEndDate());
        entity.setAgreementStatus(eo.getAgreementStatus() == null ? null : eo.getAgreementStatus().getValue());
        entity.setSumAmt(eo.getSumAmt());
        entity.setTranBaseAmt(eo.getTranBaseAmt());
        entity.setSumConCount(eo.getSumConCount());
        entity.setSumCount(eo.getSumCount());
        entity.setConTransferCount(eo.getConTransferCount());
        entity.setClientNo(eo.getClientNo());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setUserId(eo.getUserId());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setNarrative(eo.getNarrative());
        entity.setRenewAcctType(eo.getRenewAcctType() == null ? null : eo.getRenewAcctType().getValue());
        entity.setOpenNumType(eo.getOpenNumType() == null ? null : eo.getOpenNumType().getValue());
        entity.setAutoSettleFlag(eo.getAutoSettleFlag() == null ? null : eo.getAutoSettleFlag().getValue());
        entity.setPriintBaseAcctNo(eo.getPriintBaseAcctNo());
        entity.setPriintAcctSeqNo(eo.getPriintAcctSeqNo());
        entity.setPriintProdType(eo.getPriintProdType());
        entity.setPriintCcy(eo.getPriintCcy() == null ? null : eo.getPriintCcy().getValue());
        entity.setFinFixedAmt(eo.getFinFixedAmt());
        entity.setLowestAmt(eo.getLowestAmt());
        entity.setSettleBaseAcctNo(eo.getSettleBaseAcctNo());
        entity.setSettleProdType(eo.getSettleProdType());
        entity.setSettleAcctCcy(eo.getSettleAcctCcy() == null ? null : eo.getSettleAcctCcy().getValue());
        entity.setSettleAcctSeqNo(eo.getSettleAcctSeqNo());
        entity.setLimitAmtOutDay(eo.getLimitAmtOutDay());
        entity.setMonthLimit(eo.getMonthLimit());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setOthClientNo(eo.getOthClientNo());
        return entity;
    }

    public static RbAgreementSweepExample eoToEntityExample(RbAgreementSweepEO eo) {
        if (eo == null) {
            return null;
        }
        RbAgreementSweepExample example = new RbAgreementSweepExample();
        RbAgreementSweepExample.Criteria criteria = example.createCriteria();
        if (eo.getAgreementId() != null) criteria.andAgreementIdEqualTo(eo.getAgreementId());
        if (eo.getSeqNo() != null) criteria.andSeqNoEqualTo(eo.getSeqNo());
        if (eo.getSchedNo() != null) criteria.andSchedNoEqualTo(eo.getSchedNo());
        if (eo.getAgreementType() != null) criteria.andAgreementTypeEqualTo(eo.getAgreementType().getValue());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getProdType() != null) criteria.andProdTypeEqualTo(eo.getProdType());
        if (eo.getAcctCcy() != null) criteria.andAcctCcyEqualTo(eo.getAcctCcy().getValue());
        if (eo.getAcctSeqNo() != null) criteria.andAcctSeqNoEqualTo(eo.getAcctSeqNo());
        if (eo.getAcctName() != null) criteria.andAcctNameEqualTo(eo.getAcctName());
        if (eo.getAcctFixedRate() != null) criteria.andAcctFixedRateEqualTo(eo.getAcctFixedRate());
        if (eo.getAcctPercentRate() != null) criteria.andAcctPercentRateEqualTo(eo.getAcctPercentRate());
        if (eo.getAcctSpreadRate() != null) criteria.andAcctSpreadRateEqualTo(eo.getAcctSpreadRate());
        if (eo.getRenewMinAmt() != null) criteria.andRenewMinAmtEqualTo(eo.getRenewMinAmt());
        if (eo.getRenewType() != null) criteria.andRenewTypeEqualTo(eo.getRenewType().getValue());
        if (eo.getRenewMethod() != null) criteria.andRenewMethodEqualTo(eo.getRenewMethod().getValue());
        if (eo.getRenewMultiple() != null) criteria.andRenewMultipleEqualTo(eo.getRenewMultiple());
        if (eo.getTranAmt() != null) criteria.andTranAmtEqualTo(eo.getTranAmt());
        if (eo.getOthInternalKey() != null) criteria.andOthInternalKeyEqualTo(eo.getOthInternalKey());
        if (eo.getOthBaseAcctNo() != null) criteria.andOthBaseAcctNoEqualTo(eo.getOthBaseAcctNo());
        if (eo.getOthProdType() != null) criteria.andOthProdTypeEqualTo(eo.getOthProdType());
        if (eo.getOthAcctCcy() != null) criteria.andOthAcctCcyEqualTo(eo.getOthAcctCcy().getValue());
        if (eo.getOthAcctSeqNo() != null) criteria.andOthAcctSeqNoEqualTo(eo.getOthAcctSeqNo());
        if (eo.getOthBankCode() != null) criteria.andOthBankCodeEqualTo(eo.getOthBankCode());
        if (eo.getOthAcctDesc() != null) criteria.andOthAcctDescEqualTo(eo.getOthAcctDesc());
        if (eo.getOthAcctSort() != null) criteria.andOthAcctSortEqualTo(eo.getOthAcctSort().getValue());
        if (eo.getReasonCode() != null) criteria.andReasonCodeEqualTo(eo.getReasonCode().getValue());
        if (eo.getBalRatio() != null) criteria.andBalRatioEqualTo(eo.getBalRatio());
        if (eo.getPriority() != null) criteria.andPriorityEqualTo(eo.getPriority());
        if (eo.getSignDate() != null) criteria.andSignDateEqualTo(eo.getSignDate());
        if (eo.getStartDate() != null) criteria.andStartDateEqualTo(eo.getStartDate());
        if (eo.getTerm() != null) criteria.andTermEqualTo(eo.getTerm());
        if (eo.getTermType() != null) criteria.andTermTypeEqualTo(eo.getTermType().getValue());
        if (eo.getEndDate() != null) criteria.andEndDateEqualTo(eo.getEndDate());
        if (eo.getAgreementStatus() != null) criteria.andAgreementStatusEqualTo(eo.getAgreementStatus().getValue());
        if (eo.getSumAmt() != null) criteria.andSumAmtEqualTo(eo.getSumAmt());
        if (eo.getTranBaseAmt() != null) criteria.andTranBaseAmtEqualTo(eo.getTranBaseAmt());
        if (eo.getSumConCount() != null) criteria.andSumConCountEqualTo(eo.getSumConCount());
        if (eo.getSumCount() != null) criteria.andSumCountEqualTo(eo.getSumCount());
        if (eo.getConTransferCount() != null) criteria.andConTransferCountEqualTo(eo.getConTransferCount());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getNarrative() != null) criteria.andNarrativeEqualTo(eo.getNarrative());
        if (eo.getRenewAcctType() != null) criteria.andRenewAcctTypeEqualTo(eo.getRenewAcctType().getValue());
        if (eo.getOpenNumType() != null) criteria.andOpenNumTypeEqualTo(eo.getOpenNumType().getValue());
        if (eo.getAutoSettleFlag() != null) criteria.andAutoSettleFlagEqualTo(eo.getAutoSettleFlag().getValue());
        if (eo.getPriintBaseAcctNo() != null) criteria.andPriintBaseAcctNoEqualTo(eo.getPriintBaseAcctNo());
        if (eo.getPriintAcctSeqNo() != null) criteria.andPriintAcctSeqNoEqualTo(eo.getPriintAcctSeqNo());
        if (eo.getPriintProdType() != null) criteria.andPriintProdTypeEqualTo(eo.getPriintProdType());
        if (eo.getPriintCcy() != null) criteria.andPriintCcyEqualTo(eo.getPriintCcy().getValue());
        if (eo.getFinFixedAmt() != null) criteria.andFinFixedAmtEqualTo(eo.getFinFixedAmt());
        if (eo.getLowestAmt() != null) criteria.andLowestAmtEqualTo(eo.getLowestAmt());
        if (eo.getSettleBaseAcctNo() != null) criteria.andSettleBaseAcctNoEqualTo(eo.getSettleBaseAcctNo());
        if (eo.getSettleProdType() != null) criteria.andSettleProdTypeEqualTo(eo.getSettleProdType());
        if (eo.getSettleAcctCcy() != null) criteria.andSettleAcctCcyEqualTo(eo.getSettleAcctCcy().getValue());
        if (eo.getSettleAcctSeqNo() != null) criteria.andSettleAcctSeqNoEqualTo(eo.getSettleAcctSeqNo());
        if (eo.getLimitAmtOutDay() != null) criteria.andLimitAmtOutDayEqualTo(eo.getLimitAmtOutDay());
        if (eo.getMonthLimit() != null) criteria.andMonthLimitEqualTo(eo.getMonthLimit());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getOthClientNo() != null) criteria.andOthClientNoEqualTo(eo.getOthClientNo());
        return example;
    }
}