package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbBatchTranDetails;
import com.dcits.deposit.entity.RbBatchTranDetailsExample;
import com.dcits.deposit.facade.eo.RbBatchTranDetailsEO;
import com.dcits.deposit.enums.SourceType;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.ClientType;
import com.dcits.deposit.enums.DocType;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.SourceType;
import com.dcits.deposit.enums.TranType;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.TranType;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.BatchStatus;
import com.dcits.deposit.enums.Company;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.TranStatus;

public final class RbBatchTranDetailsValueUtil {
    private RbBatchTranDetailsValueUtil() {
    }

    public static RbBatchTranDetailsEO entityToEo(RbBatchTranDetails entity) {
        if (entity == null) {
            return null;
        }
        RbBatchTranDetailsEO eo = new RbBatchTranDetailsEO();
        eo.setBatchSeqNo(entity.getBatchSeqNo());
        eo.setBatchNo(entity.getBatchNo());
        eo.setSeqNo(entity.getSeqNo());
        eo.setJobRunId(entity.getJobRunId());
        eo.setChannelSeqNo(entity.getChannelSeqNo());
        eo.setReference(entity.getReference());
        eo.setSourceType(SourceType.byValue(entity.getSourceType()));
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setProdType(entity.getProdType());
        eo.setAcctCcy(AcctCcy.byValue(entity.getAcctCcy()));
        eo.setAcctSeqNo(entity.getAcctSeqNo());
        eo.setAcctBranch(AcctBranch.byValue(entity.getAcctBranch()));
        eo.setClientType(ClientType.byValue(entity.getClientType()));
        eo.setAcctDesc(entity.getAcctDesc());
        eo.setDocType(DocType.byValue(entity.getDocType()));
        eo.setPrefix(entity.getPrefix());
        eo.setVoucherNo(entity.getVoucherNo());
        eo.setSettlementDate(entity.getSettlementDate());
        eo.setTranDate(entity.getTranDate());
        eo.setTranBranch(AcctBranch.byValue(entity.getTranBranch()));
        eo.setChannel(SourceType.byValue(entity.getChannel()));
        eo.setTranType(TranType.byValue(entity.getTranType()));
        eo.setTranAmt(entity.getTranAmt());
        eo.setCcy(AcctCcy.byValue(entity.getCcy()));
        eo.setServCharge(IndividualFlag.byValue(entity.getServCharge()));
        eo.setTranDesc(entity.getTranDesc());
        eo.setTranNote(entity.getTranNote());
        eo.setGlCode(entity.getGlCode());
        eo.setFhSeqNo(entity.getFhSeqNo());
        eo.setNarrative(entity.getNarrative());
        eo.setOthTranType(TranType.byValue(entity.getOthTranType()));
        eo.setOthReference(entity.getOthReference());
        eo.setOthSeqNo(entity.getOthSeqNo());
        eo.setOthGlCode(entity.getOthGlCode());
        eo.setOthTranName(entity.getOthTranName());
        eo.setOthBranch(AcctBranch.byValue(entity.getOthBranch()));
        eo.setOthBaseAcctNo(entity.getOthBaseAcctNo());
        eo.setOthProdType(entity.getOthProdType());
        eo.setOthAcctCcy(AcctCcy.byValue(entity.getOthAcctCcy()));
        eo.setOthAcctSeqNo(entity.getOthAcctSeqNo());
        eo.setOthAcctDesc(entity.getOthAcctDesc());
        eo.setOthBankCode(entity.getOthBankCode());
        eo.setOthBankName(entity.getOthBankName());
        eo.setBatchStatus(BatchStatus.byValue(entity.getBatchStatus()));
        eo.setRemark1(entity.getRemark1());
        eo.setRemark2(entity.getRemark2());
        eo.setRemark3(entity.getRemark3());
        eo.setRemark4(entity.getRemark4());
        eo.setRemark5(entity.getRemark5());
        eo.setRetMsg(entity.getRetMsg());
        eo.setErrorCode(entity.getErrorCode());
        eo.setErrorDesc(entity.getErrorDesc());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setUserId(entity.getUserId());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setNarrativeCode(entity.getNarrativeCode());
        eo.setOthRealBankName(entity.getOthRealBankName());
        eo.setOthRealBankCode(entity.getOthRealBankCode());
        eo.setOthRealBaseAcctNo(entity.getOthRealBaseAcctNo());
        eo.setOthRealDocumentId(entity.getOthRealDocumentId());
        eo.setOthRealProdType(entity.getOthRealProdType());
        eo.setOthRealDocumentType(DocumentType.byValue(entity.getOthRealDocumentType()));
        eo.setOthRealTranAddr(entity.getOthRealTranAddr());
        eo.setOthRealTranName(entity.getOthRealTranName());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setTranStatus(TranStatus.byValue(entity.getTranStatus()));
        return eo;
    }

    public static RbBatchTranDetails eoToEntity(RbBatchTranDetailsEO eo) {
        if (eo == null) {
            return null;
        }
        RbBatchTranDetails entity = new RbBatchTranDetails();
        entity.setBatchSeqNo(eo.getBatchSeqNo());
        entity.setBatchNo(eo.getBatchNo());
        entity.setSeqNo(eo.getSeqNo());
        entity.setJobRunId(eo.getJobRunId());
        entity.setChannelSeqNo(eo.getChannelSeqNo());
        entity.setReference(eo.getReference());
        entity.setSourceType(eo.getSourceType() == null ? null : eo.getSourceType().getValue());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setProdType(eo.getProdType());
        entity.setAcctCcy(eo.getAcctCcy() == null ? null : eo.getAcctCcy().getValue());
        entity.setAcctSeqNo(eo.getAcctSeqNo());
        entity.setAcctBranch(eo.getAcctBranch() == null ? null : eo.getAcctBranch().getValue());
        entity.setClientType(eo.getClientType() == null ? null : eo.getClientType().getValue());
        entity.setAcctDesc(eo.getAcctDesc());
        entity.setDocType(eo.getDocType() == null ? null : eo.getDocType().getValue());
        entity.setPrefix(eo.getPrefix());
        entity.setVoucherNo(eo.getVoucherNo());
        entity.setSettlementDate(eo.getSettlementDate());
        entity.setTranDate(eo.getTranDate());
        entity.setTranBranch(eo.getTranBranch() == null ? null : eo.getTranBranch().getValue());
        entity.setChannel(eo.getChannel() == null ? null : eo.getChannel().getValue());
        entity.setTranType(eo.getTranType() == null ? null : eo.getTranType().getValue());
        entity.setTranAmt(eo.getTranAmt());
        entity.setCcy(eo.getCcy() == null ? null : eo.getCcy().getValue());
        entity.setServCharge(eo.getServCharge() == null ? null : eo.getServCharge().getValue());
        entity.setTranDesc(eo.getTranDesc());
        entity.setTranNote(eo.getTranNote());
        entity.setGlCode(eo.getGlCode());
        entity.setFhSeqNo(eo.getFhSeqNo());
        entity.setNarrative(eo.getNarrative());
        entity.setOthTranType(eo.getOthTranType() == null ? null : eo.getOthTranType().getValue());
        entity.setOthReference(eo.getOthReference());
        entity.setOthSeqNo(eo.getOthSeqNo());
        entity.setOthGlCode(eo.getOthGlCode());
        entity.setOthTranName(eo.getOthTranName());
        entity.setOthBranch(eo.getOthBranch() == null ? null : eo.getOthBranch().getValue());
        entity.setOthBaseAcctNo(eo.getOthBaseAcctNo());
        entity.setOthProdType(eo.getOthProdType());
        entity.setOthAcctCcy(eo.getOthAcctCcy() == null ? null : eo.getOthAcctCcy().getValue());
        entity.setOthAcctSeqNo(eo.getOthAcctSeqNo());
        entity.setOthAcctDesc(eo.getOthAcctDesc());
        entity.setOthBankCode(eo.getOthBankCode());
        entity.setOthBankName(eo.getOthBankName());
        entity.setBatchStatus(eo.getBatchStatus() == null ? null : eo.getBatchStatus().getValue());
        entity.setRemark1(eo.getRemark1());
        entity.setRemark2(eo.getRemark2());
        entity.setRemark3(eo.getRemark3());
        entity.setRemark4(eo.getRemark4());
        entity.setRemark5(eo.getRemark5());
        entity.setRetMsg(eo.getRetMsg());
        entity.setErrorCode(eo.getErrorCode());
        entity.setErrorDesc(eo.getErrorDesc());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setUserId(eo.getUserId());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setNarrativeCode(eo.getNarrativeCode());
        entity.setOthRealBankName(eo.getOthRealBankName());
        entity.setOthRealBankCode(eo.getOthRealBankCode());
        entity.setOthRealBaseAcctNo(eo.getOthRealBaseAcctNo());
        entity.setOthRealDocumentId(eo.getOthRealDocumentId());
        entity.setOthRealProdType(eo.getOthRealProdType());
        entity.setOthRealDocumentType(eo.getOthRealDocumentType() == null ? null : eo.getOthRealDocumentType().getValue());
        entity.setOthRealTranAddr(eo.getOthRealTranAddr());
        entity.setOthRealTranName(eo.getOthRealTranName());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setTranStatus(eo.getTranStatus() == null ? null : eo.getTranStatus().getValue());
        return entity;
    }

    public static RbBatchTranDetailsExample eoToEntityExample(RbBatchTranDetailsEO eo) {
        if (eo == null) {
            return null;
        }
        RbBatchTranDetailsExample example = new RbBatchTranDetailsExample();
        RbBatchTranDetailsExample.Criteria criteria = example.createCriteria();
        if (eo.getBatchSeqNo() != null) criteria.andBatchSeqNoEqualTo(eo.getBatchSeqNo());
        if (eo.getBatchNo() != null) criteria.andBatchNoEqualTo(eo.getBatchNo());
        if (eo.getSeqNo() != null) criteria.andSeqNoEqualTo(eo.getSeqNo());
        if (eo.getJobRunId() != null) criteria.andJobRunIdEqualTo(eo.getJobRunId());
        if (eo.getChannelSeqNo() != null) criteria.andChannelSeqNoEqualTo(eo.getChannelSeqNo());
        if (eo.getReference() != null) criteria.andReferenceEqualTo(eo.getReference());
        if (eo.getSourceType() != null) criteria.andSourceTypeEqualTo(eo.getSourceType().getValue());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getProdType() != null) criteria.andProdTypeEqualTo(eo.getProdType());
        if (eo.getAcctCcy() != null) criteria.andAcctCcyEqualTo(eo.getAcctCcy().getValue());
        if (eo.getAcctSeqNo() != null) criteria.andAcctSeqNoEqualTo(eo.getAcctSeqNo());
        if (eo.getAcctBranch() != null) criteria.andAcctBranchEqualTo(eo.getAcctBranch().getValue());
        if (eo.getClientType() != null) criteria.andClientTypeEqualTo(eo.getClientType().getValue());
        if (eo.getAcctDesc() != null) criteria.andAcctDescEqualTo(eo.getAcctDesc());
        if (eo.getDocType() != null) criteria.andDocTypeEqualTo(eo.getDocType().getValue());
        if (eo.getPrefix() != null) criteria.andPrefixEqualTo(eo.getPrefix());
        if (eo.getVoucherNo() != null) criteria.andVoucherNoEqualTo(eo.getVoucherNo());
        if (eo.getSettlementDate() != null) criteria.andSettlementDateEqualTo(eo.getSettlementDate());
        if (eo.getTranDate() != null) criteria.andTranDateEqualTo(eo.getTranDate());
        if (eo.getTranBranch() != null) criteria.andTranBranchEqualTo(eo.getTranBranch().getValue());
        if (eo.getChannel() != null) criteria.andChannelEqualTo(eo.getChannel().getValue());
        if (eo.getTranType() != null) criteria.andTranTypeEqualTo(eo.getTranType().getValue());
        if (eo.getTranAmt() != null) criteria.andTranAmtEqualTo(eo.getTranAmt());
        if (eo.getCcy() != null) criteria.andCcyEqualTo(eo.getCcy().getValue());
        if (eo.getServCharge() != null) criteria.andServChargeEqualTo(eo.getServCharge().getValue());
        if (eo.getTranDesc() != null) criteria.andTranDescEqualTo(eo.getTranDesc());
        if (eo.getTranNote() != null) criteria.andTranNoteEqualTo(eo.getTranNote());
        if (eo.getGlCode() != null) criteria.andGlCodeEqualTo(eo.getGlCode());
        if (eo.getFhSeqNo() != null) criteria.andFhSeqNoEqualTo(eo.getFhSeqNo());
        if (eo.getNarrative() != null) criteria.andNarrativeEqualTo(eo.getNarrative());
        if (eo.getOthTranType() != null) criteria.andOthTranTypeEqualTo(eo.getOthTranType().getValue());
        if (eo.getOthReference() != null) criteria.andOthReferenceEqualTo(eo.getOthReference());
        if (eo.getOthSeqNo() != null) criteria.andOthSeqNoEqualTo(eo.getOthSeqNo());
        if (eo.getOthGlCode() != null) criteria.andOthGlCodeEqualTo(eo.getOthGlCode());
        if (eo.getOthTranName() != null) criteria.andOthTranNameEqualTo(eo.getOthTranName());
        if (eo.getOthBranch() != null) criteria.andOthBranchEqualTo(eo.getOthBranch().getValue());
        if (eo.getOthBaseAcctNo() != null) criteria.andOthBaseAcctNoEqualTo(eo.getOthBaseAcctNo());
        if (eo.getOthProdType() != null) criteria.andOthProdTypeEqualTo(eo.getOthProdType());
        if (eo.getOthAcctCcy() != null) criteria.andOthAcctCcyEqualTo(eo.getOthAcctCcy().getValue());
        if (eo.getOthAcctSeqNo() != null) criteria.andOthAcctSeqNoEqualTo(eo.getOthAcctSeqNo());
        if (eo.getOthAcctDesc() != null) criteria.andOthAcctDescEqualTo(eo.getOthAcctDesc());
        if (eo.getOthBankCode() != null) criteria.andOthBankCodeEqualTo(eo.getOthBankCode());
        if (eo.getOthBankName() != null) criteria.andOthBankNameEqualTo(eo.getOthBankName());
        if (eo.getBatchStatus() != null) criteria.andBatchStatusEqualTo(eo.getBatchStatus().getValue());
        if (eo.getRemark1() != null) criteria.andRemark1EqualTo(eo.getRemark1());
        if (eo.getRemark2() != null) criteria.andRemark2EqualTo(eo.getRemark2());
        if (eo.getRemark3() != null) criteria.andRemark3EqualTo(eo.getRemark3());
        if (eo.getRemark4() != null) criteria.andRemark4EqualTo(eo.getRemark4());
        if (eo.getRemark5() != null) criteria.andRemark5EqualTo(eo.getRemark5());
        if (eo.getRetMsg() != null) criteria.andRetMsgEqualTo(eo.getRetMsg());
        if (eo.getErrorCode() != null) criteria.andErrorCodeEqualTo(eo.getErrorCode());
        if (eo.getErrorDesc() != null) criteria.andErrorDescEqualTo(eo.getErrorDesc());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getNarrativeCode() != null) criteria.andNarrativeCodeEqualTo(eo.getNarrativeCode());
        if (eo.getOthRealBankName() != null) criteria.andOthRealBankNameEqualTo(eo.getOthRealBankName());
        if (eo.getOthRealBankCode() != null) criteria.andOthRealBankCodeEqualTo(eo.getOthRealBankCode());
        if (eo.getOthRealBaseAcctNo() != null) criteria.andOthRealBaseAcctNoEqualTo(eo.getOthRealBaseAcctNo());
        if (eo.getOthRealDocumentId() != null) criteria.andOthRealDocumentIdEqualTo(eo.getOthRealDocumentId());
        if (eo.getOthRealProdType() != null) criteria.andOthRealProdTypeEqualTo(eo.getOthRealProdType());
        if (eo.getOthRealDocumentType() != null) criteria.andOthRealDocumentTypeEqualTo(eo.getOthRealDocumentType().getValue());
        if (eo.getOthRealTranAddr() != null) criteria.andOthRealTranAddrEqualTo(eo.getOthRealTranAddr());
        if (eo.getOthRealTranName() != null) criteria.andOthRealTranNameEqualTo(eo.getOthRealTranName());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getTranStatus() != null) criteria.andTranStatusEqualTo(eo.getTranStatus().getValue());
        return example;
    }
}