package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbBillRegister;
import com.dcits.deposit.entity.RbBillRegisterExample;
import com.dcits.deposit.facade.eo.RbBillRegisterEO;
import com.dcits.deposit.enums.BillBusiType;
import com.dcits.deposit.enums.BillType;
import com.dcits.deposit.enums.BillStatus;
import com.dcits.deposit.enums.DocType;
import com.dcits.deposit.enums.DocClass;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.BillIssueType;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.BillPaymentStatus;
import com.dcits.deposit.enums.BillIssueType;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.ReturnType;
import com.dcits.deposit.enums.Company;

public final class RbBillRegisterValueUtil {
    private RbBillRegisterValueUtil() {
    }

    public static RbBillRegisterEO entityToEo(RbBillRegister entity) {
        if (entity == null) {
            return null;
        }
        RbBillRegisterEO eo = new RbBillRegisterEO();
        eo.setBillSerialNo(entity.getBillSerialNo());
        eo.setClientNo(entity.getClientNo());
        eo.setBillNo(entity.getBillNo());
        eo.setBillBusiType(BillBusiType.byValue(entity.getBillBusiType()));
        eo.setBillType(BillType.byValue(entity.getBillType()));
        eo.setBillStatus(BillStatus.byValue(entity.getBillStatus()));
        eo.setBillPrefix(entity.getBillPrefix());
        eo.setBillVoucherNo(entity.getBillVoucherNo());
        eo.setDocType(DocType.byValue(entity.getDocType()));
        eo.setDocClass(DocClass.byValue(entity.getDocClass()));
        eo.setPromptDate(entity.getPromptDate());
        eo.setSettleDate(entity.getSettleDate());
        eo.setEncryptKey(entity.getEncryptKey());
        eo.setBillApplyType(entity.getBillApplyType());
        eo.setBillApplyNo(entity.getBillApplyNo());
        eo.setBillApplyPrefix(entity.getBillApplyPrefix());
        eo.setBillApplyDate(entity.getBillApplyDate());
        eo.setBillIssueAmt(entity.getBillIssueAmt());
        eo.setBillIssueCcy(AcctCcy.byValue(entity.getBillIssueCcy()));
        eo.setBillIssueType(BillIssueType.byValue(entity.getBillIssueType()));
        eo.setBillIssueBankNo(entity.getBillIssueBankNo());
        eo.setBillIssueBankName(entity.getBillIssueBankName());
        eo.setBillIssueDate(entity.getBillIssueDate());
        eo.setBillIssueCashItem(entity.getBillIssueCashItem());
        eo.setBillIssueBranch(AcctBranch.byValue(entity.getBillIssueBranch()));
        eo.setBillIssueUserId(entity.getBillIssueUserId());
        eo.setApprUserId(entity.getApprUserId());
        eo.setAuthUserId(entity.getAuthUserId());
        eo.setPrintCnt(entity.getPrintCnt());
        eo.setAgentPayerBankNo(entity.getAgentPayerBankNo());
        eo.setAgentPayerBankName(entity.getAgentPayerBankName());
        eo.setBillPaymentStatus(BillPaymentStatus.byValue(entity.getBillPaymentStatus()));
        eo.setBillPaymentAmt(entity.getBillPaymentAmt());
        eo.setExcessAmt(entity.getExcessAmt());
        eo.setPaymentType(BillIssueType.byValue(entity.getPaymentType()));
        eo.setPaymentDate(entity.getPaymentDate());
        eo.setPaymentCashItem(entity.getPaymentCashItem());
        eo.setPaymentBankNo(entity.getPaymentBankNo());
        eo.setPaymentBankName(entity.getPaymentBankName());
        eo.setPayerBaseAcctNo(entity.getPayerBaseAcctNo());
        eo.setPayerBankName(entity.getPayerBankName());
        eo.setPayerAcctName(entity.getPayerAcctName());
        eo.setPayerAcctCcy(AcctCcy.byValue(entity.getPayerAcctCcy()));
        eo.setPayerAcctProdType(entity.getPayerAcctProdType());
        eo.setPayerAcctSeqNo(entity.getPayerAcctSeqNo());
        eo.setPayerDocumentId(entity.getPayerDocumentId());
        eo.setPayerDocumentType(DocumentType.byValue(entity.getPayerDocumentType()));
        eo.setPayerAddr(entity.getPayerAddr());
        eo.setPayerBankCode(AcctBranch.byValue(entity.getPayerBankCode()));
        eo.setPayeeBaseAcctNo(entity.getPayeeBaseAcctNo());
        eo.setPayeeAcctSeqNo(entity.getPayeeAcctSeqNo());
        eo.setPayeeProdType(entity.getPayeeProdType());
        eo.setPayeeAcctCcy(AcctCcy.byValue(entity.getPayeeAcctCcy()));
        eo.setPayeeAcctName(entity.getPayeeAcctName());
        eo.setPayeeAddr(entity.getPayeeAddr());
        eo.setPayeeDocumentType(DocumentType.byValue(entity.getPayeeDocumentType()));
        eo.setPayeeDocumentId(entity.getPayeeDocumentId());
        eo.setPayeeBankCode(entity.getPayeeBankCode());
        eo.setPayeeBankName(entity.getPayeeBankName());
        eo.setReturnBaseAcctNo(entity.getReturnBaseAcctNo());
        eo.setReturnAcctName(entity.getReturnAcctName());
        eo.setReturnDocumentId(entity.getReturnDocumentId());
        eo.setReturnDocumentType(DocumentType.byValue(entity.getReturnDocumentType()));
        eo.setRefundBankNo(entity.getRefundBankNo());
        eo.setReturnCashItem(entity.getReturnCashItem());
        eo.setReturnType(ReturnType.byValue(entity.getReturnType()));
        eo.setReturnUser(entity.getReturnUser());
        eo.setReturnDate(entity.getReturnDate());
        eo.setLastHolderName(entity.getLastHolderName());
        eo.setLastHolderBaseAcctNo(entity.getLastHolderBaseAcctNo());
        eo.setLastHolderBankCode(entity.getLastHolderBankCode());
        eo.setLastHolderBankName(entity.getLastHolderBankName());
        eo.setRemark(entity.getRemark());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setLastTranDate(entity.getLastTranDate());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setLastChangeDate(entity.getLastChangeDate());
        return eo;
    }

    public static RbBillRegister eoToEntity(RbBillRegisterEO eo) {
        if (eo == null) {
            return null;
        }
        RbBillRegister entity = new RbBillRegister();
        entity.setBillSerialNo(eo.getBillSerialNo());
        entity.setClientNo(eo.getClientNo());
        entity.setBillNo(eo.getBillNo());
        entity.setBillBusiType(eo.getBillBusiType() == null ? null : eo.getBillBusiType().getValue());
        entity.setBillType(eo.getBillType() == null ? null : eo.getBillType().getValue());
        entity.setBillStatus(eo.getBillStatus() == null ? null : eo.getBillStatus().getValue());
        entity.setBillPrefix(eo.getBillPrefix());
        entity.setBillVoucherNo(eo.getBillVoucherNo());
        entity.setDocType(eo.getDocType() == null ? null : eo.getDocType().getValue());
        entity.setDocClass(eo.getDocClass() == null ? null : eo.getDocClass().getValue());
        entity.setPromptDate(eo.getPromptDate());
        entity.setSettleDate(eo.getSettleDate());
        entity.setEncryptKey(eo.getEncryptKey());
        entity.setBillApplyType(eo.getBillApplyType());
        entity.setBillApplyNo(eo.getBillApplyNo());
        entity.setBillApplyPrefix(eo.getBillApplyPrefix());
        entity.setBillApplyDate(eo.getBillApplyDate());
        entity.setBillIssueAmt(eo.getBillIssueAmt());
        entity.setBillIssueCcy(eo.getBillIssueCcy() == null ? null : eo.getBillIssueCcy().getValue());
        entity.setBillIssueType(eo.getBillIssueType() == null ? null : eo.getBillIssueType().getValue());
        entity.setBillIssueBankNo(eo.getBillIssueBankNo());
        entity.setBillIssueBankName(eo.getBillIssueBankName());
        entity.setBillIssueDate(eo.getBillIssueDate());
        entity.setBillIssueCashItem(eo.getBillIssueCashItem());
        entity.setBillIssueBranch(eo.getBillIssueBranch() == null ? null : eo.getBillIssueBranch().getValue());
        entity.setBillIssueUserId(eo.getBillIssueUserId());
        entity.setApprUserId(eo.getApprUserId());
        entity.setAuthUserId(eo.getAuthUserId());
        entity.setPrintCnt(eo.getPrintCnt());
        entity.setAgentPayerBankNo(eo.getAgentPayerBankNo());
        entity.setAgentPayerBankName(eo.getAgentPayerBankName());
        entity.setBillPaymentStatus(eo.getBillPaymentStatus() == null ? null : eo.getBillPaymentStatus().getValue());
        entity.setBillPaymentAmt(eo.getBillPaymentAmt());
        entity.setExcessAmt(eo.getExcessAmt());
        entity.setPaymentType(eo.getPaymentType() == null ? null : eo.getPaymentType().getValue());
        entity.setPaymentDate(eo.getPaymentDate());
        entity.setPaymentCashItem(eo.getPaymentCashItem());
        entity.setPaymentBankNo(eo.getPaymentBankNo());
        entity.setPaymentBankName(eo.getPaymentBankName());
        entity.setPayerBaseAcctNo(eo.getPayerBaseAcctNo());
        entity.setPayerBankName(eo.getPayerBankName());
        entity.setPayerAcctName(eo.getPayerAcctName());
        entity.setPayerAcctCcy(eo.getPayerAcctCcy() == null ? null : eo.getPayerAcctCcy().getValue());
        entity.setPayerAcctProdType(eo.getPayerAcctProdType());
        entity.setPayerAcctSeqNo(eo.getPayerAcctSeqNo());
        entity.setPayerDocumentId(eo.getPayerDocumentId());
        entity.setPayerDocumentType(eo.getPayerDocumentType() == null ? null : eo.getPayerDocumentType().getValue());
        entity.setPayerAddr(eo.getPayerAddr());
        entity.setPayerBankCode(eo.getPayerBankCode() == null ? null : eo.getPayerBankCode().getValue());
        entity.setPayeeBaseAcctNo(eo.getPayeeBaseAcctNo());
        entity.setPayeeAcctSeqNo(eo.getPayeeAcctSeqNo());
        entity.setPayeeProdType(eo.getPayeeProdType());
        entity.setPayeeAcctCcy(eo.getPayeeAcctCcy() == null ? null : eo.getPayeeAcctCcy().getValue());
        entity.setPayeeAcctName(eo.getPayeeAcctName());
        entity.setPayeeAddr(eo.getPayeeAddr());
        entity.setPayeeDocumentType(eo.getPayeeDocumentType() == null ? null : eo.getPayeeDocumentType().getValue());
        entity.setPayeeDocumentId(eo.getPayeeDocumentId());
        entity.setPayeeBankCode(eo.getPayeeBankCode());
        entity.setPayeeBankName(eo.getPayeeBankName());
        entity.setReturnBaseAcctNo(eo.getReturnBaseAcctNo());
        entity.setReturnAcctName(eo.getReturnAcctName());
        entity.setReturnDocumentId(eo.getReturnDocumentId());
        entity.setReturnDocumentType(eo.getReturnDocumentType() == null ? null : eo.getReturnDocumentType().getValue());
        entity.setRefundBankNo(eo.getRefundBankNo());
        entity.setReturnCashItem(eo.getReturnCashItem());
        entity.setReturnType(eo.getReturnType() == null ? null : eo.getReturnType().getValue());
        entity.setReturnUser(eo.getReturnUser());
        entity.setReturnDate(eo.getReturnDate());
        entity.setLastHolderName(eo.getLastHolderName());
        entity.setLastHolderBaseAcctNo(eo.getLastHolderBaseAcctNo());
        entity.setLastHolderBankCode(eo.getLastHolderBankCode());
        entity.setLastHolderBankName(eo.getLastHolderBankName());
        entity.setRemark(eo.getRemark());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setLastTranDate(eo.getLastTranDate());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setLastChangeDate(eo.getLastChangeDate());
        return entity;
    }

    public static RbBillRegisterExample eoToEntityExample(RbBillRegisterEO eo) {
        if (eo == null) {
            return null;
        }
        RbBillRegisterExample example = new RbBillRegisterExample();
        RbBillRegisterExample.Criteria criteria = example.createCriteria();
        if (eo.getBillSerialNo() != null) criteria.andBillSerialNoEqualTo(eo.getBillSerialNo());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getBillNo() != null) criteria.andBillNoEqualTo(eo.getBillNo());
        if (eo.getBillBusiType() != null) criteria.andBillBusiTypeEqualTo(eo.getBillBusiType().getValue());
        if (eo.getBillType() != null) criteria.andBillTypeEqualTo(eo.getBillType().getValue());
        if (eo.getBillStatus() != null) criteria.andBillStatusEqualTo(eo.getBillStatus().getValue());
        if (eo.getBillPrefix() != null) criteria.andBillPrefixEqualTo(eo.getBillPrefix());
        if (eo.getBillVoucherNo() != null) criteria.andBillVoucherNoEqualTo(eo.getBillVoucherNo());
        if (eo.getDocType() != null) criteria.andDocTypeEqualTo(eo.getDocType().getValue());
        if (eo.getDocClass() != null) criteria.andDocClassEqualTo(eo.getDocClass().getValue());
        if (eo.getPromptDate() != null) criteria.andPromptDateEqualTo(eo.getPromptDate());
        if (eo.getSettleDate() != null) criteria.andSettleDateEqualTo(eo.getSettleDate());
        if (eo.getEncryptKey() != null) criteria.andEncryptKeyEqualTo(eo.getEncryptKey());
        if (eo.getBillApplyType() != null) criteria.andBillApplyTypeEqualTo(eo.getBillApplyType());
        if (eo.getBillApplyNo() != null) criteria.andBillApplyNoEqualTo(eo.getBillApplyNo());
        if (eo.getBillApplyPrefix() != null) criteria.andBillApplyPrefixEqualTo(eo.getBillApplyPrefix());
        if (eo.getBillApplyDate() != null) criteria.andBillApplyDateEqualTo(eo.getBillApplyDate());
        if (eo.getBillIssueAmt() != null) criteria.andBillIssueAmtEqualTo(eo.getBillIssueAmt());
        if (eo.getBillIssueCcy() != null) criteria.andBillIssueCcyEqualTo(eo.getBillIssueCcy().getValue());
        if (eo.getBillIssueType() != null) criteria.andBillIssueTypeEqualTo(eo.getBillIssueType().getValue());
        if (eo.getBillIssueBankNo() != null) criteria.andBillIssueBankNoEqualTo(eo.getBillIssueBankNo());
        if (eo.getBillIssueBankName() != null) criteria.andBillIssueBankNameEqualTo(eo.getBillIssueBankName());
        if (eo.getBillIssueDate() != null) criteria.andBillIssueDateEqualTo(eo.getBillIssueDate());
        if (eo.getBillIssueCashItem() != null) criteria.andBillIssueCashItemEqualTo(eo.getBillIssueCashItem());
        if (eo.getBillIssueBranch() != null) criteria.andBillIssueBranchEqualTo(eo.getBillIssueBranch().getValue());
        if (eo.getBillIssueUserId() != null) criteria.andBillIssueUserIdEqualTo(eo.getBillIssueUserId());
        if (eo.getApprUserId() != null) criteria.andApprUserIdEqualTo(eo.getApprUserId());
        if (eo.getAuthUserId() != null) criteria.andAuthUserIdEqualTo(eo.getAuthUserId());
        if (eo.getPrintCnt() != null) criteria.andPrintCntEqualTo(eo.getPrintCnt());
        if (eo.getAgentPayerBankNo() != null) criteria.andAgentPayerBankNoEqualTo(eo.getAgentPayerBankNo());
        if (eo.getAgentPayerBankName() != null) criteria.andAgentPayerBankNameEqualTo(eo.getAgentPayerBankName());
        if (eo.getBillPaymentStatus() != null) criteria.andBillPaymentStatusEqualTo(eo.getBillPaymentStatus().getValue());
        if (eo.getBillPaymentAmt() != null) criteria.andBillPaymentAmtEqualTo(eo.getBillPaymentAmt());
        if (eo.getExcessAmt() != null) criteria.andExcessAmtEqualTo(eo.getExcessAmt());
        if (eo.getPaymentType() != null) criteria.andPaymentTypeEqualTo(eo.getPaymentType().getValue());
        if (eo.getPaymentDate() != null) criteria.andPaymentDateEqualTo(eo.getPaymentDate());
        if (eo.getPaymentCashItem() != null) criteria.andPaymentCashItemEqualTo(eo.getPaymentCashItem());
        if (eo.getPaymentBankNo() != null) criteria.andPaymentBankNoEqualTo(eo.getPaymentBankNo());
        if (eo.getPaymentBankName() != null) criteria.andPaymentBankNameEqualTo(eo.getPaymentBankName());
        if (eo.getPayerBaseAcctNo() != null) criteria.andPayerBaseAcctNoEqualTo(eo.getPayerBaseAcctNo());
        if (eo.getPayerBankName() != null) criteria.andPayerBankNameEqualTo(eo.getPayerBankName());
        if (eo.getPayerAcctName() != null) criteria.andPayerAcctNameEqualTo(eo.getPayerAcctName());
        if (eo.getPayerAcctCcy() != null) criteria.andPayerAcctCcyEqualTo(eo.getPayerAcctCcy().getValue());
        if (eo.getPayerAcctProdType() != null) criteria.andPayerAcctProdTypeEqualTo(eo.getPayerAcctProdType());
        if (eo.getPayerAcctSeqNo() != null) criteria.andPayerAcctSeqNoEqualTo(eo.getPayerAcctSeqNo());
        if (eo.getPayerDocumentId() != null) criteria.andPayerDocumentIdEqualTo(eo.getPayerDocumentId());
        if (eo.getPayerDocumentType() != null) criteria.andPayerDocumentTypeEqualTo(eo.getPayerDocumentType().getValue());
        if (eo.getPayerAddr() != null) criteria.andPayerAddrEqualTo(eo.getPayerAddr());
        if (eo.getPayerBankCode() != null) criteria.andPayerBankCodeEqualTo(eo.getPayerBankCode().getValue());
        if (eo.getPayeeBaseAcctNo() != null) criteria.andPayeeBaseAcctNoEqualTo(eo.getPayeeBaseAcctNo());
        if (eo.getPayeeAcctSeqNo() != null) criteria.andPayeeAcctSeqNoEqualTo(eo.getPayeeAcctSeqNo());
        if (eo.getPayeeProdType() != null) criteria.andPayeeProdTypeEqualTo(eo.getPayeeProdType());
        if (eo.getPayeeAcctCcy() != null) criteria.andPayeeAcctCcyEqualTo(eo.getPayeeAcctCcy().getValue());
        if (eo.getPayeeAcctName() != null) criteria.andPayeeAcctNameEqualTo(eo.getPayeeAcctName());
        if (eo.getPayeeAddr() != null) criteria.andPayeeAddrEqualTo(eo.getPayeeAddr());
        if (eo.getPayeeDocumentType() != null) criteria.andPayeeDocumentTypeEqualTo(eo.getPayeeDocumentType().getValue());
        if (eo.getPayeeDocumentId() != null) criteria.andPayeeDocumentIdEqualTo(eo.getPayeeDocumentId());
        if (eo.getPayeeBankCode() != null) criteria.andPayeeBankCodeEqualTo(eo.getPayeeBankCode());
        if (eo.getPayeeBankName() != null) criteria.andPayeeBankNameEqualTo(eo.getPayeeBankName());
        if (eo.getReturnBaseAcctNo() != null) criteria.andReturnBaseAcctNoEqualTo(eo.getReturnBaseAcctNo());
        if (eo.getReturnAcctName() != null) criteria.andReturnAcctNameEqualTo(eo.getReturnAcctName());
        if (eo.getReturnDocumentId() != null) criteria.andReturnDocumentIdEqualTo(eo.getReturnDocumentId());
        if (eo.getReturnDocumentType() != null) criteria.andReturnDocumentTypeEqualTo(eo.getReturnDocumentType().getValue());
        if (eo.getRefundBankNo() != null) criteria.andRefundBankNoEqualTo(eo.getRefundBankNo());
        if (eo.getReturnCashItem() != null) criteria.andReturnCashItemEqualTo(eo.getReturnCashItem());
        if (eo.getReturnType() != null) criteria.andReturnTypeEqualTo(eo.getReturnType().getValue());
        if (eo.getReturnUser() != null) criteria.andReturnUserEqualTo(eo.getReturnUser());
        if (eo.getReturnDate() != null) criteria.andReturnDateEqualTo(eo.getReturnDate());
        if (eo.getLastHolderName() != null) criteria.andLastHolderNameEqualTo(eo.getLastHolderName());
        if (eo.getLastHolderBaseAcctNo() != null) criteria.andLastHolderBaseAcctNoEqualTo(eo.getLastHolderBaseAcctNo());
        if (eo.getLastHolderBankCode() != null) criteria.andLastHolderBankCodeEqualTo(eo.getLastHolderBankCode());
        if (eo.getLastHolderBankName() != null) criteria.andLastHolderBankNameEqualTo(eo.getLastHolderBankName());
        if (eo.getRemark() != null) criteria.andRemarkEqualTo(eo.getRemark());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getLastTranDate() != null) criteria.andLastTranDateEqualTo(eo.getLastTranDate());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        return example;
    }
}