package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbDcPrecontract;
import com.dcits.deposit.entity.RbDcPrecontractExample;
import com.dcits.deposit.facade.eo.RbDcPrecontractEO;
import com.dcits.deposit.enums.PrecontractType;
import com.dcits.deposit.enums.PrecontractStatus;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctNature;
import com.dcits.deposit.enums.AcctStatus;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.StageLimitClass;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.PayIntMode;
import com.dcits.deposit.enums.CycleFreq;
import com.dcits.deposit.enums.IntType;
import com.dcits.deposit.enums.SourceType;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.WithdrawalType;
import com.dcits.deposit.enums.StageProdClass;
import com.dcits.deposit.enums.IntCalcType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.Company;

public final class RbDcPrecontractValueUtil {
    private RbDcPrecontractValueUtil() {
    }

    public static RbDcPrecontractEO entityToEo(RbDcPrecontract entity) {
        if (entity == null) {
            return null;
        }
        RbDcPrecontractEO eo = new RbDcPrecontractEO();
        eo.setPrecontractNo(entity.getPrecontractNo());
        eo.setClientNo(entity.getClientNo());
        eo.setStageCode(entity.getStageCode());
        eo.setIssueYear(entity.getIssueYear());
        eo.setPrecontractType(PrecontractType.byValue(entity.getPrecontractType()));
        eo.setPrecontractStatus(PrecontractStatus.byValue(entity.getPrecontractStatus()));
        eo.setInternalKey(entity.getInternalKey());
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setProdType(entity.getProdType());
        eo.setAcctSeqNo(entity.getAcctSeqNo());
        eo.setAcctCcy(AcctCcy.byValue(entity.getAcctCcy()));
        eo.setAcctName(entity.getAcctName());
        eo.setAcctNature(AcctNature.byValue(entity.getAcctNature()));
        eo.setAcctStatus(AcctStatus.byValue(entity.getAcctStatus()));
        eo.setBranch(AcctBranch.byValue(entity.getBranch()));
        eo.setPrecontractBranch(AcctBranch.byValue(entity.getPrecontractBranch()));
        eo.setPrecontractDate(entity.getPrecontractDate());
        eo.setPrecontractCcy(AcctCcy.byValue(entity.getPrecontractCcy()));
        eo.setPrecontractAmt(entity.getPrecontractAmt());
        eo.setPrecontractOpenDate(entity.getPrecontractOpenDate());
        eo.setStageLimitClass(StageLimitClass.byValue(entity.getStageLimitClass()));
        eo.setIntStartDate(entity.getIntStartDate());
        eo.setAutoSettleFlag(IndividualFlag.byValue(entity.getAutoSettleFlag()));
        eo.setCycleIntFlag(IndividualFlag.byValue(entity.getCycleIntFlag()));
        eo.setPayIntMode(PayIntMode.byValue(entity.getPayIntMode()));
        eo.setCycleFreq(CycleFreq.byValue(entity.getCycleFreq()));
        eo.setIntDay(entity.getIntDay());
        eo.setHangSeqNo(entity.getHangSeqNo());
        eo.setSubHangSeqNo(entity.getSubHangSeqNo());
        eo.setTranAmt(entity.getTranAmt());
        eo.setIssueStartDate(entity.getIssueStartDate());
        eo.setIssueEndDate(entity.getIssueEndDate());
        eo.setIssueAmt(entity.getIssueAmt());
        eo.setIntType(IntType.byValue(entity.getIntType()));
        eo.setFloatRate(entity.getFloatRate());
        eo.setRealRate(entity.getRealRate());
        eo.setActualRate(entity.getActualRate());
        eo.setSourceType(SourceType.byValue(entity.getSourceType()));
        eo.setNarrative(entity.getNarrative());
        eo.setReference(entity.getReference());
        eo.setOthInternalKey(entity.getOthInternalKey());
        eo.setOthBaseAcctNo(entity.getOthBaseAcctNo());
        eo.setOthProdType(entity.getOthProdType());
        eo.setOthCcy(AcctCcy.byValue(entity.getOthCcy()));
        eo.setOthAcctSeqNo(entity.getOthAcctSeqNo());
        eo.setOthAcctName(entity.getOthAcctName());
        eo.setSubsInternalKey(entity.getSubsInternalKey());
        eo.setIntInternalKey(entity.getIntInternalKey());
        eo.setPledgedFlag(IndividualFlag.byValue(entity.getPledgedFlag()));
        eo.setResSeqNo(entity.getResSeqNo());
        eo.setTrfNo(entity.getTrfNo());
        eo.setTrfTotalSettleAmt(entity.getTrfTotalSettleAmt());
        eo.setRedeemDate(entity.getRedeemDate());
        eo.setExpRedeemIntAmt(entity.getExpRedeemIntAmt());
        eo.setWithdrawalType(WithdrawalType.byValue(entity.getWithdrawalType()));
        eo.setVoucherNo(entity.getVoucherNo());
        eo.setPrintCnt(entity.getPrintCnt());
        eo.setStageProdClass(StageProdClass.byValue(entity.getStageProdClass()));
        eo.setIntCalcType(IntCalcType.byValue(entity.getIntCalcType()));
        eo.setIntTaxLevy(IndividualFlag.byValue(entity.getIntTaxLevy()));
        eo.setFailureReason(entity.getFailureReason());
        eo.setDeleteDate(entity.getDeleteDate());
        eo.setDelReason(entity.getDelReason());
        eo.setUserId(entity.getUserId());
        eo.setAuthUserId(entity.getAuthUserId());
        eo.setDelUserId(entity.getDelUserId());
        eo.setDelAuthUserId(entity.getDelAuthUserId());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setSettleInternalKey(entity.getSettleInternalKey());
        return eo;
    }

    public static RbDcPrecontract eoToEntity(RbDcPrecontractEO eo) {
        if (eo == null) {
            return null;
        }
        RbDcPrecontract entity = new RbDcPrecontract();
        entity.setPrecontractNo(eo.getPrecontractNo());
        entity.setClientNo(eo.getClientNo());
        entity.setStageCode(eo.getStageCode());
        entity.setIssueYear(eo.getIssueYear());
        entity.setPrecontractType(eo.getPrecontractType() == null ? null : eo.getPrecontractType().getValue());
        entity.setPrecontractStatus(eo.getPrecontractStatus() == null ? null : eo.getPrecontractStatus().getValue());
        entity.setInternalKey(eo.getInternalKey());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setProdType(eo.getProdType());
        entity.setAcctSeqNo(eo.getAcctSeqNo());
        entity.setAcctCcy(eo.getAcctCcy() == null ? null : eo.getAcctCcy().getValue());
        entity.setAcctName(eo.getAcctName());
        entity.setAcctNature(eo.getAcctNature() == null ? null : eo.getAcctNature().getValue());
        entity.setAcctStatus(eo.getAcctStatus() == null ? null : eo.getAcctStatus().getValue());
        entity.setBranch(eo.getBranch() == null ? null : eo.getBranch().getValue());
        entity.setPrecontractBranch(eo.getPrecontractBranch() == null ? null : eo.getPrecontractBranch().getValue());
        entity.setPrecontractDate(eo.getPrecontractDate());
        entity.setPrecontractCcy(eo.getPrecontractCcy() == null ? null : eo.getPrecontractCcy().getValue());
        entity.setPrecontractAmt(eo.getPrecontractAmt());
        entity.setPrecontractOpenDate(eo.getPrecontractOpenDate());
        entity.setStageLimitClass(eo.getStageLimitClass() == null ? null : eo.getStageLimitClass().getValue());
        entity.setIntStartDate(eo.getIntStartDate());
        entity.setAutoSettleFlag(eo.getAutoSettleFlag() == null ? null : eo.getAutoSettleFlag().getValue());
        entity.setCycleIntFlag(eo.getCycleIntFlag() == null ? null : eo.getCycleIntFlag().getValue());
        entity.setPayIntMode(eo.getPayIntMode() == null ? null : eo.getPayIntMode().getValue());
        entity.setCycleFreq(eo.getCycleFreq() == null ? null : eo.getCycleFreq().getValue());
        entity.setIntDay(eo.getIntDay());
        entity.setHangSeqNo(eo.getHangSeqNo());
        entity.setSubHangSeqNo(eo.getSubHangSeqNo());
        entity.setTranAmt(eo.getTranAmt());
        entity.setIssueStartDate(eo.getIssueStartDate());
        entity.setIssueEndDate(eo.getIssueEndDate());
        entity.setIssueAmt(eo.getIssueAmt());
        entity.setIntType(eo.getIntType() == null ? null : eo.getIntType().getValue());
        entity.setFloatRate(eo.getFloatRate());
        entity.setRealRate(eo.getRealRate());
        entity.setActualRate(eo.getActualRate());
        entity.setSourceType(eo.getSourceType() == null ? null : eo.getSourceType().getValue());
        entity.setNarrative(eo.getNarrative());
        entity.setReference(eo.getReference());
        entity.setOthInternalKey(eo.getOthInternalKey());
        entity.setOthBaseAcctNo(eo.getOthBaseAcctNo());
        entity.setOthProdType(eo.getOthProdType());
        entity.setOthCcy(eo.getOthCcy() == null ? null : eo.getOthCcy().getValue());
        entity.setOthAcctSeqNo(eo.getOthAcctSeqNo());
        entity.setOthAcctName(eo.getOthAcctName());
        entity.setSubsInternalKey(eo.getSubsInternalKey());
        entity.setIntInternalKey(eo.getIntInternalKey());
        entity.setPledgedFlag(eo.getPledgedFlag() == null ? null : eo.getPledgedFlag().getValue());
        entity.setResSeqNo(eo.getResSeqNo());
        entity.setTrfNo(eo.getTrfNo());
        entity.setTrfTotalSettleAmt(eo.getTrfTotalSettleAmt());
        entity.setRedeemDate(eo.getRedeemDate());
        entity.setExpRedeemIntAmt(eo.getExpRedeemIntAmt());
        entity.setWithdrawalType(eo.getWithdrawalType() == null ? null : eo.getWithdrawalType().getValue());
        entity.setVoucherNo(eo.getVoucherNo());
        entity.setPrintCnt(eo.getPrintCnt());
        entity.setStageProdClass(eo.getStageProdClass() == null ? null : eo.getStageProdClass().getValue());
        entity.setIntCalcType(eo.getIntCalcType() == null ? null : eo.getIntCalcType().getValue());
        entity.setIntTaxLevy(eo.getIntTaxLevy() == null ? null : eo.getIntTaxLevy().getValue());
        entity.setFailureReason(eo.getFailureReason());
        entity.setDeleteDate(eo.getDeleteDate());
        entity.setDelReason(eo.getDelReason());
        entity.setUserId(eo.getUserId());
        entity.setAuthUserId(eo.getAuthUserId());
        entity.setDelUserId(eo.getDelUserId());
        entity.setDelAuthUserId(eo.getDelAuthUserId());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setSettleInternalKey(eo.getSettleInternalKey());
        return entity;
    }

    public static RbDcPrecontractExample eoToEntityExample(RbDcPrecontractEO eo) {
        if (eo == null) {
            return null;
        }
        RbDcPrecontractExample example = new RbDcPrecontractExample();
        RbDcPrecontractExample.Criteria criteria = example.createCriteria();
        if (eo.getPrecontractNo() != null) criteria.andPrecontractNoEqualTo(eo.getPrecontractNo());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getStageCode() != null) criteria.andStageCodeEqualTo(eo.getStageCode());
        if (eo.getIssueYear() != null) criteria.andIssueYearEqualTo(eo.getIssueYear());
        if (eo.getPrecontractType() != null) criteria.andPrecontractTypeEqualTo(eo.getPrecontractType().getValue());
        if (eo.getPrecontractStatus() != null) criteria.andPrecontractStatusEqualTo(eo.getPrecontractStatus().getValue());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getProdType() != null) criteria.andProdTypeEqualTo(eo.getProdType());
        if (eo.getAcctSeqNo() != null) criteria.andAcctSeqNoEqualTo(eo.getAcctSeqNo());
        if (eo.getAcctCcy() != null) criteria.andAcctCcyEqualTo(eo.getAcctCcy().getValue());
        if (eo.getAcctName() != null) criteria.andAcctNameEqualTo(eo.getAcctName());
        if (eo.getAcctNature() != null) criteria.andAcctNatureEqualTo(eo.getAcctNature().getValue());
        if (eo.getAcctStatus() != null) criteria.andAcctStatusEqualTo(eo.getAcctStatus().getValue());
        if (eo.getBranch() != null) criteria.andBranchEqualTo(eo.getBranch().getValue());
        if (eo.getPrecontractBranch() != null) criteria.andPrecontractBranchEqualTo(eo.getPrecontractBranch().getValue());
        if (eo.getPrecontractDate() != null) criteria.andPrecontractDateEqualTo(eo.getPrecontractDate());
        if (eo.getPrecontractCcy() != null) criteria.andPrecontractCcyEqualTo(eo.getPrecontractCcy().getValue());
        if (eo.getPrecontractAmt() != null) criteria.andPrecontractAmtEqualTo(eo.getPrecontractAmt());
        if (eo.getPrecontractOpenDate() != null) criteria.andPrecontractOpenDateEqualTo(eo.getPrecontractOpenDate());
        if (eo.getStageLimitClass() != null) criteria.andStageLimitClassEqualTo(eo.getStageLimitClass().getValue());
        if (eo.getIntStartDate() != null) criteria.andIntStartDateEqualTo(eo.getIntStartDate());
        if (eo.getAutoSettleFlag() != null) criteria.andAutoSettleFlagEqualTo(eo.getAutoSettleFlag().getValue());
        if (eo.getCycleIntFlag() != null) criteria.andCycleIntFlagEqualTo(eo.getCycleIntFlag().getValue());
        if (eo.getPayIntMode() != null) criteria.andPayIntModeEqualTo(eo.getPayIntMode().getValue());
        if (eo.getCycleFreq() != null) criteria.andCycleFreqEqualTo(eo.getCycleFreq().getValue());
        if (eo.getIntDay() != null) criteria.andIntDayEqualTo(eo.getIntDay());
        if (eo.getHangSeqNo() != null) criteria.andHangSeqNoEqualTo(eo.getHangSeqNo());
        if (eo.getSubHangSeqNo() != null) criteria.andSubHangSeqNoEqualTo(eo.getSubHangSeqNo());
        if (eo.getTranAmt() != null) criteria.andTranAmtEqualTo(eo.getTranAmt());
        if (eo.getIssueStartDate() != null) criteria.andIssueStartDateEqualTo(eo.getIssueStartDate());
        if (eo.getIssueEndDate() != null) criteria.andIssueEndDateEqualTo(eo.getIssueEndDate());
        if (eo.getIssueAmt() != null) criteria.andIssueAmtEqualTo(eo.getIssueAmt());
        if (eo.getIntType() != null) criteria.andIntTypeEqualTo(eo.getIntType().getValue());
        if (eo.getFloatRate() != null) criteria.andFloatRateEqualTo(eo.getFloatRate());
        if (eo.getRealRate() != null) criteria.andRealRateEqualTo(eo.getRealRate());
        if (eo.getActualRate() != null) criteria.andActualRateEqualTo(eo.getActualRate());
        if (eo.getSourceType() != null) criteria.andSourceTypeEqualTo(eo.getSourceType().getValue());
        if (eo.getNarrative() != null) criteria.andNarrativeEqualTo(eo.getNarrative());
        if (eo.getReference() != null) criteria.andReferenceEqualTo(eo.getReference());
        if (eo.getOthInternalKey() != null) criteria.andOthInternalKeyEqualTo(eo.getOthInternalKey());
        if (eo.getOthBaseAcctNo() != null) criteria.andOthBaseAcctNoEqualTo(eo.getOthBaseAcctNo());
        if (eo.getOthProdType() != null) criteria.andOthProdTypeEqualTo(eo.getOthProdType());
        if (eo.getOthCcy() != null) criteria.andOthCcyEqualTo(eo.getOthCcy().getValue());
        if (eo.getOthAcctSeqNo() != null) criteria.andOthAcctSeqNoEqualTo(eo.getOthAcctSeqNo());
        if (eo.getOthAcctName() != null) criteria.andOthAcctNameEqualTo(eo.getOthAcctName());
        if (eo.getSubsInternalKey() != null) criteria.andSubsInternalKeyEqualTo(eo.getSubsInternalKey());
        if (eo.getIntInternalKey() != null) criteria.andIntInternalKeyEqualTo(eo.getIntInternalKey());
        if (eo.getPledgedFlag() != null) criteria.andPledgedFlagEqualTo(eo.getPledgedFlag().getValue());
        if (eo.getResSeqNo() != null) criteria.andResSeqNoEqualTo(eo.getResSeqNo());
        if (eo.getTrfNo() != null) criteria.andTrfNoEqualTo(eo.getTrfNo());
        if (eo.getTrfTotalSettleAmt() != null) criteria.andTrfTotalSettleAmtEqualTo(eo.getTrfTotalSettleAmt());
        if (eo.getRedeemDate() != null) criteria.andRedeemDateEqualTo(eo.getRedeemDate());
        if (eo.getExpRedeemIntAmt() != null) criteria.andExpRedeemIntAmtEqualTo(eo.getExpRedeemIntAmt());
        if (eo.getWithdrawalType() != null) criteria.andWithdrawalTypeEqualTo(eo.getWithdrawalType().getValue());
        if (eo.getVoucherNo() != null) criteria.andVoucherNoEqualTo(eo.getVoucherNo());
        if (eo.getPrintCnt() != null) criteria.andPrintCntEqualTo(eo.getPrintCnt());
        if (eo.getStageProdClass() != null) criteria.andStageProdClassEqualTo(eo.getStageProdClass().getValue());
        if (eo.getIntCalcType() != null) criteria.andIntCalcTypeEqualTo(eo.getIntCalcType().getValue());
        if (eo.getIntTaxLevy() != null) criteria.andIntTaxLevyEqualTo(eo.getIntTaxLevy().getValue());
        if (eo.getFailureReason() != null) criteria.andFailureReasonEqualTo(eo.getFailureReason());
        if (eo.getDeleteDate() != null) criteria.andDeleteDateEqualTo(eo.getDeleteDate());
        if (eo.getDelReason() != null) criteria.andDelReasonEqualTo(eo.getDelReason());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getAuthUserId() != null) criteria.andAuthUserIdEqualTo(eo.getAuthUserId());
        if (eo.getDelUserId() != null) criteria.andDelUserIdEqualTo(eo.getDelUserId());
        if (eo.getDelAuthUserId() != null) criteria.andDelAuthUserIdEqualTo(eo.getDelAuthUserId());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getSettleInternalKey() != null) criteria.andSettleInternalKeyEqualTo(eo.getSettleInternalKey());
        return example;
    }
}