package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbDelayTranHist;
import com.dcits.deposit.entity.RbDelayTranHistExample;
import com.dcits.deposit.facade.eo.RbDelayTranHistEO;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.TranMethod;
import com.dcits.deposit.enums.TranType;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.DocType;
import com.dcits.deposit.enums.ArrivalStatus;
import com.dcits.deposit.enums.SourceType;
import com.dcits.deposit.enums.CashItem;
import com.dcits.deposit.enums.Company;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.BankInOut;

public final class RbDelayTranHistValueUtil {
    private RbDelayTranHistValueUtil() {
    }

    public static RbDelayTranHistEO entityToEo(RbDelayTranHist entity) {
        if (entity == null) {
            return null;
        }
        RbDelayTranHistEO eo = new RbDelayTranHistEO();
        eo.setSeqNo(entity.getSeqNo());
        eo.setChannelSeqNo(entity.getChannelSeqNo());
        eo.setResSeqNo(entity.getResSeqNo());
        eo.setInternalKey(entity.getInternalKey());
        eo.setCardNo(entity.getCardNo());
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setAcctCcy(AcctCcy.byValue(entity.getAcctCcy()));
        eo.setAcctSeqNo(entity.getAcctSeqNo());
        eo.setProdType(entity.getProdType());
        eo.setClientNo(entity.getClientNo());
        eo.setClientName(entity.getClientName());
        eo.setOthInternalKey(entity.getOthInternalKey());
        eo.setOthCardNo(entity.getOthCardNo());
        eo.setOthBaseAcctNo(entity.getOthBaseAcctNo());
        eo.setOthAcctCcy(AcctCcy.byValue(entity.getOthAcctCcy()));
        eo.setOthAcctSeqNo(entity.getOthAcctSeqNo());
        eo.setOthProdType(entity.getOthProdType());
        eo.setOthAcctName(entity.getOthAcctName());
        eo.setOthAcctDesc(entity.getOthAcctDesc());
        eo.setSettleCardFlag(IndividualFlag.byValue(entity.getSettleCardFlag()));
        eo.setCcy(AcctCcy.byValue(entity.getCcy()));
        eo.setTranMethod(TranMethod.byValue(entity.getTranMethod()));
        eo.setSignTimestamp(entity.getSignTimestamp());
        eo.setTranType(TranType.byValue(entity.getTranType()));
        eo.setTranAmt(entity.getTranAmt());
        eo.setTranDate(entity.getTranDate());
        eo.setTranBranch(AcctBranch.byValue(entity.getTranBranch()));
        eo.setDocType(DocType.byValue(entity.getDocType()));
        eo.setPrefix(entity.getPrefix());
        eo.setVoucherNo(entity.getVoucherNo());
        eo.setArrivalStatus(ArrivalStatus.byValue(entity.getArrivalStatus()));
        eo.setReference(entity.getReference());
        eo.setSourceType(SourceType.byValue(entity.getSourceType()));
        eo.setExchangeTranCode(entity.getExchangeTranCode());
        eo.setExchangeTranCodet(entity.getExchangeTranCodet());
        eo.setTranDesc(entity.getTranDesc());
        eo.setTranNote(entity.getTranNote());
        eo.setCashItem(CashItem.byValue(entity.getCashItem()));
        eo.setNarrative(entity.getNarrative());
        eo.setCommissionClientName(entity.getCommissionClientName());
        eo.setCommissionClientTel(entity.getCommissionClientTel());
        eo.setPayUnit(entity.getPayUnit());
        eo.setCancelReason(entity.getCancelReason());
        eo.setTerminalId(entity.getTerminalId());
        eo.setTrack2(entity.getTrack2());
        eo.setTrack3(entity.getTrack3());
        eo.setAuthUserId(entity.getAuthUserId());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setUserId(entity.getUserId());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setSubSeqNo(entity.getSubSeqNo());
        eo.setInnerBaseAcctNo(entity.getInnerBaseAcctNo());
        eo.setInnerProdType(entity.getInnerProdType());
        eo.setInnerAcctSeqNo(entity.getInnerAcctSeqNo());
        eo.setInnerAcctCcy(AcctCcy.byValue(entity.getInnerAcctCcy()));
        eo.setInnerInternalKey(entity.getInnerInternalKey());
        eo.setInnerAcctName(entity.getInnerAcctName());
        eo.setInnerClientNo(entity.getInnerClientNo());
        eo.setHangSeqNo(entity.getHangSeqNo());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setOthClientNo(entity.getOthClientNo());
        eo.setBankInOut(BankInOut.byValue(entity.getBankInOut()));
        return eo;
    }

    public static RbDelayTranHist eoToEntity(RbDelayTranHistEO eo) {
        if (eo == null) {
            return null;
        }
        RbDelayTranHist entity = new RbDelayTranHist();
        entity.setSeqNo(eo.getSeqNo());
        entity.setChannelSeqNo(eo.getChannelSeqNo());
        entity.setResSeqNo(eo.getResSeqNo());
        entity.setInternalKey(eo.getInternalKey());
        entity.setCardNo(eo.getCardNo());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setAcctCcy(eo.getAcctCcy() == null ? null : eo.getAcctCcy().getValue());
        entity.setAcctSeqNo(eo.getAcctSeqNo());
        entity.setProdType(eo.getProdType());
        entity.setClientNo(eo.getClientNo());
        entity.setClientName(eo.getClientName());
        entity.setOthInternalKey(eo.getOthInternalKey());
        entity.setOthCardNo(eo.getOthCardNo());
        entity.setOthBaseAcctNo(eo.getOthBaseAcctNo());
        entity.setOthAcctCcy(eo.getOthAcctCcy() == null ? null : eo.getOthAcctCcy().getValue());
        entity.setOthAcctSeqNo(eo.getOthAcctSeqNo());
        entity.setOthProdType(eo.getOthProdType());
        entity.setOthAcctName(eo.getOthAcctName());
        entity.setOthAcctDesc(eo.getOthAcctDesc());
        entity.setSettleCardFlag(eo.getSettleCardFlag() == null ? null : eo.getSettleCardFlag().getValue());
        entity.setCcy(eo.getCcy() == null ? null : eo.getCcy().getValue());
        entity.setTranMethod(eo.getTranMethod() == null ? null : eo.getTranMethod().getValue());
        entity.setSignTimestamp(eo.getSignTimestamp());
        entity.setTranType(eo.getTranType() == null ? null : eo.getTranType().getValue());
        entity.setTranAmt(eo.getTranAmt());
        entity.setTranDate(eo.getTranDate());
        entity.setTranBranch(eo.getTranBranch() == null ? null : eo.getTranBranch().getValue());
        entity.setDocType(eo.getDocType() == null ? null : eo.getDocType().getValue());
        entity.setPrefix(eo.getPrefix());
        entity.setVoucherNo(eo.getVoucherNo());
        entity.setArrivalStatus(eo.getArrivalStatus() == null ? null : eo.getArrivalStatus().getValue());
        entity.setReference(eo.getReference());
        entity.setSourceType(eo.getSourceType() == null ? null : eo.getSourceType().getValue());
        entity.setExchangeTranCode(eo.getExchangeTranCode());
        entity.setExchangeTranCodet(eo.getExchangeTranCodet());
        entity.setTranDesc(eo.getTranDesc());
        entity.setTranNote(eo.getTranNote());
        entity.setCashItem(eo.getCashItem() == null ? null : eo.getCashItem().getValue());
        entity.setNarrative(eo.getNarrative());
        entity.setCommissionClientName(eo.getCommissionClientName());
        entity.setCommissionClientTel(eo.getCommissionClientTel());
        entity.setPayUnit(eo.getPayUnit());
        entity.setCancelReason(eo.getCancelReason());
        entity.setTerminalId(eo.getTerminalId());
        entity.setTrack2(eo.getTrack2());
        entity.setTrack3(eo.getTrack3());
        entity.setAuthUserId(eo.getAuthUserId());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setUserId(eo.getUserId());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setSubSeqNo(eo.getSubSeqNo());
        entity.setInnerBaseAcctNo(eo.getInnerBaseAcctNo());
        entity.setInnerProdType(eo.getInnerProdType());
        entity.setInnerAcctSeqNo(eo.getInnerAcctSeqNo());
        entity.setInnerAcctCcy(eo.getInnerAcctCcy() == null ? null : eo.getInnerAcctCcy().getValue());
        entity.setInnerInternalKey(eo.getInnerInternalKey());
        entity.setInnerAcctName(eo.getInnerAcctName());
        entity.setInnerClientNo(eo.getInnerClientNo());
        entity.setHangSeqNo(eo.getHangSeqNo());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setOthClientNo(eo.getOthClientNo());
        entity.setBankInOut(eo.getBankInOut() == null ? null : eo.getBankInOut().getValue());
        return entity;
    }

    public static RbDelayTranHistExample eoToEntityExample(RbDelayTranHistEO eo) {
        if (eo == null) {
            return null;
        }
        RbDelayTranHistExample example = new RbDelayTranHistExample();
        RbDelayTranHistExample.Criteria criteria = example.createCriteria();
        if (eo.getSeqNo() != null) criteria.andSeqNoEqualTo(eo.getSeqNo());
        if (eo.getChannelSeqNo() != null) criteria.andChannelSeqNoEqualTo(eo.getChannelSeqNo());
        if (eo.getResSeqNo() != null) criteria.andResSeqNoEqualTo(eo.getResSeqNo());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getCardNo() != null) criteria.andCardNoEqualTo(eo.getCardNo());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getAcctCcy() != null) criteria.andAcctCcyEqualTo(eo.getAcctCcy().getValue());
        if (eo.getAcctSeqNo() != null) criteria.andAcctSeqNoEqualTo(eo.getAcctSeqNo());
        if (eo.getProdType() != null) criteria.andProdTypeEqualTo(eo.getProdType());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getClientName() != null) criteria.andClientNameEqualTo(eo.getClientName());
        if (eo.getOthInternalKey() != null) criteria.andOthInternalKeyEqualTo(eo.getOthInternalKey());
        if (eo.getOthCardNo() != null) criteria.andOthCardNoEqualTo(eo.getOthCardNo());
        if (eo.getOthBaseAcctNo() != null) criteria.andOthBaseAcctNoEqualTo(eo.getOthBaseAcctNo());
        if (eo.getOthAcctCcy() != null) criteria.andOthAcctCcyEqualTo(eo.getOthAcctCcy().getValue());
        if (eo.getOthAcctSeqNo() != null) criteria.andOthAcctSeqNoEqualTo(eo.getOthAcctSeqNo());
        if (eo.getOthProdType() != null) criteria.andOthProdTypeEqualTo(eo.getOthProdType());
        if (eo.getOthAcctName() != null) criteria.andOthAcctNameEqualTo(eo.getOthAcctName());
        if (eo.getOthAcctDesc() != null) criteria.andOthAcctDescEqualTo(eo.getOthAcctDesc());
        if (eo.getSettleCardFlag() != null) criteria.andSettleCardFlagEqualTo(eo.getSettleCardFlag().getValue());
        if (eo.getCcy() != null) criteria.andCcyEqualTo(eo.getCcy().getValue());
        if (eo.getTranMethod() != null) criteria.andTranMethodEqualTo(eo.getTranMethod().getValue());
        if (eo.getSignTimestamp() != null) criteria.andSignTimestampEqualTo(eo.getSignTimestamp());
        if (eo.getTranType() != null) criteria.andTranTypeEqualTo(eo.getTranType().getValue());
        if (eo.getTranAmt() != null) criteria.andTranAmtEqualTo(eo.getTranAmt());
        if (eo.getTranDate() != null) criteria.andTranDateEqualTo(eo.getTranDate());
        if (eo.getTranBranch() != null) criteria.andTranBranchEqualTo(eo.getTranBranch().getValue());
        if (eo.getDocType() != null) criteria.andDocTypeEqualTo(eo.getDocType().getValue());
        if (eo.getPrefix() != null) criteria.andPrefixEqualTo(eo.getPrefix());
        if (eo.getVoucherNo() != null) criteria.andVoucherNoEqualTo(eo.getVoucherNo());
        if (eo.getArrivalStatus() != null) criteria.andArrivalStatusEqualTo(eo.getArrivalStatus().getValue());
        if (eo.getReference() != null) criteria.andReferenceEqualTo(eo.getReference());
        if (eo.getSourceType() != null) criteria.andSourceTypeEqualTo(eo.getSourceType().getValue());
        if (eo.getExchangeTranCode() != null) criteria.andExchangeTranCodeEqualTo(eo.getExchangeTranCode());
        if (eo.getExchangeTranCodet() != null) criteria.andExchangeTranCodetEqualTo(eo.getExchangeTranCodet());
        if (eo.getTranDesc() != null) criteria.andTranDescEqualTo(eo.getTranDesc());
        if (eo.getTranNote() != null) criteria.andTranNoteEqualTo(eo.getTranNote());
        if (eo.getCashItem() != null) criteria.andCashItemEqualTo(eo.getCashItem().getValue());
        if (eo.getNarrative() != null) criteria.andNarrativeEqualTo(eo.getNarrative());
        if (eo.getCommissionClientName() != null) criteria.andCommissionClientNameEqualTo(eo.getCommissionClientName());
        if (eo.getCommissionClientTel() != null) criteria.andCommissionClientTelEqualTo(eo.getCommissionClientTel());
        if (eo.getPayUnit() != null) criteria.andPayUnitEqualTo(eo.getPayUnit());
        if (eo.getCancelReason() != null) criteria.andCancelReasonEqualTo(eo.getCancelReason());
        if (eo.getTerminalId() != null) criteria.andTerminalIdEqualTo(eo.getTerminalId());
        if (eo.getTrack2() != null) criteria.andTrack2EqualTo(eo.getTrack2());
        if (eo.getTrack3() != null) criteria.andTrack3EqualTo(eo.getTrack3());
        if (eo.getAuthUserId() != null) criteria.andAuthUserIdEqualTo(eo.getAuthUserId());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getSubSeqNo() != null) criteria.andSubSeqNoEqualTo(eo.getSubSeqNo());
        if (eo.getInnerBaseAcctNo() != null) criteria.andInnerBaseAcctNoEqualTo(eo.getInnerBaseAcctNo());
        if (eo.getInnerProdType() != null) criteria.andInnerProdTypeEqualTo(eo.getInnerProdType());
        if (eo.getInnerAcctSeqNo() != null) criteria.andInnerAcctSeqNoEqualTo(eo.getInnerAcctSeqNo());
        if (eo.getInnerAcctCcy() != null) criteria.andInnerAcctCcyEqualTo(eo.getInnerAcctCcy().getValue());
        if (eo.getInnerInternalKey() != null) criteria.andInnerInternalKeyEqualTo(eo.getInnerInternalKey());
        if (eo.getInnerAcctName() != null) criteria.andInnerAcctNameEqualTo(eo.getInnerAcctName());
        if (eo.getInnerClientNo() != null) criteria.andInnerClientNoEqualTo(eo.getInnerClientNo());
        if (eo.getHangSeqNo() != null) criteria.andHangSeqNoEqualTo(eo.getHangSeqNo());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getOthClientNo() != null) criteria.andOthClientNoEqualTo(eo.getOthClientNo());
        if (eo.getBankInOut() != null) criteria.andBankInOutEqualTo(eo.getBankInOut().getValue());
        return example;
    }
}