package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbExchangeTranHist;
import com.dcits.deposit.entity.RbExchangeTranHistExample;
import com.dcits.deposit.facade.eo.RbExchangeTranHistEO;
import com.dcits.deposit.enums.BalType;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.BalType;
import com.dcits.deposit.enums.TranType;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.TranType;
import com.dcits.deposit.enums.ExchangeTranStatus;
import com.dcits.deposit.enums.SellBuyInd;
import com.dcits.deposit.enums.QuoteType;
import com.dcits.deposit.enums.RateType;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.BaseQuoteType;
import com.dcits.deposit.enums.BaseRateType;
import com.dcits.deposit.enums.BaseQuoteType;
import com.dcits.deposit.enums.BaseQuoteType;
import com.dcits.deposit.enums.RateType;
import com.dcits.deposit.enums.SourceType;
import com.dcits.deposit.enums.SourceModule;
import com.dcits.deposit.enums.ProfitCenter;
import com.dcits.deposit.enums.UncStatus;
import com.dcits.deposit.enums.Company;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.CouponRateType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.IndividualFlag;

public final class RbExchangeTranHistValueUtil {
    private RbExchangeTranHistValueUtil() {
    }

    public static RbExchangeTranHistEO entityToEo(RbExchangeTranHist entity) {
        if (entity == null) {
            return null;
        }
        RbExchangeTranHistEO eo = new RbExchangeTranHistEO();
        eo.setSeqNo(entity.getSeqNo());
        eo.setCashSeqNo(entity.getCashSeqNo());
        eo.setTaeSubSeqNo(entity.getTaeSubSeqNo());
        eo.setExchangeSeqNo(entity.getExchangeSeqNo());
        eo.setDepositInternalKey(entity.getDepositInternalKey());
        eo.setDepositBaseAcctNo(entity.getDepositBaseAcctNo());
        eo.setDepositAcctSeqNo(entity.getDepositAcctSeqNo());
        eo.setDepositProdType(entity.getDepositProdType());
        eo.setDepositBalanceType(BalType.byValue(entity.getDepositBalanceType()));
        eo.setDepositSeqNo(entity.getDepositSeqNo());
        eo.setWithdrawInternalKey(entity.getWithdrawInternalKey());
        eo.setWithdrawBaseAcctNo(entity.getWithdrawBaseAcctNo());
        eo.setWithdrawAcctCcy(AcctCcy.byValue(entity.getWithdrawAcctCcy()));
        eo.setWithdrawAcctSeqNo(entity.getWithdrawAcctSeqNo());
        eo.setWithdrawProdType(entity.getWithdrawProdType());
        eo.setWithdrawBalanceType(BalType.byValue(entity.getWithdrawBalanceType()));
        eo.setWithdrawSeqNo(entity.getWithdrawSeqNo());
        eo.setClientNo(entity.getClientNo());
        eo.setTranType(TranType.byValue(entity.getTranType()));
        eo.setTranDate(entity.getTranDate());
        eo.setTranBranch(AcctBranch.byValue(entity.getTranBranch()));
        eo.setReversalDate(entity.getReversalDate());
        eo.setReversalTranType(TranType.byValue(entity.getReversalTranType()));
        eo.setExchangeTranStatus(ExchangeTranStatus.byValue(entity.getExchangeTranStatus()));
        eo.setSellBuyInd(SellBuyInd.byValue(entity.getSellBuyInd()));
        eo.setQuoteType(QuoteType.byValue(entity.getQuoteType()));
        eo.setRateType(RateType.byValue(entity.getRateType()));
        eo.setBuyAmount(entity.getBuyAmount());
        eo.setBuyCcy(AcctCcy.byValue(entity.getBuyCcy()));
        eo.setBuyRate(entity.getBuyRate());
        eo.setSellCcy(AcctCcy.byValue(entity.getSellCcy()));
        eo.setSellAmount(entity.getSellAmount());
        eo.setSellRate(entity.getSellRate());
        eo.setExchRate(entity.getExchRate());
        eo.setFloatRate(entity.getFloatRate());
        eo.setBaseQuoteType(BaseQuoteType.byValue(entity.getBaseQuoteType()));
        eo.setBaseRateType(BaseRateType.byValue(entity.getBaseRateType()));
        eo.setBaseRate(entity.getBaseRate());
        eo.setBaseEquivAmt(entity.getBaseEquivAmt());
        eo.setCrossRate(entity.getCrossRate());
        eo.setCrossRateAttr(entity.getCrossRateAttr());
        eo.setUncCrossRate(entity.getUncCrossRate());
        eo.setInnerRate(entity.getInnerRate());
        eo.setChangeBaseEquivAmt(entity.getChangeBaseEquivAmt());
        eo.setChangeCnyAmount(entity.getChangeCnyAmount());
        eo.setChangeRate(entity.getChangeRate());
        eo.setChangeBaseQuoteType(BaseQuoteType.byValue(entity.getChangeBaseQuoteType()));
        eo.setChangeQuoteType(BaseQuoteType.byValue(entity.getChangeQuoteType()));
        eo.setChangeRateType(RateType.byValue(entity.getChangeRateType()));
        eo.setReference(entity.getReference());
        eo.setTraceRefNo(entity.getTraceRefNo());
        eo.setSourceType(SourceType.byValue(entity.getSourceType()));
        eo.setBankSeqNo(entity.getBankSeqNo());
        eo.setRemark(entity.getRemark());
        eo.setSourceModule(SourceModule.byValue(entity.getSourceModule()));
        eo.setTerminalId(entity.getTerminalId());
        eo.setTraceRefCode(entity.getTraceRefCode());
        eo.setApprovalDate(entity.getApprovalDate());
        eo.setValueDate(entity.getValueDate());
        eo.setApprUserId(entity.getApprUserId());
        eo.setApprAuthUserId(entity.getApprAuthUserId());
        eo.setUserId(entity.getUserId());
        eo.setAuthUserId(entity.getAuthUserId());
        eo.setReversalAuthUserId(entity.getReversalAuthUserId());
        eo.setReversalUserId(entity.getReversalUserId());
        eo.setProfitCenter(ProfitCenter.byValue(entity.getProfitCenter()));
        eo.setFcyCtrlIbuncAmt(entity.getFcyCtrlIbuncAmt());
        eo.setUncStatus(UncStatus.byValue(entity.getUncStatus()));
        eo.setIbuncReference(entity.getIbuncReference());
        eo.setObuncReference(entity.getObuncReference());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setBuyUncRate(entity.getBuyUncRate());
        eo.setCountryLoc(IssCountry.byValue(entity.getCountryLoc()));
        eo.setCouponRateType(CouponRateType.byValue(entity.getCouponRateType()));
        eo.setEffectDate(entity.getEffectDate());
        eo.setEffectTime(entity.getEffectTime());
        eo.setFloatPoint(entity.getFloatPoint());
        eo.setMinAmtFlag(IndividualFlag.byValue(entity.getMinAmtFlag()));
        eo.setSellUncRate(entity.getSellUncRate());
        eo.setBranch(AcctBranch.byValue(entity.getBranch()));
        eo.setDocumentId(entity.getDocumentId());
        eo.setDocumentType(DocumentType.byValue(entity.getDocumentType()));
        eo.setAreaCode(entity.getAreaCode());
        eo.setClientName(entity.getClientName());
        eo.setIsIndividual(IndividualFlag.byValue(entity.getIsIndividual()));
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        return eo;
    }

    public static RbExchangeTranHist eoToEntity(RbExchangeTranHistEO eo) {
        if (eo == null) {
            return null;
        }
        RbExchangeTranHist entity = new RbExchangeTranHist();
        entity.setSeqNo(eo.getSeqNo());
        entity.setCashSeqNo(eo.getCashSeqNo());
        entity.setTaeSubSeqNo(eo.getTaeSubSeqNo());
        entity.setExchangeSeqNo(eo.getExchangeSeqNo());
        entity.setDepositInternalKey(eo.getDepositInternalKey());
        entity.setDepositBaseAcctNo(eo.getDepositBaseAcctNo());
        entity.setDepositAcctSeqNo(eo.getDepositAcctSeqNo());
        entity.setDepositProdType(eo.getDepositProdType());
        entity.setDepositBalanceType(eo.getDepositBalanceType() == null ? null : eo.getDepositBalanceType().getValue());
        entity.setDepositSeqNo(eo.getDepositSeqNo());
        entity.setWithdrawInternalKey(eo.getWithdrawInternalKey());
        entity.setWithdrawBaseAcctNo(eo.getWithdrawBaseAcctNo());
        entity.setWithdrawAcctCcy(eo.getWithdrawAcctCcy() == null ? null : eo.getWithdrawAcctCcy().getValue());
        entity.setWithdrawAcctSeqNo(eo.getWithdrawAcctSeqNo());
        entity.setWithdrawProdType(eo.getWithdrawProdType());
        entity.setWithdrawBalanceType(eo.getWithdrawBalanceType() == null ? null : eo.getWithdrawBalanceType().getValue());
        entity.setWithdrawSeqNo(eo.getWithdrawSeqNo());
        entity.setClientNo(eo.getClientNo());
        entity.setTranType(eo.getTranType() == null ? null : eo.getTranType().getValue());
        entity.setTranDate(eo.getTranDate());
        entity.setTranBranch(eo.getTranBranch() == null ? null : eo.getTranBranch().getValue());
        entity.setReversalDate(eo.getReversalDate());
        entity.setReversalTranType(eo.getReversalTranType() == null ? null : eo.getReversalTranType().getValue());
        entity.setExchangeTranStatus(eo.getExchangeTranStatus() == null ? null : eo.getExchangeTranStatus().getValue());
        entity.setSellBuyInd(eo.getSellBuyInd() == null ? null : eo.getSellBuyInd().getValue());
        entity.setQuoteType(eo.getQuoteType() == null ? null : eo.getQuoteType().getValue());
        entity.setRateType(eo.getRateType() == null ? null : eo.getRateType().getValue());
        entity.setBuyAmount(eo.getBuyAmount());
        entity.setBuyCcy(eo.getBuyCcy() == null ? null : eo.getBuyCcy().getValue());
        entity.setBuyRate(eo.getBuyRate());
        entity.setSellCcy(eo.getSellCcy() == null ? null : eo.getSellCcy().getValue());
        entity.setSellAmount(eo.getSellAmount());
        entity.setSellRate(eo.getSellRate());
        entity.setExchRate(eo.getExchRate());
        entity.setFloatRate(eo.getFloatRate());
        entity.setBaseQuoteType(eo.getBaseQuoteType() == null ? null : eo.getBaseQuoteType().getValue());
        entity.setBaseRateType(eo.getBaseRateType() == null ? null : eo.getBaseRateType().getValue());
        entity.setBaseRate(eo.getBaseRate());
        entity.setBaseEquivAmt(eo.getBaseEquivAmt());
        entity.setCrossRate(eo.getCrossRate());
        entity.setCrossRateAttr(eo.getCrossRateAttr());
        entity.setUncCrossRate(eo.getUncCrossRate());
        entity.setInnerRate(eo.getInnerRate());
        entity.setChangeBaseEquivAmt(eo.getChangeBaseEquivAmt());
        entity.setChangeCnyAmount(eo.getChangeCnyAmount());
        entity.setChangeRate(eo.getChangeRate());
        entity.setChangeBaseQuoteType(eo.getChangeBaseQuoteType() == null ? null : eo.getChangeBaseQuoteType().getValue());
        entity.setChangeQuoteType(eo.getChangeQuoteType() == null ? null : eo.getChangeQuoteType().getValue());
        entity.setChangeRateType(eo.getChangeRateType() == null ? null : eo.getChangeRateType().getValue());
        entity.setReference(eo.getReference());
        entity.setTraceRefNo(eo.getTraceRefNo());
        entity.setSourceType(eo.getSourceType() == null ? null : eo.getSourceType().getValue());
        entity.setBankSeqNo(eo.getBankSeqNo());
        entity.setRemark(eo.getRemark());
        entity.setSourceModule(eo.getSourceModule() == null ? null : eo.getSourceModule().getValue());
        entity.setTerminalId(eo.getTerminalId());
        entity.setTraceRefCode(eo.getTraceRefCode());
        entity.setApprovalDate(eo.getApprovalDate());
        entity.setValueDate(eo.getValueDate());
        entity.setApprUserId(eo.getApprUserId());
        entity.setApprAuthUserId(eo.getApprAuthUserId());
        entity.setUserId(eo.getUserId());
        entity.setAuthUserId(eo.getAuthUserId());
        entity.setReversalAuthUserId(eo.getReversalAuthUserId());
        entity.setReversalUserId(eo.getReversalUserId());
        entity.setProfitCenter(eo.getProfitCenter() == null ? null : eo.getProfitCenter().getValue());
        entity.setFcyCtrlIbuncAmt(eo.getFcyCtrlIbuncAmt());
        entity.setUncStatus(eo.getUncStatus() == null ? null : eo.getUncStatus().getValue());
        entity.setIbuncReference(eo.getIbuncReference());
        entity.setObuncReference(eo.getObuncReference());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setBuyUncRate(eo.getBuyUncRate());
        entity.setCountryLoc(eo.getCountryLoc() == null ? null : eo.getCountryLoc().getValue());
        entity.setCouponRateType(eo.getCouponRateType() == null ? null : eo.getCouponRateType().getValue());
        entity.setEffectDate(eo.getEffectDate());
        entity.setEffectTime(eo.getEffectTime());
        entity.setFloatPoint(eo.getFloatPoint());
        entity.setMinAmtFlag(eo.getMinAmtFlag() == null ? null : eo.getMinAmtFlag().getValue());
        entity.setSellUncRate(eo.getSellUncRate());
        entity.setBranch(eo.getBranch() == null ? null : eo.getBranch().getValue());
        entity.setDocumentId(eo.getDocumentId());
        entity.setDocumentType(eo.getDocumentType() == null ? null : eo.getDocumentType().getValue());
        entity.setAreaCode(eo.getAreaCode());
        entity.setClientName(eo.getClientName());
        entity.setIsIndividual(eo.getIsIndividual() == null ? null : eo.getIsIndividual().getValue());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        return entity;
    }

    public static RbExchangeTranHistExample eoToEntityExample(RbExchangeTranHistEO eo) {
        if (eo == null) {
            return null;
        }
        RbExchangeTranHistExample example = new RbExchangeTranHistExample();
        RbExchangeTranHistExample.Criteria criteria = example.createCriteria();
        if (eo.getSeqNo() != null) criteria.andSeqNoEqualTo(eo.getSeqNo());
        if (eo.getCashSeqNo() != null) criteria.andCashSeqNoEqualTo(eo.getCashSeqNo());
        if (eo.getTaeSubSeqNo() != null) criteria.andTaeSubSeqNoEqualTo(eo.getTaeSubSeqNo());
        if (eo.getExchangeSeqNo() != null) criteria.andExchangeSeqNoEqualTo(eo.getExchangeSeqNo());
        if (eo.getDepositInternalKey() != null) criteria.andDepositInternalKeyEqualTo(eo.getDepositInternalKey());
        if (eo.getDepositBaseAcctNo() != null) criteria.andDepositBaseAcctNoEqualTo(eo.getDepositBaseAcctNo());
        if (eo.getDepositAcctSeqNo() != null) criteria.andDepositAcctSeqNoEqualTo(eo.getDepositAcctSeqNo());
        if (eo.getDepositProdType() != null) criteria.andDepositProdTypeEqualTo(eo.getDepositProdType());
        if (eo.getDepositBalanceType() != null) criteria.andDepositBalanceTypeEqualTo(eo.getDepositBalanceType().getValue());
        if (eo.getDepositSeqNo() != null) criteria.andDepositSeqNoEqualTo(eo.getDepositSeqNo());
        if (eo.getWithdrawInternalKey() != null) criteria.andWithdrawInternalKeyEqualTo(eo.getWithdrawInternalKey());
        if (eo.getWithdrawBaseAcctNo() != null) criteria.andWithdrawBaseAcctNoEqualTo(eo.getWithdrawBaseAcctNo());
        if (eo.getWithdrawAcctCcy() != null) criteria.andWithdrawAcctCcyEqualTo(eo.getWithdrawAcctCcy().getValue());
        if (eo.getWithdrawAcctSeqNo() != null) criteria.andWithdrawAcctSeqNoEqualTo(eo.getWithdrawAcctSeqNo());
        if (eo.getWithdrawProdType() != null) criteria.andWithdrawProdTypeEqualTo(eo.getWithdrawProdType());
        if (eo.getWithdrawBalanceType() != null) criteria.andWithdrawBalanceTypeEqualTo(eo.getWithdrawBalanceType().getValue());
        if (eo.getWithdrawSeqNo() != null) criteria.andWithdrawSeqNoEqualTo(eo.getWithdrawSeqNo());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getTranType() != null) criteria.andTranTypeEqualTo(eo.getTranType().getValue());
        if (eo.getTranDate() != null) criteria.andTranDateEqualTo(eo.getTranDate());
        if (eo.getTranBranch() != null) criteria.andTranBranchEqualTo(eo.getTranBranch().getValue());
        if (eo.getReversalDate() != null) criteria.andReversalDateEqualTo(eo.getReversalDate());
        if (eo.getReversalTranType() != null) criteria.andReversalTranTypeEqualTo(eo.getReversalTranType().getValue());
        if (eo.getExchangeTranStatus() != null) criteria.andExchangeTranStatusEqualTo(eo.getExchangeTranStatus().getValue());
        if (eo.getSellBuyInd() != null) criteria.andSellBuyIndEqualTo(eo.getSellBuyInd().getValue());
        if (eo.getQuoteType() != null) criteria.andQuoteTypeEqualTo(eo.getQuoteType().getValue());
        if (eo.getRateType() != null) criteria.andRateTypeEqualTo(eo.getRateType().getValue());
        if (eo.getBuyAmount() != null) criteria.andBuyAmountEqualTo(eo.getBuyAmount());
        if (eo.getBuyCcy() != null) criteria.andBuyCcyEqualTo(eo.getBuyCcy().getValue());
        if (eo.getBuyRate() != null) criteria.andBuyRateEqualTo(eo.getBuyRate());
        if (eo.getSellCcy() != null) criteria.andSellCcyEqualTo(eo.getSellCcy().getValue());
        if (eo.getSellAmount() != null) criteria.andSellAmountEqualTo(eo.getSellAmount());
        if (eo.getSellRate() != null) criteria.andSellRateEqualTo(eo.getSellRate());
        if (eo.getExchRate() != null) criteria.andExchRateEqualTo(eo.getExchRate());
        if (eo.getFloatRate() != null) criteria.andFloatRateEqualTo(eo.getFloatRate());
        if (eo.getBaseQuoteType() != null) criteria.andBaseQuoteTypeEqualTo(eo.getBaseQuoteType().getValue());
        if (eo.getBaseRateType() != null) criteria.andBaseRateTypeEqualTo(eo.getBaseRateType().getValue());
        if (eo.getBaseRate() != null) criteria.andBaseRateEqualTo(eo.getBaseRate());
        if (eo.getBaseEquivAmt() != null) criteria.andBaseEquivAmtEqualTo(eo.getBaseEquivAmt());
        if (eo.getCrossRate() != null) criteria.andCrossRateEqualTo(eo.getCrossRate());
        if (eo.getCrossRateAttr() != null) criteria.andCrossRateAttrEqualTo(eo.getCrossRateAttr());
        if (eo.getUncCrossRate() != null) criteria.andUncCrossRateEqualTo(eo.getUncCrossRate());
        if (eo.getInnerRate() != null) criteria.andInnerRateEqualTo(eo.getInnerRate());
        if (eo.getChangeBaseEquivAmt() != null) criteria.andChangeBaseEquivAmtEqualTo(eo.getChangeBaseEquivAmt());
        if (eo.getChangeCnyAmount() != null) criteria.andChangeCnyAmountEqualTo(eo.getChangeCnyAmount());
        if (eo.getChangeRate() != null) criteria.andChangeRateEqualTo(eo.getChangeRate());
        if (eo.getChangeBaseQuoteType() != null) criteria.andChangeBaseQuoteTypeEqualTo(eo.getChangeBaseQuoteType().getValue());
        if (eo.getChangeQuoteType() != null) criteria.andChangeQuoteTypeEqualTo(eo.getChangeQuoteType().getValue());
        if (eo.getChangeRateType() != null) criteria.andChangeRateTypeEqualTo(eo.getChangeRateType().getValue());
        if (eo.getReference() != null) criteria.andReferenceEqualTo(eo.getReference());
        if (eo.getTraceRefNo() != null) criteria.andTraceRefNoEqualTo(eo.getTraceRefNo());
        if (eo.getSourceType() != null) criteria.andSourceTypeEqualTo(eo.getSourceType().getValue());
        if (eo.getBankSeqNo() != null) criteria.andBankSeqNoEqualTo(eo.getBankSeqNo());
        if (eo.getRemark() != null) criteria.andRemarkEqualTo(eo.getRemark());
        if (eo.getSourceModule() != null) criteria.andSourceModuleEqualTo(eo.getSourceModule().getValue());
        if (eo.getTerminalId() != null) criteria.andTerminalIdEqualTo(eo.getTerminalId());
        if (eo.getTraceRefCode() != null) criteria.andTraceRefCodeEqualTo(eo.getTraceRefCode());
        if (eo.getApprovalDate() != null) criteria.andApprovalDateEqualTo(eo.getApprovalDate());
        if (eo.getValueDate() != null) criteria.andValueDateEqualTo(eo.getValueDate());
        if (eo.getApprUserId() != null) criteria.andApprUserIdEqualTo(eo.getApprUserId());
        if (eo.getApprAuthUserId() != null) criteria.andApprAuthUserIdEqualTo(eo.getApprAuthUserId());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getAuthUserId() != null) criteria.andAuthUserIdEqualTo(eo.getAuthUserId());
        if (eo.getReversalAuthUserId() != null) criteria.andReversalAuthUserIdEqualTo(eo.getReversalAuthUserId());
        if (eo.getReversalUserId() != null) criteria.andReversalUserIdEqualTo(eo.getReversalUserId());
        if (eo.getProfitCenter() != null) criteria.andProfitCenterEqualTo(eo.getProfitCenter().getValue());
        if (eo.getFcyCtrlIbuncAmt() != null) criteria.andFcyCtrlIbuncAmtEqualTo(eo.getFcyCtrlIbuncAmt());
        if (eo.getUncStatus() != null) criteria.andUncStatusEqualTo(eo.getUncStatus().getValue());
        if (eo.getIbuncReference() != null) criteria.andIbuncReferenceEqualTo(eo.getIbuncReference());
        if (eo.getObuncReference() != null) criteria.andObuncReferenceEqualTo(eo.getObuncReference());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getBuyUncRate() != null) criteria.andBuyUncRateEqualTo(eo.getBuyUncRate());
        if (eo.getCountryLoc() != null) criteria.andCountryLocEqualTo(eo.getCountryLoc().getValue());
        if (eo.getCouponRateType() != null) criteria.andCouponRateTypeEqualTo(eo.getCouponRateType().getValue());
        if (eo.getEffectDate() != null) criteria.andEffectDateEqualTo(eo.getEffectDate());
        if (eo.getEffectTime() != null) criteria.andEffectTimeEqualTo(eo.getEffectTime());
        if (eo.getFloatPoint() != null) criteria.andFloatPointEqualTo(eo.getFloatPoint());
        if (eo.getMinAmtFlag() != null) criteria.andMinAmtFlagEqualTo(eo.getMinAmtFlag().getValue());
        if (eo.getSellUncRate() != null) criteria.andSellUncRateEqualTo(eo.getSellUncRate());
        if (eo.getBranch() != null) criteria.andBranchEqualTo(eo.getBranch().getValue());
        if (eo.getDocumentId() != null) criteria.andDocumentIdEqualTo(eo.getDocumentId());
        if (eo.getDocumentType() != null) criteria.andDocumentTypeEqualTo(eo.getDocumentType().getValue());
        if (eo.getAreaCode() != null) criteria.andAreaCodeEqualTo(eo.getAreaCode());
        if (eo.getClientName() != null) criteria.andClientNameEqualTo(eo.getClientName());
        if (eo.getIsIndividual() != null) criteria.andIsIndividualEqualTo(eo.getIsIndividual().getValue());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        return example;
    }
}