package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbRestraints;
import com.dcits.deposit.entity.RbRestraintsExample;
import com.dcits.deposit.facade.eo.RbRestraintsEO;
import com.dcits.deposit.enums.AcctInternalKeyType;
import com.dcits.deposit.enums.RestraintType;
import com.dcits.deposit.enums.TermType;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.RestraintSource;
import com.dcits.deposit.enums.ResAcctRange;
import com.dcits.deposit.enums.RestraintsStatus;
import com.dcits.deposit.enums.SourceModule;
import com.dcits.deposit.enums.RestraintLevel;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.Company;

public final class RbRestraintsValueUtil {
    private RbRestraintsValueUtil() {
    }

    public static RbRestraintsEO entityToEo(RbRestraints entity) {
        if (entity == null) {
            return null;
        }
        RbRestraintsEO eo = new RbRestraintsEO();
        eo.setResSeqNo(entity.getResSeqNo());
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setInternalKey(entity.getInternalKey());
        eo.setAcctInternalKeyType(AcctInternalKeyType.byValue(entity.getAcctInternalKeyType()));
        eo.setClientNo(entity.getClientNo());
        eo.setRestraintType(RestraintType.byValue(entity.getRestraintType()));
        eo.setChannelDate(entity.getChannelDate());
        eo.setChannelSeqNo(entity.getChannelSeqNo());
        eo.setStartDate(entity.getStartDate());
        eo.setEndDate(entity.getEndDate());
        eo.setRestraintEndTime(entity.getRestraintEndTime());
        eo.setTerm(entity.getTerm());
        eo.setTermType(TermType.byValue(entity.getTermType()));
        eo.setPledgedAmt(entity.getPledgedAmt());
        eo.setTranAmt(entity.getTranAmt());
        eo.setWaitSeq(entity.getWaitSeq());
        eo.setReference(entity.getReference());
        eo.setTranBranch(AcctBranch.byValue(entity.getTranBranch()));
        eo.setTranDate(entity.getTranDate());
        eo.setSettlementDate(entity.getSettlementDate());
        eo.setJudiciaryDocumentType(DocumentType.byValue(entity.getJudiciaryDocumentType()));
        eo.setJudiciaryDocumentType2(DocumentType.byValue(entity.getJudiciaryDocumentType2()));
        eo.setJudiciaryOthDocumentType(DocumentType.byValue(entity.getJudiciaryOthDocumentType()));
        eo.setJudiciaryOthDocumentType2(DocumentType.byValue(entity.getJudiciaryOthDocumentType2()));
        eo.setDeductionJudiciaryName(entity.getDeductionJudiciaryName());
        eo.setDeductionLawNo(entity.getDeductionLawNo());
        eo.setRestraintSource(RestraintSource.byValue(entity.getRestraintSource()));
        eo.setJudiciaryDocumentId(entity.getJudiciaryDocumentId());
        eo.setJudiciaryDocumentId2(entity.getJudiciaryDocumentId2());
        eo.setJudiciaryOthDocumentId(entity.getJudiciaryOthDocumentId());
        eo.setJudiciaryOthDocumentId2(entity.getJudiciaryOthDocumentId2());
        eo.setReleaseJudiciaryName(entity.getReleaseJudiciaryName());
        eo.setReleaseLawNo(entity.getReleaseLawNo());
        eo.setRestraintJudiciaryName(entity.getRestraintJudiciaryName());
        eo.setResLawNo(entity.getResLawNo());
        eo.setResAcctRange(ResAcctRange.byValue(entity.getResAcctRange()));
        eo.setResPriority(entity.getResPriority());
        eo.setRestraintsStatus(RestraintsStatus.byValue(entity.getRestraintsStatus()));
        eo.setSourceModule(SourceModule.byValue(entity.getSourceModule()));
        eo.setRestraintLevel(RestraintLevel.byValue(entity.getRestraintLevel()));
        eo.setUnderLien(IndividualFlag.byValue(entity.getUnderLien()));
        eo.setReserveFlag(IndividualFlag.byValue(entity.getReserveFlag()));
        eo.setPreFrozenFlag(IndividualFlag.byValue(entity.getPreFrozenFlag()));
        eo.setAhBuFlag(IndividualFlag.byValue(entity.getAhBuFlag()));
        eo.setContinueFreezeFlag(IndividualFlag.byValue(entity.getContinueFreezeFlag()));
        eo.setJudiciaryOfficerName(entity.getJudiciaryOfficerName());
        eo.setJudiciaryOthOfficerName(entity.getJudiciaryOthOfficerName());
        eo.setThawDocumentId(entity.getThawDocumentId());
        eo.setThawDocumentId2(entity.getThawDocumentId2());
        eo.setThawOfficerName(entity.getThawOfficerName());
        eo.setThawOthDocumentId(entity.getThawOthDocumentId());
        eo.setThawOthDocumentId2(entity.getThawOthDocumentId2());
        eo.setThawOthDocumentType(DocumentType.byValue(entity.getThawOthDocumentType()));
        eo.setThawOthDocumentType2(DocumentType.byValue(entity.getThawOthDocumentType2()));
        eo.setThawOthOfficerName(entity.getThawOthOfficerName());
        eo.setThawDocumentType2(DocumentType.byValue(entity.getThawDocumentType2()));
        eo.setThawDocumentType(DocumentType.byValue(entity.getThawDocumentType()));
        eo.setBusinessApplicationId(entity.getBusinessApplicationId());
        eo.setOriginalApplicationId(entity.getOriginalApplicationId());
        eo.setDeductionLawType(entity.getDeductionLawType());
        eo.setRemark(entity.getRemark());
        eo.setNarrative(entity.getNarrative());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setUserId(entity.getUserId());
        eo.setAuthUserId(entity.getAuthUserId());
        eo.setProgramId(entity.getProgramId());
        eo.setLastChangeUserId(entity.getLastChangeUserId());
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setTranTimestamp(entity.getTranTimestamp());
        return eo;
    }

    public static RbRestraints eoToEntity(RbRestraintsEO eo) {
        if (eo == null) {
            return null;
        }
        RbRestraints entity = new RbRestraints();
        entity.setResSeqNo(eo.getResSeqNo());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setInternalKey(eo.getInternalKey());
        entity.setAcctInternalKeyType(eo.getAcctInternalKeyType() == null ? null : eo.getAcctInternalKeyType().getValue());
        entity.setClientNo(eo.getClientNo());
        entity.setRestraintType(eo.getRestraintType() == null ? null : eo.getRestraintType().getValue());
        entity.setChannelDate(eo.getChannelDate());
        entity.setChannelSeqNo(eo.getChannelSeqNo());
        entity.setStartDate(eo.getStartDate());
        entity.setEndDate(eo.getEndDate());
        entity.setRestraintEndTime(eo.getRestraintEndTime());
        entity.setTerm(eo.getTerm());
        entity.setTermType(eo.getTermType() == null ? null : eo.getTermType().getValue());
        entity.setPledgedAmt(eo.getPledgedAmt());
        entity.setTranAmt(eo.getTranAmt());
        entity.setWaitSeq(eo.getWaitSeq());
        entity.setReference(eo.getReference());
        entity.setTranBranch(eo.getTranBranch() == null ? null : eo.getTranBranch().getValue());
        entity.setTranDate(eo.getTranDate());
        entity.setSettlementDate(eo.getSettlementDate());
        entity.setJudiciaryDocumentType(eo.getJudiciaryDocumentType() == null ? null : eo.getJudiciaryDocumentType().getValue());
        entity.setJudiciaryDocumentType2(eo.getJudiciaryDocumentType2() == null ? null : eo.getJudiciaryDocumentType2().getValue());
        entity.setJudiciaryOthDocumentType(eo.getJudiciaryOthDocumentType() == null ? null : eo.getJudiciaryOthDocumentType().getValue());
        entity.setJudiciaryOthDocumentType2(eo.getJudiciaryOthDocumentType2() == null ? null : eo.getJudiciaryOthDocumentType2().getValue());
        entity.setDeductionJudiciaryName(eo.getDeductionJudiciaryName());
        entity.setDeductionLawNo(eo.getDeductionLawNo());
        entity.setRestraintSource(eo.getRestraintSource() == null ? null : eo.getRestraintSource().getValue());
        entity.setJudiciaryDocumentId(eo.getJudiciaryDocumentId());
        entity.setJudiciaryDocumentId2(eo.getJudiciaryDocumentId2());
        entity.setJudiciaryOthDocumentId(eo.getJudiciaryOthDocumentId());
        entity.setJudiciaryOthDocumentId2(eo.getJudiciaryOthDocumentId2());
        entity.setReleaseJudiciaryName(eo.getReleaseJudiciaryName());
        entity.setReleaseLawNo(eo.getReleaseLawNo());
        entity.setRestraintJudiciaryName(eo.getRestraintJudiciaryName());
        entity.setResLawNo(eo.getResLawNo());
        entity.setResAcctRange(eo.getResAcctRange() == null ? null : eo.getResAcctRange().getValue());
        entity.setResPriority(eo.getResPriority());
        entity.setRestraintsStatus(eo.getRestraintsStatus() == null ? null : eo.getRestraintsStatus().getValue());
        entity.setSourceModule(eo.getSourceModule() == null ? null : eo.getSourceModule().getValue());
        entity.setRestraintLevel(eo.getRestraintLevel() == null ? null : eo.getRestraintLevel().getValue());
        entity.setUnderLien(eo.getUnderLien() == null ? null : eo.getUnderLien().getValue());
        entity.setReserveFlag(eo.getReserveFlag() == null ? null : eo.getReserveFlag().getValue());
        entity.setPreFrozenFlag(eo.getPreFrozenFlag() == null ? null : eo.getPreFrozenFlag().getValue());
        entity.setAhBuFlag(eo.getAhBuFlag() == null ? null : eo.getAhBuFlag().getValue());
        entity.setContinueFreezeFlag(eo.getContinueFreezeFlag() == null ? null : eo.getContinueFreezeFlag().getValue());
        entity.setJudiciaryOfficerName(eo.getJudiciaryOfficerName());
        entity.setJudiciaryOthOfficerName(eo.getJudiciaryOthOfficerName());
        entity.setThawDocumentId(eo.getThawDocumentId());
        entity.setThawDocumentId2(eo.getThawDocumentId2());
        entity.setThawOfficerName(eo.getThawOfficerName());
        entity.setThawOthDocumentId(eo.getThawOthDocumentId());
        entity.setThawOthDocumentId2(eo.getThawOthDocumentId2());
        entity.setThawOthDocumentType(eo.getThawOthDocumentType() == null ? null : eo.getThawOthDocumentType().getValue());
        entity.setThawOthDocumentType2(eo.getThawOthDocumentType2() == null ? null : eo.getThawOthDocumentType2().getValue());
        entity.setThawOthOfficerName(eo.getThawOthOfficerName());
        entity.setThawDocumentType2(eo.getThawDocumentType2() == null ? null : eo.getThawDocumentType2().getValue());
        entity.setThawDocumentType(eo.getThawDocumentType() == null ? null : eo.getThawDocumentType().getValue());
        entity.setBusinessApplicationId(eo.getBusinessApplicationId());
        entity.setOriginalApplicationId(eo.getOriginalApplicationId());
        entity.setDeductionLawType(eo.getDeductionLawType());
        entity.setRemark(eo.getRemark());
        entity.setNarrative(eo.getNarrative());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setUserId(eo.getUserId());
        entity.setAuthUserId(eo.getAuthUserId());
        entity.setProgramId(eo.getProgramId());
        entity.setLastChangeUserId(eo.getLastChangeUserId());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setTranTimestamp(eo.getTranTimestamp());
        return entity;
    }

    public static RbRestraintsExample eoToEntityExample(RbRestraintsEO eo) {
        if (eo == null) {
            return null;
        }
        RbRestraintsExample example = new RbRestraintsExample();
        RbRestraintsExample.Criteria criteria = example.createCriteria();
        if (eo.getResSeqNo() != null) criteria.andResSeqNoEqualTo(eo.getResSeqNo());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getAcctInternalKeyType() != null) criteria.andAcctInternalKeyTypeEqualTo(eo.getAcctInternalKeyType().getValue());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getRestraintType() != null) criteria.andRestraintTypeEqualTo(eo.getRestraintType().getValue());
        if (eo.getChannelDate() != null) criteria.andChannelDateEqualTo(eo.getChannelDate());
        if (eo.getChannelSeqNo() != null) criteria.andChannelSeqNoEqualTo(eo.getChannelSeqNo());
        if (eo.getStartDate() != null) criteria.andStartDateEqualTo(eo.getStartDate());
        if (eo.getEndDate() != null) criteria.andEndDateEqualTo(eo.getEndDate());
        if (eo.getRestraintEndTime() != null) criteria.andRestraintEndTimeEqualTo(eo.getRestraintEndTime());
        if (eo.getTerm() != null) criteria.andTermEqualTo(eo.getTerm());
        if (eo.getTermType() != null) criteria.andTermTypeEqualTo(eo.getTermType().getValue());
        if (eo.getPledgedAmt() != null) criteria.andPledgedAmtEqualTo(eo.getPledgedAmt());
        if (eo.getTranAmt() != null) criteria.andTranAmtEqualTo(eo.getTranAmt());
        if (eo.getWaitSeq() != null) criteria.andWaitSeqEqualTo(eo.getWaitSeq());
        if (eo.getReference() != null) criteria.andReferenceEqualTo(eo.getReference());
        if (eo.getTranBranch() != null) criteria.andTranBranchEqualTo(eo.getTranBranch().getValue());
        if (eo.getTranDate() != null) criteria.andTranDateEqualTo(eo.getTranDate());
        if (eo.getSettlementDate() != null) criteria.andSettlementDateEqualTo(eo.getSettlementDate());
        if (eo.getJudiciaryDocumentType() != null) criteria.andJudiciaryDocumentTypeEqualTo(eo.getJudiciaryDocumentType().getValue());
        if (eo.getJudiciaryDocumentType2() != null) criteria.andJudiciaryDocumentType2EqualTo(eo.getJudiciaryDocumentType2().getValue());
        if (eo.getJudiciaryOthDocumentType() != null) criteria.andJudiciaryOthDocumentTypeEqualTo(eo.getJudiciaryOthDocumentType().getValue());
        if (eo.getJudiciaryOthDocumentType2() != null) criteria.andJudiciaryOthDocumentType2EqualTo(eo.getJudiciaryOthDocumentType2().getValue());
        if (eo.getDeductionJudiciaryName() != null) criteria.andDeductionJudiciaryNameEqualTo(eo.getDeductionJudiciaryName());
        if (eo.getDeductionLawNo() != null) criteria.andDeductionLawNoEqualTo(eo.getDeductionLawNo());
        if (eo.getRestraintSource() != null) criteria.andRestraintSourceEqualTo(eo.getRestraintSource().getValue());
        if (eo.getJudiciaryDocumentId() != null) criteria.andJudiciaryDocumentIdEqualTo(eo.getJudiciaryDocumentId());
        if (eo.getJudiciaryDocumentId2() != null) criteria.andJudiciaryDocumentId2EqualTo(eo.getJudiciaryDocumentId2());
        if (eo.getJudiciaryOthDocumentId() != null) criteria.andJudiciaryOthDocumentIdEqualTo(eo.getJudiciaryOthDocumentId());
        if (eo.getJudiciaryOthDocumentId2() != null) criteria.andJudiciaryOthDocumentId2EqualTo(eo.getJudiciaryOthDocumentId2());
        if (eo.getReleaseJudiciaryName() != null) criteria.andReleaseJudiciaryNameEqualTo(eo.getReleaseJudiciaryName());
        if (eo.getReleaseLawNo() != null) criteria.andReleaseLawNoEqualTo(eo.getReleaseLawNo());
        if (eo.getRestraintJudiciaryName() != null) criteria.andRestraintJudiciaryNameEqualTo(eo.getRestraintJudiciaryName());
        if (eo.getResLawNo() != null) criteria.andResLawNoEqualTo(eo.getResLawNo());
        if (eo.getResAcctRange() != null) criteria.andResAcctRangeEqualTo(eo.getResAcctRange().getValue());
        if (eo.getResPriority() != null) criteria.andResPriorityEqualTo(eo.getResPriority());
        if (eo.getRestraintsStatus() != null) criteria.andRestraintsStatusEqualTo(eo.getRestraintsStatus().getValue());
        if (eo.getSourceModule() != null) criteria.andSourceModuleEqualTo(eo.getSourceModule().getValue());
        if (eo.getRestraintLevel() != null) criteria.andRestraintLevelEqualTo(eo.getRestraintLevel().getValue());
        if (eo.getUnderLien() != null) criteria.andUnderLienEqualTo(eo.getUnderLien().getValue());
        if (eo.getReserveFlag() != null) criteria.andReserveFlagEqualTo(eo.getReserveFlag().getValue());
        if (eo.getPreFrozenFlag() != null) criteria.andPreFrozenFlagEqualTo(eo.getPreFrozenFlag().getValue());
        if (eo.getAhBuFlag() != null) criteria.andAhBuFlagEqualTo(eo.getAhBuFlag().getValue());
        if (eo.getContinueFreezeFlag() != null) criteria.andContinueFreezeFlagEqualTo(eo.getContinueFreezeFlag().getValue());
        if (eo.getJudiciaryOfficerName() != null) criteria.andJudiciaryOfficerNameEqualTo(eo.getJudiciaryOfficerName());
        if (eo.getJudiciaryOthOfficerName() != null) criteria.andJudiciaryOthOfficerNameEqualTo(eo.getJudiciaryOthOfficerName());
        if (eo.getThawDocumentId() != null) criteria.andThawDocumentIdEqualTo(eo.getThawDocumentId());
        if (eo.getThawDocumentId2() != null) criteria.andThawDocumentId2EqualTo(eo.getThawDocumentId2());
        if (eo.getThawOfficerName() != null) criteria.andThawOfficerNameEqualTo(eo.getThawOfficerName());
        if (eo.getThawOthDocumentId() != null) criteria.andThawOthDocumentIdEqualTo(eo.getThawOthDocumentId());
        if (eo.getThawOthDocumentId2() != null) criteria.andThawOthDocumentId2EqualTo(eo.getThawOthDocumentId2());
        if (eo.getThawOthDocumentType() != null) criteria.andThawOthDocumentTypeEqualTo(eo.getThawOthDocumentType().getValue());
        if (eo.getThawOthDocumentType2() != null) criteria.andThawOthDocumentType2EqualTo(eo.getThawOthDocumentType2().getValue());
        if (eo.getThawOthOfficerName() != null) criteria.andThawOthOfficerNameEqualTo(eo.getThawOthOfficerName());
        if (eo.getThawDocumentType2() != null) criteria.andThawDocumentType2EqualTo(eo.getThawDocumentType2().getValue());
        if (eo.getThawDocumentType() != null) criteria.andThawDocumentTypeEqualTo(eo.getThawDocumentType().getValue());
        if (eo.getBusinessApplicationId() != null) criteria.andBusinessApplicationIdEqualTo(eo.getBusinessApplicationId());
        if (eo.getOriginalApplicationId() != null) criteria.andOriginalApplicationIdEqualTo(eo.getOriginalApplicationId());
        if (eo.getDeductionLawType() != null) criteria.andDeductionLawTypeEqualTo(eo.getDeductionLawType());
        if (eo.getRemark() != null) criteria.andRemarkEqualTo(eo.getRemark());
        if (eo.getNarrative() != null) criteria.andNarrativeEqualTo(eo.getNarrative());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getAuthUserId() != null) criteria.andAuthUserIdEqualTo(eo.getAuthUserId());
        if (eo.getProgramId() != null) criteria.andProgramIdEqualTo(eo.getProgramId());
        if (eo.getLastChangeUserId() != null) criteria.andLastChangeUserIdEqualTo(eo.getLastChangeUserId());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        return example;
    }
}