package com.dcits.deposit.service.utils;

import com.dcits.deposit.entity.RbTranHist;
import com.dcits.deposit.entity.RbTranHistExample;
import com.dcits.deposit.facade.eo.RbTranHistEO;
import com.dcits.deposit.enums.SourceType;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctClass;
import com.dcits.deposit.enums.AcctStatus;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AcctTranFlag;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.CrDrInd;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.TranType;
import com.dcits.deposit.enums.TranCategory;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctBranch;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.AcctCcy;
import com.dcits.deposit.enums.DocType;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.ClientType;
import com.dcits.deposit.enums.BusinessUnit;
import com.dcits.deposit.enums.CashItem;
import com.dcits.deposit.enums.TranStatus;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AmtCalcType;
import com.dcits.deposit.enums.SourceType;
import com.dcits.deposit.enums.AmtType;
import com.dcits.deposit.enums.BalType;
import com.dcits.deposit.enums.FromRateFlag;
import com.dcits.deposit.enums.FromRateFlag;
import com.dcits.deposit.enums.FinType;
import com.dcits.deposit.enums.QuoteType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.MediumType;
import com.dcits.deposit.enums.SourceModule;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.RateType;
import com.dcits.deposit.enums.TranMethod;
import com.dcits.deposit.enums.WithdrawalType;
import com.dcits.deposit.enums.OthBranchRegionalismCode;
import com.dcits.deposit.enums.OthBranchRegionalismCode;
import com.dcits.deposit.enums.DocumentType;
import com.dcits.deposit.enums.QuoteType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.ProfitCenter;
import com.dcits.deposit.enums.SourceModule;
import com.dcits.deposit.enums.TranType;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.AccountingStatus;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.Company;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.CashUseRemark;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.CashSourceRemark;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.TellerTerminalType;
import com.dcits.deposit.enums.ApprIndicator;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.RemainTerm;
import com.dcits.deposit.enums.TellerTerminalType;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.IssCountry;
import com.dcits.deposit.enums.IndividualFlag;
import com.dcits.deposit.enums.SourceModule;

public final class RbTranHistValueUtil {
    private RbTranHistValueUtil() {
    }

    public static RbTranHistEO entityToEo(RbTranHist entity) {
        if (entity == null) {
            return null;
        }
        RbTranHistEO eo = new RbTranHistEO();
        eo.setSeqNo(entity.getSeqNo());
        eo.setChannelSeqNo(entity.getChannelSeqNo());
        eo.setSubSeqNo(entity.getSubSeqNo());
        eo.setTaeSubSeqNo(entity.getTaeSubSeqNo());
        eo.setSourceType(SourceType.byValue(entity.getSourceType()));
        eo.setReference(entity.getReference());
        eo.setClientNo(entity.getClientNo());
        eo.setInternalKey(entity.getInternalKey());
        eo.setBaseAcctNo(entity.getBaseAcctNo());
        eo.setProdType(entity.getProdType());
        eo.setAcctCcy(AcctCcy.byValue(entity.getAcctCcy()));
        eo.setAcctSeqNo(entity.getAcctSeqNo());
        eo.setSubAcctNo(entity.getSubAcctNo());
        eo.setAcctClass(AcctClass.byValue(entity.getAcctClass()));
        eo.setAcctStatus(AcctStatus.byValue(entity.getAcctStatus()));
        eo.setAcctRealFlag(IndividualFlag.byValue(entity.getAcctRealFlag()));
        eo.setAcctTranFlag(AcctTranFlag.byValue(entity.getAcctTranFlag()));
        eo.setAcctDesc(entity.getAcctDesc());
        eo.setAcctBranch(AcctBranch.byValue(entity.getAcctBranch()));
        eo.setEventType(entity.getEventType());
        eo.setTranDate(entity.getTranDate());
        eo.setTranBranch(AcctBranch.byValue(entity.getTranBranch()));
        eo.setCrDrInd(CrDrInd.byValue(entity.getCrDrInd()));
        eo.setCcy(AcctCcy.byValue(entity.getCcy()));
        eo.setTranType(TranType.byValue(entity.getTranType()));
        eo.setTranDesc(entity.getTranDesc());
        eo.setPreviousBalAmt(entity.getPreviousBalAmt());
        eo.setTranAmt(entity.getTranAmt());
        eo.setActualBal(entity.getActualBal());
        eo.setTranCategory(TranCategory.byValue(entity.getTranCategory()));
        eo.setGlCode(entity.getGlCode());
        eo.setOthReference(entity.getOthReference());
        eo.setOthInternalKey(entity.getOthInternalKey());
        eo.setOthBaseAcctNo(entity.getOthBaseAcctNo());
        eo.setOthAcctCcy(AcctCcy.byValue(entity.getOthAcctCcy()));
        eo.setOthAcctSeqNo(entity.getOthAcctSeqNo());
        eo.setFhSeqNo(entity.getFhSeqNo());
        eo.setOthProdType(entity.getOthProdType());
        eo.setOthAcctDesc(entity.getOthAcctDesc());
        eo.setOthBankCode(entity.getOthBankCode());
        eo.setOthBankName(entity.getOthBankName());
        eo.setOthBranch(AcctBranch.byValue(entity.getOthBranch()));
        eo.setOthRealBankCode(entity.getOthRealBankCode());
        eo.setOthRealBankName(entity.getOthRealBankName());
        eo.setOthRealProdType(entity.getOthRealProdType());
        eo.setOthRealBaseAcctNo(entity.getOthRealBaseAcctNo());
        eo.setContraAcctCcy(AcctCcy.byValue(entity.getContraAcctCcy()));
        eo.setFromCcy(AcctCcy.byValue(entity.getFromCcy()));
        eo.setOthSeqNo(entity.getOthSeqNo());
        eo.setPrimaryTranSeqNo(entity.getPrimaryTranSeqNo());
        eo.setToCcy(AcctCcy.byValue(entity.getToCcy()));
        eo.setFromAmount(entity.getFromAmount());
        eo.setToAmount(entity.getToAmount());
        eo.setDocType(DocType.byValue(entity.getDocType()));
        eo.setPrefix(entity.getPrefix());
        eo.setVoucherNo(entity.getVoucherNo());
        eo.setDocumentId(entity.getDocumentId());
        eo.setDocumentType(DocumentType.byValue(entity.getDocumentType()));
        eo.setClientName(entity.getClientName());
        eo.setClientType(ClientType.byValue(entity.getClientType()));
        eo.setBillNo(entity.getBillNo());
        eo.setBusinessUnit(BusinessUnit.byValue(entity.getBusinessUnit()));
        eo.setCashItem(CashItem.byValue(entity.getCashItem()));
        eo.setTranNote(entity.getTranNote());
        eo.setTranStatus(TranStatus.byValue(entity.getTranStatus()));
        eo.setAutoReversalFlag(IndividualFlag.byValue(entity.getAutoReversalFlag()));
        eo.setAmtCalcType(AmtCalcType.byValue(entity.getAmtCalcType()));
        eo.setChannel(SourceType.byValue(entity.getChannel()));
        eo.setAmtType(AmtType.byValue(entity.getAmtType()));
        eo.setBalType(BalType.byValue(entity.getBalType()));
        eo.setContraEquivAmt(entity.getContraEquivAmt());
        eo.setActualBalAmtFin(entity.getActualBalAmtFin());
        eo.setBaseEquivAmt(entity.getBaseEquivAmt());
        eo.setFlatRate(entity.getFlatRate());
        eo.setOvToAmount(entity.getOvToAmount());
        eo.setCrossRate(entity.getCrossRate());
        eo.setFromRateFlag(FromRateFlag.byValue(entity.getFromRateFlag()));
        eo.setFromXrate(entity.getFromXrate());
        eo.setOvCrossRate(entity.getOvCrossRate());
        eo.setToRateFlag(FromRateFlag.byValue(entity.getToRateFlag()));
        eo.setToXrate(entity.getToXrate());
        eo.setBizType(entity.getBizType());
        eo.setFinType(FinType.byValue(entity.getFinType()));
        eo.setQuoteType(QuoteType.byValue(entity.getQuoteType()));
        eo.setMediumFlag(IndividualFlag.byValue(entity.getMediumFlag()));
        eo.setMediumType(MediumType.byValue(entity.getMediumType()));
        eo.setOrigSystem(SourceModule.byValue(entity.getOrigSystem()));
        eo.setOthDocumentType(DocumentType.byValue(entity.getOthDocumentType()));
        eo.setPbkUpdFlag(IndividualFlag.byValue(entity.getPbkUpdFlag()));
        eo.setPrimaryEventType(entity.getPrimaryEventType());
        eo.setRateType(RateType.byValue(entity.getRateType()));
        eo.setTranMethod(TranMethod.byValue(entity.getTranMethod()));
        eo.setWithdrawalType(WithdrawalType.byValue(entity.getWithdrawalType()));
        eo.setBatchNo(entity.getBatchNo());
        eo.setBankSeqNo(entity.getBankSeqNo());
        eo.setCommissionClientTel(entity.getCommissionClientTel());
        eo.setLender(entity.getLender());
        eo.setLimitRefList(entity.getLimitRefList());
        eo.setCreateTimestamp(entity.getCreateTimestamp());
        eo.setOthBranchRegionalismCode(OthBranchRegionalismCode.byValue(entity.getOthBranchRegionalismCode()));
        eo.setLastChangeDate(entity.getLastChangeDate());
        eo.setOthDocumentId(entity.getOthDocumentId());
        eo.setOthRealBranchRegionCode(OthBranchRegionalismCode.byValue(entity.getOthRealBranchRegionCode()));
        eo.setOthRealDocumentId(entity.getOthRealDocumentId());
        eo.setOthRealDocumentType(DocumentType.byValue(entity.getOthRealDocumentType()));
        eo.setOthTranAddr(entity.getOthTranAddr());
        eo.setOthRealTranAddr(entity.getOthRealTranAddr());
        eo.setOthTranName(entity.getOthTranName());
        eo.setOthRealTranName(entity.getOthRealTranName());
        eo.setPayUnit(entity.getPayUnit());
        eo.setPrintCnt(entity.getPrintCnt());
        eo.setReceiptNo(entity.getReceiptNo());
        eo.setSendSystem(entity.getSendSystem());
        eo.setPriority(entity.getPriority());
        eo.setToId(QuoteType.byValue(entity.getToId()));
        eo.setServCharge(IndividualFlag.byValue(entity.getServCharge()));
        eo.setCommissionClientName(entity.getCommissionClientName());
        eo.setProfitCenter(ProfitCenter.byValue(entity.getProfitCenter()));
        eo.setProgramId(entity.getProgramId());
        eo.setSourceModule(SourceModule.byValue(entity.getSourceModule()));
        eo.setEffectDate(entity.getEffectDate());
        eo.setSystemCode(entity.getSystemCode());
        eo.setReversalSeqNo(entity.getReversalSeqNo());
        eo.setTerminalId(entity.getTerminalId());
        eo.setTraceId(entity.getTraceId());
        eo.setReversalTranType(TranType.byValue(entity.getReversalTranType()));
        eo.setReversalFlag(IndividualFlag.byValue(entity.getReversalFlag()));
        eo.setReversalDate(entity.getReversalDate());
        eo.setChannelDate(entity.getChannelDate());
        eo.setSettlementDate(entity.getSettlementDate());
        eo.setAccountingStatus(AccountingStatus.byValue(entity.getAccountingStatus()));
        eo.setGlPostedFlag(IndividualFlag.byValue(entity.getGlPostedFlag()));
        eo.setNarrative(entity.getNarrative());
        eo.setApprUserId(entity.getApprUserId());
        eo.setAuthUserId(entity.getAuthUserId());
        eo.setOrigTranTimestamp(entity.getOrigTranTimestamp());
        eo.setTranTimestamp(entity.getTranTimestamp());
        eo.setUserId(entity.getUserId());
        eo.setCompany(Company.byValue(entity.getCompany()));
        eo.setChequeDate(entity.getChequeDate());
        eo.setRemark(entity.getRemark());
        eo.setCashUsePlaceCode(IssCountry.byValue(entity.getCashUsePlaceCode()));
        eo.setCashUseRemark(CashUseRemark.byValue(entity.getCashUseRemark()));
        eo.setCashSourceCountry(IssCountry.byValue(entity.getCashSourceCountry()));
        eo.setCashSourceRemark(CashSourceRemark.byValue(entity.getCashSourceRemark()));
        eo.setTaeFlag(IndividualFlag.byValue(entity.getTaeFlag()));
        eo.setTranCode(entity.getTranCode());
        eo.setDealNo(entity.getDealNo());
        eo.setDealCode(entity.getDealCode());
        eo.setInputMediumId(entity.getInputMediumId());
        eo.setTellerTerminalType(TellerTerminalType.byValue(entity.getTellerTerminalType()));
        eo.setApprIndicator(ApprIndicator.byValue(entity.getApprIndicator()));
        eo.setApprTerminalId(entity.getApprTerminalId());
        eo.setPrintIndicator(IndividualFlag.byValue(entity.getPrintIndicator()));
        eo.setRemainTerm(RemainTerm.byValue(entity.getRemainTerm()));
        eo.setInputMediumType(TellerTerminalType.byValue(entity.getInputMediumType()));
        eo.setTranCountry(IssCountry.byValue(entity.getTranCountry()));
        eo.setLcyTranAmt(entity.getLcyTranAmt());
        eo.setCustRate(entity.getCustRate());
        eo.setAutoTradeFlag(IndividualFlag.byValue(entity.getAutoTradeFlag()));
        eo.setTreatsChannelNo(entity.getTreatsChannelNo());
        eo.setTreatsReference(entity.getTreatsReference());
        eo.setTackOverCcyRateOne(entity.getTackOverCcyRateOne());
        eo.setTackOverCcyRateTwo(entity.getTackOverCcyRateTwo());
        eo.setMaturityNarrative1(entity.getMaturityNarrative1());
        eo.setMaturityNarrative2(entity.getMaturityNarrative2());
        eo.setMaturityNarrative3(entity.getMaturityNarrative3());
        eo.setMaturityNarrative4(entity.getMaturityNarrative4());
        eo.setBaseCcyAmountOne(entity.getBaseCcyAmountOne());
        eo.setBaseCcyAmountTwo(entity.getBaseCcyAmountTwo());
        eo.setBusSeqNo(entity.getBusSeqNo());
        eo.setCashFromCode(entity.getCashFromCode());
        eo.setCashFromCountry(IssCountry.byValue(entity.getCashFromCountry()));
        eo.setCashToCode(entity.getCashToCode());
        eo.setCashToCountry(IssCountry.byValue(entity.getCashToCountry()));
        eo.setContraTranDate(entity.getContraTranDate());
        eo.setLoanProdType(entity.getLoanProdType());
        eo.setNarrativeCode(entity.getNarrativeCode());
        eo.setPiFlag(IndividualFlag.byValue(entity.getPiFlag()));
        eo.setReaccountCd(entity.getReaccountCd());
        eo.setMainSourceModule(SourceModule.byValue(entity.getMainSourceModule()));
        eo.setOldDataRemark(entity.getOldDataRemark());
        eo.setExchangeTranCode(entity.getExchangeTranCode());
        eo.setExchangeTranCodet(entity.getExchangeTranCodet());
        return eo;
    }

    public static RbTranHist eoToEntity(RbTranHistEO eo) {
        if (eo == null) {
            return null;
        }
        RbTranHist entity = new RbTranHist();
        entity.setSeqNo(eo.getSeqNo());
        entity.setChannelSeqNo(eo.getChannelSeqNo());
        entity.setSubSeqNo(eo.getSubSeqNo());
        entity.setTaeSubSeqNo(eo.getTaeSubSeqNo());
        entity.setSourceType(eo.getSourceType() == null ? null : eo.getSourceType().getValue());
        entity.setReference(eo.getReference());
        entity.setClientNo(eo.getClientNo());
        entity.setInternalKey(eo.getInternalKey());
        entity.setBaseAcctNo(eo.getBaseAcctNo());
        entity.setProdType(eo.getProdType());
        entity.setAcctCcy(eo.getAcctCcy() == null ? null : eo.getAcctCcy().getValue());
        entity.setAcctSeqNo(eo.getAcctSeqNo());
        entity.setSubAcctNo(eo.getSubAcctNo());
        entity.setAcctClass(eo.getAcctClass() == null ? null : eo.getAcctClass().getValue());
        entity.setAcctStatus(eo.getAcctStatus() == null ? null : eo.getAcctStatus().getValue());
        entity.setAcctRealFlag(eo.getAcctRealFlag() == null ? null : eo.getAcctRealFlag().getValue());
        entity.setAcctTranFlag(eo.getAcctTranFlag() == null ? null : eo.getAcctTranFlag().getValue());
        entity.setAcctDesc(eo.getAcctDesc());
        entity.setAcctBranch(eo.getAcctBranch() == null ? null : eo.getAcctBranch().getValue());
        entity.setEventType(eo.getEventType());
        entity.setTranDate(eo.getTranDate());
        entity.setTranBranch(eo.getTranBranch() == null ? null : eo.getTranBranch().getValue());
        entity.setCrDrInd(eo.getCrDrInd() == null ? null : eo.getCrDrInd().getValue());
        entity.setCcy(eo.getCcy() == null ? null : eo.getCcy().getValue());
        entity.setTranType(eo.getTranType() == null ? null : eo.getTranType().getValue());
        entity.setTranDesc(eo.getTranDesc());
        entity.setPreviousBalAmt(eo.getPreviousBalAmt());
        entity.setTranAmt(eo.getTranAmt());
        entity.setActualBal(eo.getActualBal());
        entity.setTranCategory(eo.getTranCategory() == null ? null : eo.getTranCategory().getValue());
        entity.setGlCode(eo.getGlCode());
        entity.setOthReference(eo.getOthReference());
        entity.setOthInternalKey(eo.getOthInternalKey());
        entity.setOthBaseAcctNo(eo.getOthBaseAcctNo());
        entity.setOthAcctCcy(eo.getOthAcctCcy() == null ? null : eo.getOthAcctCcy().getValue());
        entity.setOthAcctSeqNo(eo.getOthAcctSeqNo());
        entity.setFhSeqNo(eo.getFhSeqNo());
        entity.setOthProdType(eo.getOthProdType());
        entity.setOthAcctDesc(eo.getOthAcctDesc());
        entity.setOthBankCode(eo.getOthBankCode());
        entity.setOthBankName(eo.getOthBankName());
        entity.setOthBranch(eo.getOthBranch() == null ? null : eo.getOthBranch().getValue());
        entity.setOthRealBankCode(eo.getOthRealBankCode());
        entity.setOthRealBankName(eo.getOthRealBankName());
        entity.setOthRealProdType(eo.getOthRealProdType());
        entity.setOthRealBaseAcctNo(eo.getOthRealBaseAcctNo());
        entity.setContraAcctCcy(eo.getContraAcctCcy() == null ? null : eo.getContraAcctCcy().getValue());
        entity.setFromCcy(eo.getFromCcy() == null ? null : eo.getFromCcy().getValue());
        entity.setOthSeqNo(eo.getOthSeqNo());
        entity.setPrimaryTranSeqNo(eo.getPrimaryTranSeqNo());
        entity.setToCcy(eo.getToCcy() == null ? null : eo.getToCcy().getValue());
        entity.setFromAmount(eo.getFromAmount());
        entity.setToAmount(eo.getToAmount());
        entity.setDocType(eo.getDocType() == null ? null : eo.getDocType().getValue());
        entity.setPrefix(eo.getPrefix());
        entity.setVoucherNo(eo.getVoucherNo());
        entity.setDocumentId(eo.getDocumentId());
        entity.setDocumentType(eo.getDocumentType() == null ? null : eo.getDocumentType().getValue());
        entity.setClientName(eo.getClientName());
        entity.setClientType(eo.getClientType() == null ? null : eo.getClientType().getValue());
        entity.setBillNo(eo.getBillNo());
        entity.setBusinessUnit(eo.getBusinessUnit() == null ? null : eo.getBusinessUnit().getValue());
        entity.setCashItem(eo.getCashItem() == null ? null : eo.getCashItem().getValue());
        entity.setTranNote(eo.getTranNote());
        entity.setTranStatus(eo.getTranStatus() == null ? null : eo.getTranStatus().getValue());
        entity.setAutoReversalFlag(eo.getAutoReversalFlag() == null ? null : eo.getAutoReversalFlag().getValue());
        entity.setAmtCalcType(eo.getAmtCalcType() == null ? null : eo.getAmtCalcType().getValue());
        entity.setChannel(eo.getChannel() == null ? null : eo.getChannel().getValue());
        entity.setAmtType(eo.getAmtType() == null ? null : eo.getAmtType().getValue());
        entity.setBalType(eo.getBalType() == null ? null : eo.getBalType().getValue());
        entity.setContraEquivAmt(eo.getContraEquivAmt());
        entity.setActualBalAmtFin(eo.getActualBalAmtFin());
        entity.setBaseEquivAmt(eo.getBaseEquivAmt());
        entity.setFlatRate(eo.getFlatRate());
        entity.setOvToAmount(eo.getOvToAmount());
        entity.setCrossRate(eo.getCrossRate());
        entity.setFromRateFlag(eo.getFromRateFlag() == null ? null : eo.getFromRateFlag().getValue());
        entity.setFromXrate(eo.getFromXrate());
        entity.setOvCrossRate(eo.getOvCrossRate());
        entity.setToRateFlag(eo.getToRateFlag() == null ? null : eo.getToRateFlag().getValue());
        entity.setToXrate(eo.getToXrate());
        entity.setBizType(eo.getBizType());
        entity.setFinType(eo.getFinType() == null ? null : eo.getFinType().getValue());
        entity.setQuoteType(eo.getQuoteType() == null ? null : eo.getQuoteType().getValue());
        entity.setMediumFlag(eo.getMediumFlag() == null ? null : eo.getMediumFlag().getValue());
        entity.setMediumType(eo.getMediumType() == null ? null : eo.getMediumType().getValue());
        entity.setOrigSystem(eo.getOrigSystem() == null ? null : eo.getOrigSystem().getValue());
        entity.setOthDocumentType(eo.getOthDocumentType() == null ? null : eo.getOthDocumentType().getValue());
        entity.setPbkUpdFlag(eo.getPbkUpdFlag() == null ? null : eo.getPbkUpdFlag().getValue());
        entity.setPrimaryEventType(eo.getPrimaryEventType());
        entity.setRateType(eo.getRateType() == null ? null : eo.getRateType().getValue());
        entity.setTranMethod(eo.getTranMethod() == null ? null : eo.getTranMethod().getValue());
        entity.setWithdrawalType(eo.getWithdrawalType() == null ? null : eo.getWithdrawalType().getValue());
        entity.setBatchNo(eo.getBatchNo());
        entity.setBankSeqNo(eo.getBankSeqNo());
        entity.setCommissionClientTel(eo.getCommissionClientTel());
        entity.setLender(eo.getLender());
        entity.setLimitRefList(eo.getLimitRefList());
        entity.setCreateTimestamp(eo.getCreateTimestamp());
        entity.setOthBranchRegionalismCode(eo.getOthBranchRegionalismCode() == null ? null : eo.getOthBranchRegionalismCode().getValue());
        entity.setLastChangeDate(eo.getLastChangeDate());
        entity.setOthDocumentId(eo.getOthDocumentId());
        entity.setOthRealBranchRegionCode(eo.getOthRealBranchRegionCode() == null ? null : eo.getOthRealBranchRegionCode().getValue());
        entity.setOthRealDocumentId(eo.getOthRealDocumentId());
        entity.setOthRealDocumentType(eo.getOthRealDocumentType() == null ? null : eo.getOthRealDocumentType().getValue());
        entity.setOthTranAddr(eo.getOthTranAddr());
        entity.setOthRealTranAddr(eo.getOthRealTranAddr());
        entity.setOthTranName(eo.getOthTranName());
        entity.setOthRealTranName(eo.getOthRealTranName());
        entity.setPayUnit(eo.getPayUnit());
        entity.setPrintCnt(eo.getPrintCnt());
        entity.setReceiptNo(eo.getReceiptNo());
        entity.setSendSystem(eo.getSendSystem());
        entity.setPriority(eo.getPriority());
        entity.setToId(eo.getToId() == null ? null : eo.getToId().getValue());
        entity.setServCharge(eo.getServCharge() == null ? null : eo.getServCharge().getValue());
        entity.setCommissionClientName(eo.getCommissionClientName());
        entity.setProfitCenter(eo.getProfitCenter() == null ? null : eo.getProfitCenter().getValue());
        entity.setProgramId(eo.getProgramId());
        entity.setSourceModule(eo.getSourceModule() == null ? null : eo.getSourceModule().getValue());
        entity.setEffectDate(eo.getEffectDate());
        entity.setSystemCode(eo.getSystemCode());
        entity.setReversalSeqNo(eo.getReversalSeqNo());
        entity.setTerminalId(eo.getTerminalId());
        entity.setTraceId(eo.getTraceId());
        entity.setReversalTranType(eo.getReversalTranType() == null ? null : eo.getReversalTranType().getValue());
        entity.setReversalFlag(eo.getReversalFlag() == null ? null : eo.getReversalFlag().getValue());
        entity.setReversalDate(eo.getReversalDate());
        entity.setChannelDate(eo.getChannelDate());
        entity.setSettlementDate(eo.getSettlementDate());
        entity.setAccountingStatus(eo.getAccountingStatus() == null ? null : eo.getAccountingStatus().getValue());
        entity.setGlPostedFlag(eo.getGlPostedFlag() == null ? null : eo.getGlPostedFlag().getValue());
        entity.setNarrative(eo.getNarrative());
        entity.setApprUserId(eo.getApprUserId());
        entity.setAuthUserId(eo.getAuthUserId());
        entity.setOrigTranTimestamp(eo.getOrigTranTimestamp());
        entity.setTranTimestamp(eo.getTranTimestamp());
        entity.setUserId(eo.getUserId());
        entity.setCompany(eo.getCompany() == null ? null : eo.getCompany().getValue());
        entity.setChequeDate(eo.getChequeDate());
        entity.setRemark(eo.getRemark());
        entity.setCashUsePlaceCode(eo.getCashUsePlaceCode() == null ? null : eo.getCashUsePlaceCode().getValue());
        entity.setCashUseRemark(eo.getCashUseRemark() == null ? null : eo.getCashUseRemark().getValue());
        entity.setCashSourceCountry(eo.getCashSourceCountry() == null ? null : eo.getCashSourceCountry().getValue());
        entity.setCashSourceRemark(eo.getCashSourceRemark() == null ? null : eo.getCashSourceRemark().getValue());
        entity.setTaeFlag(eo.getTaeFlag() == null ? null : eo.getTaeFlag().getValue());
        entity.setTranCode(eo.getTranCode());
        entity.setDealNo(eo.getDealNo());
        entity.setDealCode(eo.getDealCode());
        entity.setInputMediumId(eo.getInputMediumId());
        entity.setTellerTerminalType(eo.getTellerTerminalType() == null ? null : eo.getTellerTerminalType().getValue());
        entity.setApprIndicator(eo.getApprIndicator() == null ? null : eo.getApprIndicator().getValue());
        entity.setApprTerminalId(eo.getApprTerminalId());
        entity.setPrintIndicator(eo.getPrintIndicator() == null ? null : eo.getPrintIndicator().getValue());
        entity.setRemainTerm(eo.getRemainTerm() == null ? null : eo.getRemainTerm().getValue());
        entity.setInputMediumType(eo.getInputMediumType() == null ? null : eo.getInputMediumType().getValue());
        entity.setTranCountry(eo.getTranCountry() == null ? null : eo.getTranCountry().getValue());
        entity.setLcyTranAmt(eo.getLcyTranAmt());
        entity.setCustRate(eo.getCustRate());
        entity.setAutoTradeFlag(eo.getAutoTradeFlag() == null ? null : eo.getAutoTradeFlag().getValue());
        entity.setTreatsChannelNo(eo.getTreatsChannelNo());
        entity.setTreatsReference(eo.getTreatsReference());
        entity.setTackOverCcyRateOne(eo.getTackOverCcyRateOne());
        entity.setTackOverCcyRateTwo(eo.getTackOverCcyRateTwo());
        entity.setMaturityNarrative1(eo.getMaturityNarrative1());
        entity.setMaturityNarrative2(eo.getMaturityNarrative2());
        entity.setMaturityNarrative3(eo.getMaturityNarrative3());
        entity.setMaturityNarrative4(eo.getMaturityNarrative4());
        entity.setBaseCcyAmountOne(eo.getBaseCcyAmountOne());
        entity.setBaseCcyAmountTwo(eo.getBaseCcyAmountTwo());
        entity.setBusSeqNo(eo.getBusSeqNo());
        entity.setCashFromCode(eo.getCashFromCode());
        entity.setCashFromCountry(eo.getCashFromCountry() == null ? null : eo.getCashFromCountry().getValue());
        entity.setCashToCode(eo.getCashToCode());
        entity.setCashToCountry(eo.getCashToCountry() == null ? null : eo.getCashToCountry().getValue());
        entity.setContraTranDate(eo.getContraTranDate());
        entity.setLoanProdType(eo.getLoanProdType());
        entity.setNarrativeCode(eo.getNarrativeCode());
        entity.setPiFlag(eo.getPiFlag() == null ? null : eo.getPiFlag().getValue());
        entity.setReaccountCd(eo.getReaccountCd());
        entity.setMainSourceModule(eo.getMainSourceModule() == null ? null : eo.getMainSourceModule().getValue());
        entity.setOldDataRemark(eo.getOldDataRemark());
        entity.setExchangeTranCode(eo.getExchangeTranCode());
        entity.setExchangeTranCodet(eo.getExchangeTranCodet());
        return entity;
    }

    public static RbTranHistExample eoToEntityExample(RbTranHistEO eo) {
        if (eo == null) {
            return null;
        }
        RbTranHistExample example = new RbTranHistExample();
        RbTranHistExample.Criteria criteria = example.createCriteria();
        if (eo.getSeqNo() != null) criteria.andSeqNoEqualTo(eo.getSeqNo());
        if (eo.getChannelSeqNo() != null) criteria.andChannelSeqNoEqualTo(eo.getChannelSeqNo());
        if (eo.getSubSeqNo() != null) criteria.andSubSeqNoEqualTo(eo.getSubSeqNo());
        if (eo.getTaeSubSeqNo() != null) criteria.andTaeSubSeqNoEqualTo(eo.getTaeSubSeqNo());
        if (eo.getSourceType() != null) criteria.andSourceTypeEqualTo(eo.getSourceType().getValue());
        if (eo.getReference() != null) criteria.andReferenceEqualTo(eo.getReference());
        if (eo.getClientNo() != null) criteria.andClientNoEqualTo(eo.getClientNo());
        if (eo.getInternalKey() != null) criteria.andInternalKeyEqualTo(eo.getInternalKey());
        if (eo.getBaseAcctNo() != null) criteria.andBaseAcctNoEqualTo(eo.getBaseAcctNo());
        if (eo.getProdType() != null) criteria.andProdTypeEqualTo(eo.getProdType());
        if (eo.getAcctCcy() != null) criteria.andAcctCcyEqualTo(eo.getAcctCcy().getValue());
        if (eo.getAcctSeqNo() != null) criteria.andAcctSeqNoEqualTo(eo.getAcctSeqNo());
        if (eo.getSubAcctNo() != null) criteria.andSubAcctNoEqualTo(eo.getSubAcctNo());
        if (eo.getAcctClass() != null) criteria.andAcctClassEqualTo(eo.getAcctClass().getValue());
        if (eo.getAcctStatus() != null) criteria.andAcctStatusEqualTo(eo.getAcctStatus().getValue());
        if (eo.getAcctRealFlag() != null) criteria.andAcctRealFlagEqualTo(eo.getAcctRealFlag().getValue());
        if (eo.getAcctTranFlag() != null) criteria.andAcctTranFlagEqualTo(eo.getAcctTranFlag().getValue());
        if (eo.getAcctDesc() != null) criteria.andAcctDescEqualTo(eo.getAcctDesc());
        if (eo.getAcctBranch() != null) criteria.andAcctBranchEqualTo(eo.getAcctBranch().getValue());
        if (eo.getEventType() != null) criteria.andEventTypeEqualTo(eo.getEventType());
        if (eo.getTranDate() != null) criteria.andTranDateEqualTo(eo.getTranDate());
        if (eo.getTranBranch() != null) criteria.andTranBranchEqualTo(eo.getTranBranch().getValue());
        if (eo.getCrDrInd() != null) criteria.andCrDrIndEqualTo(eo.getCrDrInd().getValue());
        if (eo.getCcy() != null) criteria.andCcyEqualTo(eo.getCcy().getValue());
        if (eo.getTranType() != null) criteria.andTranTypeEqualTo(eo.getTranType().getValue());
        if (eo.getTranDesc() != null) criteria.andTranDescEqualTo(eo.getTranDesc());
        if (eo.getPreviousBalAmt() != null) criteria.andPreviousBalAmtEqualTo(eo.getPreviousBalAmt());
        if (eo.getTranAmt() != null) criteria.andTranAmtEqualTo(eo.getTranAmt());
        if (eo.getActualBal() != null) criteria.andActualBalEqualTo(eo.getActualBal());
        if (eo.getTranCategory() != null) criteria.andTranCategoryEqualTo(eo.getTranCategory().getValue());
        if (eo.getGlCode() != null) criteria.andGlCodeEqualTo(eo.getGlCode());
        if (eo.getOthReference() != null) criteria.andOthReferenceEqualTo(eo.getOthReference());
        if (eo.getOthInternalKey() != null) criteria.andOthInternalKeyEqualTo(eo.getOthInternalKey());
        if (eo.getOthBaseAcctNo() != null) criteria.andOthBaseAcctNoEqualTo(eo.getOthBaseAcctNo());
        if (eo.getOthAcctCcy() != null) criteria.andOthAcctCcyEqualTo(eo.getOthAcctCcy().getValue());
        if (eo.getOthAcctSeqNo() != null) criteria.andOthAcctSeqNoEqualTo(eo.getOthAcctSeqNo());
        if (eo.getFhSeqNo() != null) criteria.andFhSeqNoEqualTo(eo.getFhSeqNo());
        if (eo.getOthProdType() != null) criteria.andOthProdTypeEqualTo(eo.getOthProdType());
        if (eo.getOthAcctDesc() != null) criteria.andOthAcctDescEqualTo(eo.getOthAcctDesc());
        if (eo.getOthBankCode() != null) criteria.andOthBankCodeEqualTo(eo.getOthBankCode());
        if (eo.getOthBankName() != null) criteria.andOthBankNameEqualTo(eo.getOthBankName());
        if (eo.getOthBranch() != null) criteria.andOthBranchEqualTo(eo.getOthBranch().getValue());
        if (eo.getOthRealBankCode() != null) criteria.andOthRealBankCodeEqualTo(eo.getOthRealBankCode());
        if (eo.getOthRealBankName() != null) criteria.andOthRealBankNameEqualTo(eo.getOthRealBankName());
        if (eo.getOthRealProdType() != null) criteria.andOthRealProdTypeEqualTo(eo.getOthRealProdType());
        if (eo.getOthRealBaseAcctNo() != null) criteria.andOthRealBaseAcctNoEqualTo(eo.getOthRealBaseAcctNo());
        if (eo.getContraAcctCcy() != null) criteria.andContraAcctCcyEqualTo(eo.getContraAcctCcy().getValue());
        if (eo.getFromCcy() != null) criteria.andFromCcyEqualTo(eo.getFromCcy().getValue());
        if (eo.getOthSeqNo() != null) criteria.andOthSeqNoEqualTo(eo.getOthSeqNo());
        if (eo.getPrimaryTranSeqNo() != null) criteria.andPrimaryTranSeqNoEqualTo(eo.getPrimaryTranSeqNo());
        if (eo.getToCcy() != null) criteria.andToCcyEqualTo(eo.getToCcy().getValue());
        if (eo.getFromAmount() != null) criteria.andFromAmountEqualTo(eo.getFromAmount());
        if (eo.getToAmount() != null) criteria.andToAmountEqualTo(eo.getToAmount());
        if (eo.getDocType() != null) criteria.andDocTypeEqualTo(eo.getDocType().getValue());
        if (eo.getPrefix() != null) criteria.andPrefixEqualTo(eo.getPrefix());
        if (eo.getVoucherNo() != null) criteria.andVoucherNoEqualTo(eo.getVoucherNo());
        if (eo.getDocumentId() != null) criteria.andDocumentIdEqualTo(eo.getDocumentId());
        if (eo.getDocumentType() != null) criteria.andDocumentTypeEqualTo(eo.getDocumentType().getValue());
        if (eo.getClientName() != null) criteria.andClientNameEqualTo(eo.getClientName());
        if (eo.getClientType() != null) criteria.andClientTypeEqualTo(eo.getClientType().getValue());
        if (eo.getBillNo() != null) criteria.andBillNoEqualTo(eo.getBillNo());
        if (eo.getBusinessUnit() != null) criteria.andBusinessUnitEqualTo(eo.getBusinessUnit().getValue());
        if (eo.getCashItem() != null) criteria.andCashItemEqualTo(eo.getCashItem().getValue());
        if (eo.getTranNote() != null) criteria.andTranNoteEqualTo(eo.getTranNote());
        if (eo.getTranStatus() != null) criteria.andTranStatusEqualTo(eo.getTranStatus().getValue());
        if (eo.getAutoReversalFlag() != null) criteria.andAutoReversalFlagEqualTo(eo.getAutoReversalFlag().getValue());
        if (eo.getAmtCalcType() != null) criteria.andAmtCalcTypeEqualTo(eo.getAmtCalcType().getValue());
        if (eo.getChannel() != null) criteria.andChannelEqualTo(eo.getChannel().getValue());
        if (eo.getAmtType() != null) criteria.andAmtTypeEqualTo(eo.getAmtType().getValue());
        if (eo.getBalType() != null) criteria.andBalTypeEqualTo(eo.getBalType().getValue());
        if (eo.getContraEquivAmt() != null) criteria.andContraEquivAmtEqualTo(eo.getContraEquivAmt());
        if (eo.getActualBalAmtFin() != null) criteria.andActualBalAmtFinEqualTo(eo.getActualBalAmtFin());
        if (eo.getBaseEquivAmt() != null) criteria.andBaseEquivAmtEqualTo(eo.getBaseEquivAmt());
        if (eo.getFlatRate() != null) criteria.andFlatRateEqualTo(eo.getFlatRate());
        if (eo.getOvToAmount() != null) criteria.andOvToAmountEqualTo(eo.getOvToAmount());
        if (eo.getCrossRate() != null) criteria.andCrossRateEqualTo(eo.getCrossRate());
        if (eo.getFromRateFlag() != null) criteria.andFromRateFlagEqualTo(eo.getFromRateFlag().getValue());
        if (eo.getFromXrate() != null) criteria.andFromXrateEqualTo(eo.getFromXrate());
        if (eo.getOvCrossRate() != null) criteria.andOvCrossRateEqualTo(eo.getOvCrossRate());
        if (eo.getToRateFlag() != null) criteria.andToRateFlagEqualTo(eo.getToRateFlag().getValue());
        if (eo.getToXrate() != null) criteria.andToXrateEqualTo(eo.getToXrate());
        if (eo.getBizType() != null) criteria.andBizTypeEqualTo(eo.getBizType());
        if (eo.getFinType() != null) criteria.andFinTypeEqualTo(eo.getFinType().getValue());
        if (eo.getQuoteType() != null) criteria.andQuoteTypeEqualTo(eo.getQuoteType().getValue());
        if (eo.getMediumFlag() != null) criteria.andMediumFlagEqualTo(eo.getMediumFlag().getValue());
        if (eo.getMediumType() != null) criteria.andMediumTypeEqualTo(eo.getMediumType().getValue());
        if (eo.getOrigSystem() != null) criteria.andOrigSystemEqualTo(eo.getOrigSystem().getValue());
        if (eo.getOthDocumentType() != null) criteria.andOthDocumentTypeEqualTo(eo.getOthDocumentType().getValue());
        if (eo.getPbkUpdFlag() != null) criteria.andPbkUpdFlagEqualTo(eo.getPbkUpdFlag().getValue());
        if (eo.getPrimaryEventType() != null) criteria.andPrimaryEventTypeEqualTo(eo.getPrimaryEventType());
        if (eo.getRateType() != null) criteria.andRateTypeEqualTo(eo.getRateType().getValue());
        if (eo.getTranMethod() != null) criteria.andTranMethodEqualTo(eo.getTranMethod().getValue());
        if (eo.getWithdrawalType() != null) criteria.andWithdrawalTypeEqualTo(eo.getWithdrawalType().getValue());
        if (eo.getBatchNo() != null) criteria.andBatchNoEqualTo(eo.getBatchNo());
        if (eo.getBankSeqNo() != null) criteria.andBankSeqNoEqualTo(eo.getBankSeqNo());
        if (eo.getCommissionClientTel() != null) criteria.andCommissionClientTelEqualTo(eo.getCommissionClientTel());
        if (eo.getLender() != null) criteria.andLenderEqualTo(eo.getLender());
        if (eo.getLimitRefList() != null) criteria.andLimitRefListEqualTo(eo.getLimitRefList());
        if (eo.getCreateTimestamp() != null) criteria.andCreateTimestampEqualTo(eo.getCreateTimestamp());
        if (eo.getOthBranchRegionalismCode() != null) criteria.andOthBranchRegionalismCodeEqualTo(eo.getOthBranchRegionalismCode().getValue());
        if (eo.getLastChangeDate() != null) criteria.andLastChangeDateEqualTo(eo.getLastChangeDate());
        if (eo.getOthDocumentId() != null) criteria.andOthDocumentIdEqualTo(eo.getOthDocumentId());
        if (eo.getOthRealBranchRegionCode() != null) criteria.andOthRealBranchRegionCodeEqualTo(eo.getOthRealBranchRegionCode().getValue());
        if (eo.getOthRealDocumentId() != null) criteria.andOthRealDocumentIdEqualTo(eo.getOthRealDocumentId());
        if (eo.getOthRealDocumentType() != null) criteria.andOthRealDocumentTypeEqualTo(eo.getOthRealDocumentType().getValue());
        if (eo.getOthTranAddr() != null) criteria.andOthTranAddrEqualTo(eo.getOthTranAddr());
        if (eo.getOthRealTranAddr() != null) criteria.andOthRealTranAddrEqualTo(eo.getOthRealTranAddr());
        if (eo.getOthTranName() != null) criteria.andOthTranNameEqualTo(eo.getOthTranName());
        if (eo.getOthRealTranName() != null) criteria.andOthRealTranNameEqualTo(eo.getOthRealTranName());
        if (eo.getPayUnit() != null) criteria.andPayUnitEqualTo(eo.getPayUnit());
        if (eo.getPrintCnt() != null) criteria.andPrintCntEqualTo(eo.getPrintCnt());
        if (eo.getReceiptNo() != null) criteria.andReceiptNoEqualTo(eo.getReceiptNo());
        if (eo.getSendSystem() != null) criteria.andSendSystemEqualTo(eo.getSendSystem());
        if (eo.getPriority() != null) criteria.andPriorityEqualTo(eo.getPriority());
        if (eo.getToId() != null) criteria.andToIdEqualTo(eo.getToId().getValue());
        if (eo.getServCharge() != null) criteria.andServChargeEqualTo(eo.getServCharge().getValue());
        if (eo.getCommissionClientName() != null) criteria.andCommissionClientNameEqualTo(eo.getCommissionClientName());
        if (eo.getProfitCenter() != null) criteria.andProfitCenterEqualTo(eo.getProfitCenter().getValue());
        if (eo.getProgramId() != null) criteria.andProgramIdEqualTo(eo.getProgramId());
        if (eo.getSourceModule() != null) criteria.andSourceModuleEqualTo(eo.getSourceModule().getValue());
        if (eo.getEffectDate() != null) criteria.andEffectDateEqualTo(eo.getEffectDate());
        if (eo.getSystemCode() != null) criteria.andSystemCodeEqualTo(eo.getSystemCode());
        if (eo.getReversalSeqNo() != null) criteria.andReversalSeqNoEqualTo(eo.getReversalSeqNo());
        if (eo.getTerminalId() != null) criteria.andTerminalIdEqualTo(eo.getTerminalId());
        if (eo.getTraceId() != null) criteria.andTraceIdEqualTo(eo.getTraceId());
        if (eo.getReversalTranType() != null) criteria.andReversalTranTypeEqualTo(eo.getReversalTranType().getValue());
        if (eo.getReversalFlag() != null) criteria.andReversalFlagEqualTo(eo.getReversalFlag().getValue());
        if (eo.getReversalDate() != null) criteria.andReversalDateEqualTo(eo.getReversalDate());
        if (eo.getChannelDate() != null) criteria.andChannelDateEqualTo(eo.getChannelDate());
        if (eo.getSettlementDate() != null) criteria.andSettlementDateEqualTo(eo.getSettlementDate());
        if (eo.getAccountingStatus() != null) criteria.andAccountingStatusEqualTo(eo.getAccountingStatus().getValue());
        if (eo.getGlPostedFlag() != null) criteria.andGlPostedFlagEqualTo(eo.getGlPostedFlag().getValue());
        if (eo.getNarrative() != null) criteria.andNarrativeEqualTo(eo.getNarrative());
        if (eo.getApprUserId() != null) criteria.andApprUserIdEqualTo(eo.getApprUserId());
        if (eo.getAuthUserId() != null) criteria.andAuthUserIdEqualTo(eo.getAuthUserId());
        if (eo.getOrigTranTimestamp() != null) criteria.andOrigTranTimestampEqualTo(eo.getOrigTranTimestamp());
        if (eo.getTranTimestamp() != null) criteria.andTranTimestampEqualTo(eo.getTranTimestamp());
        if (eo.getUserId() != null) criteria.andUserIdEqualTo(eo.getUserId());
        if (eo.getCompany() != null) criteria.andCompanyEqualTo(eo.getCompany().getValue());
        if (eo.getChequeDate() != null) criteria.andChequeDateEqualTo(eo.getChequeDate());
        if (eo.getRemark() != null) criteria.andRemarkEqualTo(eo.getRemark());
        if (eo.getCashUsePlaceCode() != null) criteria.andCashUsePlaceCodeEqualTo(eo.getCashUsePlaceCode().getValue());
        if (eo.getCashUseRemark() != null) criteria.andCashUseRemarkEqualTo(eo.getCashUseRemark().getValue());
        if (eo.getCashSourceCountry() != null) criteria.andCashSourceCountryEqualTo(eo.getCashSourceCountry().getValue());
        if (eo.getCashSourceRemark() != null) criteria.andCashSourceRemarkEqualTo(eo.getCashSourceRemark().getValue());
        if (eo.getTaeFlag() != null) criteria.andTaeFlagEqualTo(eo.getTaeFlag().getValue());
        if (eo.getTranCode() != null) criteria.andTranCodeEqualTo(eo.getTranCode());
        if (eo.getDealNo() != null) criteria.andDealNoEqualTo(eo.getDealNo());
        if (eo.getDealCode() != null) criteria.andDealCodeEqualTo(eo.getDealCode());
        if (eo.getInputMediumId() != null) criteria.andInputMediumIdEqualTo(eo.getInputMediumId());
        if (eo.getTellerTerminalType() != null) criteria.andTellerTerminalTypeEqualTo(eo.getTellerTerminalType().getValue());
        if (eo.getApprIndicator() != null) criteria.andApprIndicatorEqualTo(eo.getApprIndicator().getValue());
        if (eo.getApprTerminalId() != null) criteria.andApprTerminalIdEqualTo(eo.getApprTerminalId());
        if (eo.getPrintIndicator() != null) criteria.andPrintIndicatorEqualTo(eo.getPrintIndicator().getValue());
        if (eo.getRemainTerm() != null) criteria.andRemainTermEqualTo(eo.getRemainTerm().getValue());
        if (eo.getInputMediumType() != null) criteria.andInputMediumTypeEqualTo(eo.getInputMediumType().getValue());
        if (eo.getTranCountry() != null) criteria.andTranCountryEqualTo(eo.getTranCountry().getValue());
        if (eo.getLcyTranAmt() != null) criteria.andLcyTranAmtEqualTo(eo.getLcyTranAmt());
        if (eo.getCustRate() != null) criteria.andCustRateEqualTo(eo.getCustRate());
        if (eo.getAutoTradeFlag() != null) criteria.andAutoTradeFlagEqualTo(eo.getAutoTradeFlag().getValue());
        if (eo.getTreatsChannelNo() != null) criteria.andTreatsChannelNoEqualTo(eo.getTreatsChannelNo());
        if (eo.getTreatsReference() != null) criteria.andTreatsReferenceEqualTo(eo.getTreatsReference());
        if (eo.getTackOverCcyRateOne() != null) criteria.andTackOverCcyRateOneEqualTo(eo.getTackOverCcyRateOne());
        if (eo.getTackOverCcyRateTwo() != null) criteria.andTackOverCcyRateTwoEqualTo(eo.getTackOverCcyRateTwo());
        if (eo.getMaturityNarrative1() != null) criteria.andMaturityNarrative1EqualTo(eo.getMaturityNarrative1());
        if (eo.getMaturityNarrative2() != null) criteria.andMaturityNarrative2EqualTo(eo.getMaturityNarrative2());
        if (eo.getMaturityNarrative3() != null) criteria.andMaturityNarrative3EqualTo(eo.getMaturityNarrative3());
        if (eo.getMaturityNarrative4() != null) criteria.andMaturityNarrative4EqualTo(eo.getMaturityNarrative4());
        if (eo.getBaseCcyAmountOne() != null) criteria.andBaseCcyAmountOneEqualTo(eo.getBaseCcyAmountOne());
        if (eo.getBaseCcyAmountTwo() != null) criteria.andBaseCcyAmountTwoEqualTo(eo.getBaseCcyAmountTwo());
        if (eo.getBusSeqNo() != null) criteria.andBusSeqNoEqualTo(eo.getBusSeqNo());
        if (eo.getCashFromCode() != null) criteria.andCashFromCodeEqualTo(eo.getCashFromCode());
        if (eo.getCashFromCountry() != null) criteria.andCashFromCountryEqualTo(eo.getCashFromCountry().getValue());
        if (eo.getCashToCode() != null) criteria.andCashToCodeEqualTo(eo.getCashToCode());
        if (eo.getCashToCountry() != null) criteria.andCashToCountryEqualTo(eo.getCashToCountry().getValue());
        if (eo.getContraTranDate() != null) criteria.andContraTranDateEqualTo(eo.getContraTranDate());
        if (eo.getLoanProdType() != null) criteria.andLoanProdTypeEqualTo(eo.getLoanProdType());
        if (eo.getNarrativeCode() != null) criteria.andNarrativeCodeEqualTo(eo.getNarrativeCode());
        if (eo.getPiFlag() != null) criteria.andPiFlagEqualTo(eo.getPiFlag().getValue());
        if (eo.getReaccountCd() != null) criteria.andReaccountCdEqualTo(eo.getReaccountCd());
        if (eo.getMainSourceModule() != null) criteria.andMainSourceModuleEqualTo(eo.getMainSourceModule().getValue());
        if (eo.getOldDataRemark() != null) criteria.andOldDataRemarkEqualTo(eo.getOldDataRemark());
        if (eo.getExchangeTranCode() != null) criteria.andExchangeTranCodeEqualTo(eo.getExchangeTranCode());
        if (eo.getExchangeTranCodet() != null) criteria.andExchangeTranCodetEqualTo(eo.getExchangeTranCodet());
        return example;
    }
}